Implement request #986 rename systems.
freeorion/freeorion pull request #1002
Opened 2016-09-29 07:27 UTC by LGM-Doyle

This PR add the ability to rename systems as per request #986.

It follows #993.  After #993 is merged it is only 4 commits.

It add a context menu element to the SidePanel system name to rename the system if the system is owned by the player.

This PR changes the game mechanic of system ownership.  Previously systems could not be owned.  This PR changes system ownership.   An empire owns a system if is owns at least one planet in a system and no other empire owns any planets.  A system is unowned if no empire owns any planets or multiple empires own planets.

2016-09-29 07:37 UTC, geoffthemedio commented
Can you do this without putting in all the unrelated Font reworking commits?

2016-09-29 07:46 UTC, LGM-Doyle commented
Yes, if I want to do it now and then redo it later.
This was easier, because it sits on top of the `SidePanel` code which uses the list box changes.

2016-09-29 08:20 UTC, adrianbroher commented
Sneaking in unrelated changes is not welcome.

2016-09-29 08:21 UTC, LGM-Doyle commented
What was I sneaking in?

2016-09-29 08:24 UTC, adrianbroher commented
> What was I sneaking in?

#989 and #993

2016-09-29 08:28 UTC, LGM-Doyle commented
I thought that I had clearly stated in the PR that it followed #993.  The intent was so that no one would waste time implementing #986 when it was already done.

In future how would you suggest I approach this if explaining it in the PR is in adequate?

2016-09-29 08:39 UTC, adrianbroher commented
> In future how would you suggest I approach this if explaining it in the PR is in adequate?

The problem is not that you noted it in the OP.  The problem I have with this is that this is putting up pressure to accept the PRs without review by making an unrelated and somewhat popular feature depend on it.

Currently it is not even clear if the mentioned PRs will be accepted regardless of the well intention and thought put into it because nobody dares to really review it (see https://github.com/freeorion/freeorion/pull/989#pullrequestreview-2006282 and https://github.com/freeorion/freeorion/pull/989#issuecomment-249640103).

2016-09-29 08:43 UTC, LGM-Doyle commented
That is fair.

I didn't intend to pressure anyone to accept the prior commits.  I just didn't feel like writing the code twice.

2016-09-29 08:44 UTC, adrianbroher commented
> I just didn't feel like writing the code twice.

I can understand that perfectly.  But unless the depending PRs are merged there is nothing to do.

Reopening the PR because the response wasn't well thought out.

2016-09-29 08:47 UTC, LGM-Doyle commented
Thanks.

If the other PRs are not merged, I'll refactor it to work on its own.

2016-11-07 20:32 UTC, geoffthemedio commented
rebase?

2016-11-15 16:09 UTC, LGM-Doyle commented
Rebased.

2016-11-20 22:20 UTC, geoffthemedio requested changes

2016-11-20 22:20 UTC, geoffthemedio commented on universe/System.h
> +    int                     Owner() const;
if the base class function is virtual, label the derived class as such as well

2016-11-21 09:59 UTC, merged