Create Font::ChangeTemplatedText to allow a quick change of a text element.
freeorion/freeorion pull request #1041
Opened 2016-10-07 22:04 UTC by LGM-Doyle

This PR follows #1040

2016-11-01 20:53 UTC, LGM-Doyle commented
Rebased.

2016-11-01 21:53 UTC, geoffthemedio requested changes

2016-11-01 21:53 UTC, geoffthemedio commented on GG/GG/TextControl.h
> +    void ChangeTemplatedText(const std::string& new_text, size_t targ_offset);
Description and name are unclear. Does this insert text and push the following back to make room? Or replace the text of one text element starting immediately before/after the offset? Or replace all text start from the specified offset?

2016-11-01 21:53 UTC, geoffthemedio commented on GG/GG/Font.h
> +    void ChangeTemplatedText(std::string& text,
Why "templated" ?

2016-11-02 07:22 UTC, LGM-Doyle reviewed
I've tried to expand and clarify the comments for the declarations of both of these functions, including an example.

2016-11-02 08:40 UTC, merged