Improve handling of empty line data.
freeorion/freeorion pull request #1042
Opened 2016-10-07 22:05 UTC by LGM-Doyle

This PR follows #1041

2016-10-23 10:18 UTC, geoffthemedio commented
Builds and seems to run OK.

2016-11-02 19:52 UTC, LGM-Doyle commented
Rebased.

2016-11-02 21:28 UTC, geoffthemedio commented on GG/GG/Edit.h
> +    std::vector<GG::Font::LineData>::size_type LastLineIndexOrZero() const;
Could be called NumLines() perhaps?

2016-11-02 21:34 UTC, geoffthemedio requested changes

2016-11-02 21:34 UTC, geoffthemedio commented on GG/src/Edit.cpp
> +/** Return the index of the last LineData() or 0 if LineData is empty.
don't need to repeat the comment before the implementation...

2016-11-02 21:34 UTC, geoffthemedio commented on GG/src/MultiEdit.cpp
> +
remove blank line at start

2016-11-03 19:47 UTC, LGM-Doyle commented on GG/GG/Edit.h
> +    std::vector<GG::Font::LineData>::size_type LastLineIndexOrZero() const;
Certainly, `NumLines()` is the more obvious name.

2016-11-03 19:47 UTC, LGM-Doyle commented
The requested changes have been made.  The next PR in the series is #989,

2016-11-03 21:37 UTC, merged