Update in-code documentation for util/Version.h and related cpp files
freeorion/freeorion pull request #1047
Opened 2016-10-10 10:04 UTC by adrianbroher

Use Doxygen keywords were applicable or required to create proper docs.

Gave it already an aspell check for spelling errors.

2016-10-10 11:51 UTC, geoffthemedio commented
It's just some comments... Did you want some feedback before merging, or is there some other reason to make this a pull request first?

2016-10-10 12:04 UTC, adrianbroher commented
> Did you want some feedback before merging, or is there some other reason to make this a pull request first?

Yes, I'm not sure if the phrasing inside the documentation is proper.

> It's just some comments

If those kind of PRs are not welcome I can also commit to master without PRs.

2016-10-10 12:27 UTC, geoffthemedio commented
You're certainly welcome to request review of any code before committing it to master.

2016-10-10 12:32 UTC, geoffthemedio requested changes

2016-10-10 12:32 UTC, geoffthemedio commented on util/Version.cpp.in
> + *      used by all build systems.
might say "is or should be used by all..."

2016-10-10 12:32 UTC, geoffthemedio commented on util/Version.h
> + * @brief  Declares free functions to access the application and dependencies
"dependency versions" or "dependencies' versions". I'd prefer the former.

2016-10-10 12:32 UTC, geoffthemedio commented on util/Version.h
> + *      <em>VERSION BRANCH_NAME [build DATE.SHORT_COMMIT_HASH] BUILD_SYSTEM</em>
might want to give an example of what "VERSION" would look like...
might want to clarify that it's a git commit hash.
might want to give example(s) of what BUILD_SYSTEM would look like
or, could just give an example of a full version string.

2016-10-10 12:32 UTC, geoffthemedio commented on util/Version.h
> + * @bug  The current implementation doesn't expose all dependencies of all
Is it really a bug? Depends if a "limitation" is a bug... Or could say it just returns the dependency versions for common code.

2016-10-10 12:32 UTC, geoffthemedio commented on util/Version.h
> + * @bug  The @e debug log channel isn't the right place to log this but we don't
arguably unnecessary editorializing in this context...

2016-10-10 12:46 UTC, adrianbroher commented on util/Version.h
> + * @bug  The current implementation doesn't expose all dependencies of all
I would consider it a bug, given the current indirect usage of this function by HumanClientApp::HumanClientApp() and ServerApp::ServerApp() and the in-code comment written by you regarding Vorbis and Ogg.

2016-10-10 12:48 UTC, adrianbroher commented on util/Version.h
> + * @bug  The @e debug log channel isn't the right place to log this but we don't
Well, okay.  I can remove the bug note but I think the statement in itself holds merit.

2016-10-10 12:56 UTC, geoffthemedio commented on util/Version.h
> + * @bug  The @e debug log channel isn't the right place to log this but we don't
It is a reasonable use case for an info channel.

2016-10-10 12:59 UTC, geoffthemedio commented on util/Version.h
> + * @bug  The current implementation doesn't expose all dependencies of all
I suppose you could rename this to CommonDependencyVersions and have client/server-specific equivalents as well.

2016-10-10 21:10 UTC, adrianbroher commented
Updated comments as requested.

Split up the implementation of DependencyVersions to each executable dependencies.
@Vezzra the Xcode project needs to be updated.  `util/DependencyVersions.cpp` needs to removed from the common project and added to freeorion, freeorionca and freeoriond.client/human/HumanClientApp.cpp

Also added and `info` and `warn` channel and changedthe dependency version logging from the `debug` to the `info` channel.

2016-10-12 00:22 UTC, Vezzra commented
Ok, updated the Xcode project.

However, I can't build this branch, getting the following compile errors (with and without the changes to the Xcode project):
```
/Users/user/SoftwareProjekte/FO/src/util/DependencyVersions.cpp:51:30: error: use of undeclared identifier 'vorbis_version_string'; did you mean 'VorbisVersionString'?
        const char* retval = vorbis_version_string();
                             ^~~~~~~~~~~~~~~~~~~~~
                             VorbisVersionString
/Users/user/SoftwareProjekte/FO/src/util/DependencyVersions.cpp:50:17: note: 'VorbisVersionString' declared here
    std::string VorbisVersionString() {
                ^
/Users/user/SoftwareProjekte/FO/src/util/DependencyVersions.cpp:51:21: error: no viable conversion from 'std::string' (aka 'basic_string<char>') to 'const char *'
        const char* retval = vorbis_version_string();
                    ^        ~~~~~~~~~~~~~~~~~~~~~~~
```

2016-10-20 11:35 UTC, geoffthemedio approved these changes

2016-10-20 13:25 UTC, adrianbroher commented
> However, I can't build this branch

I included the vorbis header with quotes instead of angle brackets.

2016-10-20 13:26 UTC, merged

2016-10-20 19:31 UTC, geoffthemedio commented
I'm still getting compile errors from the #include <zlib.h> line for all three projects (human, ai, server)

2016-10-20 20:57 UTC, geoffthemedio commented
Same issue with #   include <png.h>

2016-10-21 09:21 UTC, geoffthemedio commented
And ft2build.h

2016-10-21 11:10 UTC, geoffthemedio commented
And after adding the freetype directory to the FreeOrion project, I get a link error:
````
2>Link:
2>     Creating library ../../FreeOrion.lib and object ../../FreeOrion.exp
2>DependencyVersions.obj : error LNK2001: unresolved external symbol _vorbis_version_string
````