Consistently rendered popup menus
freeorion/freeorion pull request #1054
Opened 2016-10-14 02:45 UTC by dbenage-cx

Adds CUIPopupMenu providing a default consistent font and color options of GG::PopupMenu.

Fixes #772

2016-10-14 05:48 UTC, LGM-Doyle commented
I've tried this out and it works for me.  Popups pop.

2016-10-14 08:18 UTC, geoffthemedio requested changes

2016-10-14 08:18 UTC, geoffthemedio commented on UI/CUIControls.cpp
> +        GG::PopupMenu(x, y, ClientUI::GetFont(), menu, ClientUI::TextColor(), ClientUI::WndOuterBorderColor(),
indent by 4, not 8, spaces

2016-10-15 18:15 UTC, merged

2016-10-16 21:33 UTC, dbenage-cx commented
TY for review/testing