Use waiting cursor during long processing states
freeorion/freeorion pull request #1060
Opened 2016-10-18 03:49 UTC by dbenage-cx

Adds functionality to change the cursor to a waiting icon.
Uses this cursor during
* WaitingForTurnStart
* WaitingForTurnData
* between PlayingTurn SaveGameDataRequest and SaveGameComplete messages.

Functionality is designed to not clear a waiting cursor until all requests for that cursor are resolved.
`ResetCursorToDefault()` is provided for cases of an immediate need for the default cursor.

Related #971

2016-10-18 07:44 UTC, geoffthemedio requested changes

2016-10-18 07:44 UTC, geoffthemedio commented on client/human/HumanClientApp.cpp
> +    m_wait_flags[reason]++;
is this thread safe?
if any networking events can cause this to be called, it might need to be...

2016-10-18 07:44 UTC, geoffthemedio commented on client/human/HumanClientApp.cpp
> +void HumanClientApp::ClearWaitingFlag(std::string reason) {
why not const std::string&

2016-10-18 07:44 UTC, geoffthemedio commented on client/human/HumanClientApp.h
> +    void                AddWaitingFlag(std::string reason);         ///< Ensure the wait cursor is used until \p reason is cleared
...

2016-10-19 00:17 UTC, dbenage-cx commented on client/human/HumanClientApp.cpp
> +    m_wait_flags[reason]++;
@geoffthemedio Good point.
I am guessing that adding functionality to GG instead and using signal/slots would be preferred (and provide a better avenue for other cursor changes).
I will look into making such a change unless another avenue is suggested, I need to study up on GG::GUIImpl/atomic/SDL to determine how to approach.
Will close this PR as invalid and open as issue if that sounds like the correct course.

2016-10-19 13:04 UTC, closed without merging

2016-10-19 16:48 UTC, Vezzra commented
@dbenage-cx, do you intend to come up with another PR with a different implementation that fixes the issues raised, or did you drop the idea entirely? In case of the former, the status needs to be changed to "follow up".

2016-10-19 22:59 UTC, dbenage-cx commented
@Vezzra I forgot to open an issue earlier, I will do so shortly.
While I am actively researching this, it may take me some time to start a new implementation.  If someone else has an interest in tackling it, I would not want to impede them from doing so.

I assume this would remain `invalid` in this case, since there is no current PR to link to (or should I link to an issue? I will hold off linking from one to the other for now).

2016-10-20 06:11 UTC, Vezzra commented
> I assume this would remain invalid in this case, since there is no current PR to link to

After re-reading the description for the "follow up" status label I have to agree - when applying that label, a reference to the follow-up PR should be provided, so as long as there is no follow-up PR, this propbably should be labelled invalid.

Just don't forget to set the status label to "follow up" once the new PR is up.

2016-10-20 07:53 UTC, adrianbroher commented
A new implementation addressing the wait cursor will be handled in #1062.

> After re-reading the description for the "follow up" status label I have to agree.

That's another corner case. The follow up shouldn't be bound to to a PR. I will change the description accordingly.