Update en.txt
freeorion/freeorion pull request #1065
Opened 2016-10-21 03:34 UTC by ericfurman

Add a line at 4356. Describes how to build multiple ships in Production queue.

2016-10-21 08:40 UTC, geoffthemedio requested changes

2016-10-21 08:40 UTC, geoffthemedio commented on default/stringtables/en.txt
> +When ships are added to the queue they have two drop down menus that enable you to build the same ship multiple times. The first is to build that ship the specified number of times. So if 5 is select
I can't find the discussion, but recently something like this was proposed for addition to the research article, in which there was discussion about the mechanics of requiring supply connects for refinements to upgrade ship weapon meters. This was vaguely related to research, but not really relevant to an article about research as a resource.

In this case, I'm a bit more conflicted. The article is really about industry as a meter / resource, which is probably OK to extend to discussion about how that resource is allocated on the queue. But getting into details of the interface seems off topic, and should probably be in a separate article about the UI specifically.

2016-10-21 23:08 UTC, dbenage-cx commented
Instead of first/second quantities, it might be good to define some terms here.
Internally, the second quantity is `blocksize`.
That term may bring more questions than answers, personally I think of an element as a batch (or maybe a work order).
So the first quantity might be `batch iterations`, and the second `batch size`.
(I'll refer to the queue element as batch here, substitute as needed if another term is used)
Some things not noted that may lead to user confusion/frustration:
* On completion of a batch, any additional iterations retain the queue position.
* After progress is made on a queue item, decreasing the batch size may result in lost PP.
* After progress, increasing the batch size will recalculate to the items required # of turns.
* The next batch iteration will not start production until the final turn of the current iteration.

That final point may be hard to explain concisely without an explanation.
e.g. Given 120 PP output and a ship needing 300 PP/3 turns (100/turn).
During turns 1-2 the remaining 20PP goes to the next item in the queue.
At the end the third turn, the next iteration receives 20PP (and the first iteration completes), the next item in the queue would not receive any PP.

2016-10-22 00:21 UTC, ericfurman commented on default/stringtables/en.txt
> +When ships are added to the queue they have two drop down menus that enable you to build the same ship multiple times. The first is to build that ship the specified number of times. So if 5 is select
Yes I thought about making this into a separate Pedia article, but this was easier.
It does seem like a good idea. I'll go ahead and start that.

2016-10-22 00:25 UTC, ericfurman commented
ok dbenage-cx, you gave me some info I was unaware of. I think your wording doesn't need much if any modification. only one thing...
While Batch has a well known and defined meaning in the computer world I think Work Order would be more understandable to the average person.

2016-10-30 10:49 UTC, geoffthemedio commented on default/stringtables/en.txt
> +When ships are added to the queue they have two drop down menus that enable you to build the same ship multiple times. The first is to build that ship the specified number of times. So if 5 is select
bump?

2016-10-30 13:04 UTC, Vezzra commented
> I think Work Order would be more understandable to the average person.

Or maybe (more specific) "Build Order"?

2016-10-30 13:23 UTC, geoffthemedio commented
Prefer "production" over "build", please.

2016-10-30 13:47 UTC, Vezzra commented
"Production Order", sure, even better 👍

2017-01-17 17:17 UTC, dbenage-cx commented
@ericfurman any update?

2017-01-20 13:10 UTC, Vezzra commented
Also rebase needed.

2017-02-12 15:26 UTC, Vezzra commented
There has been no more feedback from @ericfurman since last October. What shall we do with this PR?

2017-02-21 09:11 UTC, dbenage-cx commented
Closing for followup

2017-02-21 09:11 UTC, closed without merging

2017-02-22 10:32 UTC, Vezzra commented
Superceded by #1354.