Fix combat log accordion bad initial reflow.
freeorion/freeorion pull request #1083
Opened 2016-10-30 21:38 UTC by LGM-Doyle

PR #1076 re-exposed the problem with the initial text reflow of the combat accordion window title.

I have used the same workaround as before #1076 added `DeferredLayout`, but moved it into the `PreRender()` function.  

If I find a proper fix, while fixing the other combat log problems with fighters I will replace this code, but this PR is an improvement on #1076.

2016-10-30 21:41 UTC, geoffthemedio requested changes

2016-10-30 21:41 UTC, geoffthemedio commented on UI/CombatReport/CombatLogWnd.cpp
> +{
{ to prev line

2016-10-31 21:05 UTC, LGM-Doyle commented on UI/CombatReport/CombatLogWnd.cpp
> +{
Fixed.

2016-10-31 21:49 UTC, geoffthemedio approved these changes

2016-10-31 21:51 UTC, merged