Autoselection of ships for bombard
freeorion/freeorion pull request #1087
Opened 2016-11-05 14:59 UTC by dbenage-cx

Addresses automatic selection of ships, utilizing content tags as an additional selection criteria.
Adds population reduction amounts as the capacity of bombard parts for UI display and potential AI use.

This PR does not enable bombarding to continue until canceled, as I was unable to resolve the cancel button not functioning (`Planet::IsAboutToBeBombarded` is true, despite my attempts).

Related to #672,

2016-11-05 16:23 UTC, dbenage-cx commented
Posting this PR was premature as I believe changes may be required here to fix the issues, marking as work in progress.

2016-11-07 13:25 UTC, geoffthemedio commented on UI/SidePanel.cpp
> +            (ship->OwnedBy(empire_id) &&
why the weird staircase nesting?

2016-11-08 04:40 UTC, dbenage-cx commented on UI/SidePanel.cpp
> +            (ship->OwnedBy(empire_id) &&
Admittedly pointless change, removed.

2016-11-08 08:46 UTC, geoffthemedio requested changes

2016-11-08 08:46 UTC, geoffthemedio commented on UI/SidePanel.cpp
> +std::set<TemporaryPtr<const Ship> > AutomaticallyChosenBombardShips(int target_planet_id) {
Document criteria for selecting ships?

2016-11-09 00:29 UTC, dbenage-cx commented on UI/SidePanel.cpp
> +std::set<TemporaryPtr<const Ship> > AutomaticallyChosenBombardShips(int target_planet_id) {
Rebased with doc additions

2016-11-10 10:10 UTC, geoffthemedio commented on UI/SidePanel.cpp
> +    /** Parse content tags for a Ship, returning tags that potentially match with those of a Planet.
wouldn't call this parsing...

2016-11-10 10:11 UTC, geoffthemedio commented on UI/SidePanel.cpp
> +/** Returns valid Ship%s capable of bombarding a given planet.
|Ship%s| ?

2016-11-10 17:52 UTC, dbenage-cx commented on UI/SidePanel.cpp
> +/** Returns valid Ship%s capable of bombarding a given planet.
Allows doxygen to link the `Ship` class here, with the appended `s`.
e.g. XMLElement::WriteElement
[code](https://github.com/freeorion/freeorion/blob/master/util/XMLDoc.h#L329)
[doc](http://freeorion.github.io/cppapi/master/classXMLElement.html#a486644805342c20a02163443d35c553a)

2016-11-11 09:11 UTC, geoffthemedio approved these changes

2016-11-11 09:46 UTC, geoffthemedio commented on UI/SidePanel.cpp
> +            } else if ((tag_it->length() > TAG_BOMBARD_PREFIX.length()) &&
probably OK, but could have used boost::starts_with
http://stackoverflow.com/questions/1878001/how-do-i-check-if-a-c-string-starts-with-a-certain-string-and-convert-a-sub

2016-11-11 09:47 UTC, merged