Fix bug1086 resizing side panel causes crash
freeorion/freeorion pull request #1088
Opened 2016-11-06 09:36 UTC by LGM-Doyle

This PR fixes issue #1086, by preventing the stack overflow.

This section is copied from the third commit.

```Several infinitely recursive loops passing through
SidePanel::PlanetPanelContainer::DoPanelsLayout() were possible.

In one PlanetPanelContainer::DoPanelsLayout() would call
PlanetPanel::DoLayout(), which would signal ResizedSignal(), which would
call DoPanelsLayout() in an infinite loop.

A second loop passed through AccordionPanel::SetCollapsed(), which even
when the collapsed state was unchanged still signaled with the
ExpandCollapseSignal().
```

The third commit is possibly the only commit necessary to stop SidePanel having a stack overflow.

The second commit prevents AccordionPanel from doing unnecessary work and potentially causing other unnecessary work.

The first commit is required since currently SidePanel expects the unnecessary signal from AccordionPanel before it correctly sizes the focus drop down icons.

2016-11-06 10:31 UTC, Vezzra requested changes

2016-11-06 10:31 UTC, Vezzra commented on UI/SidePanel.cpp
> +    bool                        m_ignore_recurisve_resize;
Typo: recurisve => recursive

2016-11-06 18:34 UTC, geoffthemedio commented
otherwise ok

2016-11-07 09:55 UTC, LGM-Doyle commented
I've fixed the spelling error.

2016-11-07 10:01 UTC, Vezzra approved these changes

2016-11-07 10:04 UTC, merged

2016-11-07 10:29 UTC, LGM-Doyle commented
Thanks for the review.