Fix drop down list key scrolling
freeorion/freeorion pull request #1133
Opened 2016-11-25 22:23 UTC by LGM-Doyle

The PR fixes and enhances the drop down list key handling.

The bugs described are evident in long drop down lists like the `SystemName` list in the `SidePanel`.

The PR:
- makes sure that the drop down list tracks the selected item.
- changes to pageup/pagedown stride from 10 to (drop down list size - 1) which is a page.
- fixes some fence post errors in `ListBox::BringIntoView()`

2016-11-26 08:44 UTC, geoffthemedio requested changes

2016-11-26 08:44 UTC, geoffthemedio commented on GG/src/DropDownList.cpp
> +        if (LB()->NumRows()) {
!LB()->Empty() seems clearer...

2016-11-26 08:44 UTC, geoffthemedio commented on GG/src/DropDownList.cpp
> +        if (LB()->NumRows() && !LB()->Empty()) {
LB()->NumRows() seems redundant here?

2016-11-26 14:23 UTC, LGM-Doyle commented
Fixed throughout.

2016-11-27 08:25 UTC, geoffthemedio approved these changes

2016-11-28 17:19 UTC, geoffthemedio commented
Page Down seems to work like End for me.
Numpad buttons should also be supported.

2016-11-29 18:08 UTC, LGM-Doyle commented
Initial selection was not working and is now fixed.
The numpad keys have been added.
Page down seemed to be working for me before.  I haven't changed anything and I'm hoping that you were testing the wrong branch.

2016-11-29 18:36 UTC, geoffthemedio commented
````
1>..\..\GG\src\DropDownList.cpp(291): error C2784: '_Ty std::max(std::initializer_list<_Elem>,_Pr)' : could not deduce template argument for 'std::initializer_list<_Elem>' from 'unsigned long'
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4108) : see declaration of 'std::max'
1>..\..\GG\src\DropDownList.cpp(291): error C2780: 'const _Ty &std::max(const _Ty &,const _Ty &,_Pr)' : expects 3 arguments - 2 provided
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4101) : see declaration of 'std::max'
1>..\..\GG\src\DropDownList.cpp(291): error C2780: '_Ty std::max(std::initializer_list<_Elem>)' : expects 1 arguments - 2 provided
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4092) : see declaration of 'std::max'
1>..\..\GG\src\DropDownList.cpp(291): error C2782: 'const _Ty &std::max(const _Ty &,const _Ty &)' : template parameter '_Ty' is ambiguous
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4086) : see declaration of 'std::max'
1>          could be 'size_t'
1>          or       'unsigned long'
1>..\..\GG\src\DropDownList.cpp(303): error C2784: '_Ty std::max(std::initializer_list<_Elem>,_Pr)' : could not deduce template argument for 'std::initializer_list<_Elem>' from 'unsigned long'
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4108) : see declaration of 'std::max'
1>..\..\GG\src\DropDownList.cpp(303): error C2780: 'const _Ty &std::max(const _Ty &,const _Ty &,_Pr)' : expects 3 arguments - 2 provided
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4101) : see declaration of 'std::max'
1>..\..\GG\src\DropDownList.cpp(303): error C2780: '_Ty std::max(std::initializer_list<_Elem>)' : expects 1 arguments - 2 provided
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4092) : see declaration of 'std::max'
1>..\..\GG\src\DropDownList.cpp(303): error C2782: 'const _Ty &std::max(const _Ty &,const _Ty &)' : template parameter '_Ty' is ambiguous
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4086) : see declaration of 'std::max'
1>          could be 'size_t'
1>          or       'unsigned long'
````

2016-11-29 18:42 UTC, geoffthemedio commented
The droplists seem to need a bit more padding at the bottom, as part of the bottom row is cut off (particularly noticeable for text with dangling bits like a q).
The system droplist also needs a border to better distinguish it from the planet panel behind it. The focus drop has a suitable border outline.
![borders](https://cloud.githubusercontent.com/assets/11386908/20723742/034a0a84-b66c-11e6-88a7-6a7fd37bf571.png)

2016-11-29 20:21 UTC, geoffthemedio commented
needs rebase

2016-11-29 21:53 UTC, geoffthemedio commented
still says this branch has conflicts...

2016-11-29 22:03 UTC, LGM-Doyle commented
It had a conflict with #1143, which you just merged.  It is rebased now.

This includes the centering on the selected item when the drop down list opens.

2016-11-30 01:49 UTC, merged