Add ListBox::Show() to only show rows within the visible box.
freeorion/freeorion pull request #1134
Opened 2016-11-25 22:23 UTC by LGM-Doyle

This PR further speeds up and cleans up the SidePanel SystemName drop down list.

It adds `ListBox::Show(bool children)`, which unlike the default `Show()` does not show all of its children.  It only shows those rows which would be visible if the list rendered.  This means that the `PreRender()` of rows that would not be in the drop down are not called.  It still calls all of the `PreRender()` functions of the invisible items in the dropped portion of the list even when it is not dropped, so it is not optimal.

This speeds up re-generation of the SidePanel even when the SystemName is not expanded.  From profiling on a 1000 system map this improves the re-load of the SystemName caused by the Super-Testers revealing all of the systems from 400ms to 1.8ms.  In a regular game this cost is paid every time the SidePanel updates the SystemName contributing to late game sluggishness.

Making this change exposed a bug where `ListBox::Row::operator[]` creates dangling null Control* pointers, which causes problems (i.e. crashing), so that operator is removed in this PR.

2016-11-26 10:11 UTC, geoffthemedio requested changes

2016-11-26 10:11 UTC, geoffthemedio commented on UI/DesignWnd.cpp
> +                    ShipDesignPanel* design_panel = dynamic_cast<ShipDesignPanel*>(
I'd have put the ? outside rather than inside the dynamic_cast call...

2016-11-26 10:11 UTC, geoffthemedio commented on UI/MultiplayerLobbyWnd.cpp
> +            if (size() >=5)
space after >= before 5

2016-11-26 10:11 UTC, geoffthemedio commented on UI/TechTreeWnd.cpp
> +    if (GG::TextControl* tc = dynamic_cast<GG::TextControl*>(!empty() ? at(2) : 0))
why not check size() >= 3 instead of !empty if you're indexing at 2?

2016-11-26 15:54 UTC, geoffthemedio approved these changes

2016-11-26 18:59 UTC, LGM-Doyle commented
Do you want me to merge this?

2016-11-27 08:30 UTC, geoffthemedio commented
At least to me, approving changes means I approved those changes in response to the requested changes, not that I've decided to merge, which I would have done myself.

2016-11-27 21:09 UTC, LGM-Doyle commented
I was unsure if you were changing the procedure.  Thanks for clarifying.

2016-11-30 09:02 UTC, geoffthemedio commented
rebase?

2016-11-30 19:12 UTC, LGM-Doyle commented
Rebased.

2016-11-30 20:46 UTC, merged