Fix drop down list doesn't track anchor on app resize.
freeorion/freeorion pull request #1143
Opened 2016-11-27 20:56 UTC by LGM-Doyle

The drop down list and its anchor are in different event pumps.  If the
entire app is resized the drop down list may not track the anchor.

This commit closes the drop down list if the app is resized.

This PR fixes #1139.

2016-11-28 08:47 UTC, geoffthemedio commented on GG/src/DropDownList.cpp
> +    if (m_initial_appsize != Pt(GG::GUI::GetGUI()->AppWidth(), GG::GUI::GetGUI()->AppHeight()))
Is this preferable to connecting HumanClientApp::WindowResizedSignal to EndRun ?

2016-11-29 18:08 UTC, LGM-Doyle commented
No it was not preferable.  It is now fixed.

Thanks.

2016-11-29 18:49 UTC, geoffthemedio requested changes

2016-11-29 18:49 UTC, geoffthemedio commented on GG/src/DropDownList.cpp
> +                                     boost::bind(&ModalListPicker::WindowResizedSlot, this, _1, _2));
odd indenting

2016-11-29 21:53 UTC, geoffthemedio approved these changes

2016-11-29 21:54 UTC, merged