Improve fleet tooltip for fighters
freeorion/freeorion pull request #1179
Opened 2016-12-18 01:46 UTC by dbenage-cx

Provides two tooltip modes for a ships fighter icon in fleet window.
The first tooltip displays after the normal delay, with a summary view.
The second replaces the first after a longer delay, with a more detailed accounting.

[Forum discussion](http://www.freeorion.org/forum/posting.php?f=6&t=10342)

2016-12-18 07:45 UTC, geoffthemedio requested changes
a few more comments before various code blocks would also be nice.

2016-12-18 07:45 UTC, geoffthemedio commented on UI/MeterBrowseWnd.cpp
> +                                                                    fighter_damage, 2);
indenting

2016-12-18 07:45 UTC, geoffthemedio commented on UI/MeterBrowseWnd.cpp
> +        // add a label for each hangar part, distributing the total fighters equally
could instead have "hangar_part x 6" and just the sum of fighters in that hangar part type...

2016-12-18 07:45 UTC, geoffthemedio commented on UI/MeterBrowseWnd.cpp
> +            DebugLogger() << "Display of number of fighters mismatched.  Current: "
Should the be ErrorLogger() ?

2016-12-18 07:45 UTC, geoffthemedio commented on UI/MeterBrowseWnd.cpp
> +            % ColourWrappedtext(DoubleToString(total_dmg / NUM_COMBAT_BOUTS, 3, false), DAMAGE_COLOR));
indenting in this case is inconsistent throughout these additions. should perhaps be consistent with indendenting 4 speces or to the same position as FlexibleFormat

2016-12-18 07:45 UTC, geoffthemedio commented on UI/MeterBrowseWnd.h
> +    static const int NUM_COMBAT_BOUTS = 3;
as discussed on forum thread, don't duplicate this definition here...

2016-12-18 10:47 UTC, Vezzra commented
The link to the forum discussion is somehow broken... when clicking it, I get a forum information message "No post mode specified".

2016-12-18 21:31 UTC, geoffthemedio commented
Builds and seems to work on Windows. Default long tooltip time (5 s) is too long, though.

2016-12-19 21:58 UTC, dbenage-cx commented on UI/MeterBrowseWnd.cpp
> +                                                                    fighter_damage, 2);
Fixed

2016-12-19 21:58 UTC, dbenage-cx commented on UI/MeterBrowseWnd.cpp
> +        // add a label for each hangar part, distributing the total fighters equally
Fixed, made bays consistent with this change

2016-12-19 21:58 UTC, dbenage-cx commented on UI/MeterBrowseWnd.cpp
> +            % ColourWrappedtext(DoubleToString(total_dmg / NUM_COMBAT_BOUTS, 3, false), DAMAGE_COLOR));
Fixed

2016-12-19 22:01 UTC, dbenage-cx commented on UI/MeterBrowseWnd.h
> +    static const int NUM_COMBAT_BOUTS = 3;
Pending resolution of PR #1181

2016-12-20 21:32 UTC, dbenage-cx commented
Rebased

2016-12-21 18:53 UTC, geoffthemedio commented on UI/MeterBrowseWnd.cpp
> +                GG::ListBox::Row(FighterBrowseListWidth(), MeterBrowseRowHeight(), "")
indent step is 4 not 8 spaces

2016-12-22 03:07 UTC, dbenage-cx commented on UI/MeterBrowseWnd.cpp
> +                GG::ListBox::Row(FighterBrowseListWidth(), MeterBrowseRowHeight(), "")
TY, fixed.

2016-12-22 06:36 UTC, geoffthemedio approved these changes

2016-12-24 10:26 UTC, geoffthemedio commented
![fighter_tooltip_annotated](https://cloud.githubusercontent.com/assets/11386908/21466422/a7392356-c9cb-11e6-9f28-fab856e64b8d.png)

A couple quirks...

How are there 4 fighters able to shoot in round 2 if there are just 3 launch bays, and why is the number of fighters the same in both rounds?

The layout for listing / counting the launch bays is odd.

2016-12-24 12:14 UTC, MatGB commented
Launch bays can each launch 2 fighters, so 3 can launch up to 6 in one turn, that all looks fine to me. 

I expect at some point to have bigger or better launch bays but for now haven't touched your numbers.

2016-12-25 16:00 UTC, dbenage-cx commented
Substantial change to address layout and style, and provide more info on a round.

![fighter_tt8](https://cloud.githubusercontent.com/assets/17205519/21471913/7a9eb014-ca88-11e6-859c-0e6ef83b4cfb.png)

2016-12-26 12:35 UTC, Vezzra commented
Looks ok to me... as far as I am concerned, I guess this can be merged. To get a feeling how useful that really is more extensive playtesting will be required anyway.

2016-12-26 19:09 UTC, merged

2016-12-26 20:11 UTC, dbenage-cx commented
@geoffthemedio Thank you for reviews