Ai tweaks for sparse galaxy
freeorion/freeorion pull request #1184
Opened 2016-12-21 21:25 UTC by Dilvish-fo

Hi guys, long time no see.  I have a little Christmas contribution that I think could help liven up the holidays-- some relatively modest AI tweaks that nonetheless seem to make it a fair bit more competitive, especially in the specific setups this is directed to, which are ones where the monster density is no greater than Low, and where there are at least 40 systems per empire (or 35 if the shape is elliptical).   I prefer to run this at 400 systems and 6 AIs.  

Also, independent of the sparsity, this enables the AI to use the XenoResurrection Lab and the associated extinct species.

I am still getting up to speed on some of the AI changes during my absence, so CJ et al., just let me know if you'd prefer I change the way I tweaked the techs here.

2016-12-21 22:21 UTC, Cjkjvfnby commented
I have exams soon, after that new year + vacation and more exams after.  I am useless until that.  :(

2016-12-22 00:11 UTC, Morlic-fo requested changes
What a nice christmas surprise! Happy to see you again!

2016-12-22 00:11 UTC, Morlic-fo commented on default/python/AI/ColonisationAI.py
> +                empire_colonizers["SP_"+spec_name] = []  # get it into colonizer list even if no colony yet
Whitespace around operators.

2017-01-03 02:17 UTC, MatGB commented
I've played two games through with this now and, for the first time in over a year, one of them had to be restarted as the AI overpowered me in the early game: partially due to my own mistakes and partially because it was doing things I wasn't expecting.

I especially like the greater emphasis on detection techs in this, even if it did mess up some of my strategies, but it also made me try out a few new ideas in a way that was fun.

Overall I like the way it feels/plays.

2017-01-14 20:35 UTC, Morlic-fo commented
Ok that did not work out as intended. Tried resolving the conflicts using the web interface. Turns out that creates a merge commit.

2017-01-15 18:52 UTC, Vezzra commented
> Ok that did not work out as intended. Tried resolving the conflicts using the web interface. Turns out that creates a merge commit.

@Morlic-fo, hopefully fixed. 😃

2017-02-09 18:36 UTC, Dilvish-fo commented
Morlic, thanks much for your feedback.  I've made the corrections and fixed the conflict with current master, and was trying to do a bit of testing to confirm things are working OK before pushing the revised branch.   My testing is a little bit slowed down, though, since I can't find any AI logs anymore, nor has my initial perusal shown me where/why they've been dropped or how I can reinstate them.  Any suggestions for me on that front?

2017-02-09 23:52 UTC, dbenage-cx commented
@Dilvish-fo try `~/.local/share/freeorion` for logs (if not, check config file for location of `save-dir`, should be the parent of)

2017-02-12 16:19 UTC, Vezzra commented
@Dilvish-fo, do you think you can get this finalized in time for the release?

2017-02-13 00:02 UTC, closed without merging

2017-02-14 21:54 UTC, Cjkjvfnby commented
@Dilvish-fo, closing PR by pushing other commit does not looks good for me.   IMHO PR should be closed manually with comment.