Implementation multiplayer readiness.
freeorion/freeorion pull request #1187
Opened 2016-12-28 22:16 UTC by o01eg

- Add the field to the game protocol and lobby UI.
- Drop it if the important game's or players' changes were happened.
- When all human players are ready the game starts without requiring host player to press "start" button.

2016-12-30 10:52 UTC, adrianbroher requested changes
When using `UserString` or relatives you either wrap a string literal or a local variable.  If you can't use a string literal at the place where the translation occurs use `UserStringNop` to wrap the string literal to be translated.

2016-12-30 10:52 UTC, adrianbroher commented on UI/MultiplayerLobbyWnd.cpp
> +                push_back(new CUILabel(UserString(player_data.m_player_ready ? "YES" : "NO")));
Only use string literals or variables as `UserString` parameter.

2016-12-30 10:52 UTC, adrianbroher commented on UI/MultiplayerLobbyWnd.cpp
> +                push_back(new CUILabel(UserString(player_data.m_player_ready ? "YES" : "NO")));
Only use string literals or variables as `UserString` parameter.

2016-12-30 10:52 UTC, adrianbroher commented on UI/MultiplayerLobbyWnd.cpp
> +                push_back(new CUILabel(UserString(player_data.m_player_ready ? "YES" : "NO")));
Only use string literals or variables as `UserString` parameter.

2016-12-30 12:03 UTC, o01eg commented
Fixed.

2016-12-30 12:04 UTC, adrianbroher approved these changes

2016-12-30 12:05 UTC, adrianbroher commented
The review only covered the incorrect usage of UserString.  No further inspection was done.

2017-01-05 06:53 UTC, dbenage-cx requested changes

2017-01-05 06:53 UTC, dbenage-cx commented on UI/MultiplayerLobbyWnd.cpp
> +    } else if (m_ready_bn && (key == GG::GGK_RETURN || key == GG::GGK_KP_ENTER))
Bring opening brace up to this line
`} else if () {`

2017-01-05 06:53 UTC, dbenage-cx commented on UI/MultiplayerLobbyWnd.cpp
>                                     ClientHeight() - m_cancel_bn->Height() - CONTROL_MARGIN));
Align with start of parameter list (or indented one level for long lines)
`ClientHeight` should align with `m_cancel_bn` in this case

2017-01-05 06:53 UTC, dbenage-cx commented on UI/MultiplayerLobbyWnd.cpp
> +        }
Multi-line should start brace non-indented on next line.
```
else if (b ||
    (c && d))
{ x; }

2017-01-05 06:53 UTC, dbenage-cx commented on server/ServerFSM.cpp
> +            if (it->second.m_player_ready) { ss << ", Ready"; }
body to next line (can drop braces)
```
if (a)
    x;

2017-01-05 06:53 UTC, dbenage-cx commented on server/ServerFSM.cpp
> +    bool is_drop_ready = false;
`is_drop_ready` is unclear in this context, prefer (e.g.) `galaxy_setup_data_changed` or `lobby_data_changed`

2017-01-05 06:53 UTC, dbenage-cx commented on server/ServerFSM.cpp
> +                player.second.m_client_type == Networking::CLIENT_TYPE_HUMAN_PLAYER)) {
multi-line brace to next line

2017-01-05 06:56 UTC, dbenage-cx commented
Still needs adjustment for (at least) label layout.
Something is off as every time I nudge the position a little, the labels end up far offset.  Will try to spend some time looking into it this week if noone jumps in before.

2017-01-05 21:32 UTC, o01eg commented
I've fixed code style and some bugs.

2017-01-06 06:17 UTC, dbenage-cx approved these changes

2017-01-06 13:31 UTC, Vezzra commented
Has anyone (besides @o01eg) actually ran some tests if the PR works as intended?

If yes, and given that we have approved code reviews, LGTM I guess...?

2017-01-06 14:06 UTC, dbenage-cx commented
@Vezzra still needs UI work and then thorough testing

2017-01-06 14:12 UTC, Vezzra commented
Ok.

2017-01-08 16:19 UTC, o01eg commented
I've add commits from dbenage-cx with reworked UI that looks more better.

2017-01-08 18:21 UTC, geoffthemedio requested changes

2017-01-08 18:21 UTC, geoffthemedio commented on UI/MultiplayerLobbyWnd.cpp
> +            return GG::GetTextureManager().GetTexture(ClientUI::ArtDir() / "icons/ready.png");
GG::GetTextureManager seems to not be publically accessible to my linker. Replace this with standard in FreeOrion UI code:
````
ClientUI::GetTexture(...)
````

2017-01-08 18:37 UTC, geoffthemedio commented
Column headers look nice, though I'd rather other similar lists looked the same elsehwere in the UI.

New icon based indicators are good; was going to request something similar.

It looks like I should be getting tooltips / browse windows for something, thought I don't see any in-game...

2017-01-08 18:37 UTC, dbenage-cx commented on UI/MultiplayerLobbyWnd.cpp
> +            return GG::GetTextureManager().GetTexture(ClientUI::ArtDir() / "icons/ready.png");
Fixed (via web interface)

2017-01-08 18:43 UTC, dbenage-cx commented
I may have missed something with tooltips, but I suspect `Row` is simply not passing the pointer through.
Will continue to investigate after other work.

2017-01-10 21:19 UTC, dbenage-cx commented
4cf9661Fixes tooltip display
2b0a27f Shifts the status to first column (if desired, no big issue with using the last column)

2017-01-11 08:13 UTC, geoffthemedio commented
Why leftmost and not rightmost column?

2017-01-11 11:15 UTC, o01eg commented
I can remove last commit if it not neeeded.

2017-01-11 12:21 UTC, geoffthemedio commented
last column seemed fine to me.

2017-01-11 12:53 UTC, o01eg commented
Ok.

2017-01-11 18:32 UTC, geoffthemedio commented
I find the current button labels or design unclear. It's not obvious whether clicking a button that says "Ready" would indicate that you are ready, or that it would toggle back to "Not Ready". The "Start Game" button is better, as it's clearly a verb, so perhaps "Become Ready" or "Declare Ready" or "Accept"... and something similar for the undo buttons?

Also, some indication in the list which player is the host, and can thus edit other players' lobby selections, would be good, as it's no so obvious now due to anyone being able to click ready/not ready.

2017-01-12 21:16 UTC, o01eg commented
I've rebased code and added new column for host but cann't make it appears without scrolling.

2017-01-15 13:49 UTC, geoffthemedio approved these changes

2017-01-15 13:55 UTC, o01eg commented
It's not yet ready due UI issues.

2017-01-15 21:25 UTC, dbenage-cx commented
If a new column is to be added, we need to increase the default width as the controls are too small already.  (Not certain there is much loss wrt who the host is, except in the case of moderators.)

Other options:
*  Add the host icon into the ready state column (requires a change to `MultiTextureStaticGraphic`).
*  Add such an icon behind the player name.
*  Have some indicator (external to this list) which denotes to host, possibly with other info.

2017-01-15 22:07 UTC, dbenage-cx commented on UI/MultiplayerLobbyWnd.cpp
> +        retval.push_back(ready_width); // host
Adjust `prop_width` to account for new fixed width column.

2017-01-16 01:36 UTC, o01eg commented on UI/MultiplayerLobbyWnd.cpp
> +        retval.push_back(ready_width); // host
Thanks, now it looks correctly.

2017-01-16 01:37 UTC, o01eg commented
I've fixed UI.

2017-01-16 09:09 UTC, Vezzra commented
Can the "work in progress" label be removed, that is, is the PR ready for final review and merge? Or is there still some work/adjustments that need to be done?

2017-01-16 09:12 UTC, o01eg commented
No, I think it almost done.

2017-01-16 10:53 UTC, geoffthemedio commented
I'll merge now, though I'd like a tooltip for the host indicator column, and rephrased tooltips for "decline" and "accept", with something like "setup accepted" and "setup not yet accepted"

2017-01-16 10:53 UTC, merged