Fix include path for VS build
freeorion/freeorion pull request #1190
Opened 2016-12-31 12:57 UTC by Voker57

2016-12-31 14:28 UTC, geoffthemedio requested changes

2016-12-31 14:28 UTC, geoffthemedio commented on server/ServerApp.cpp
> +#include <../util/Random.h>
should be with "" and with the other ../util headers

2017-01-01 13:27 UTC, geoffthemedio approved these changes

2017-01-01 13:28 UTC, geoffthemedio commented
What error is this supposed to fix? I don't have any compile issues.

2017-01-01 15:09 UTC, Vezzra commented
Tagged this as bugfix for now, because it says "fix" in the title, but I'm not sure either what exactly this PR is supposed to do. So please correct me if my assumptions are wrong.

2017-01-01 15:55 UTC, Voker57 commented
@geoffthemedio when building with VS 2015, compiler complained about that include not found. The fix resolved the issue.

2017-01-01 20:06 UTC, geoffthemedio commented
I'm not getting any such error with MSVC 2015 (or 2013)

2017-01-02 07:24 UTC, Voker57 commented
Well no idea but it occured to me so I submitted a fix (and it's proper way to include, right?). Not going to rebuild fixless code in my slow VM to recheck.

2017-01-02 16:27 UTC, Vezzra commented
If the change doesn't cause any problems for anyone else (which is highly unlikely considering it's just an added include), and apparently fixes a problem @Voker57 had, I guess we can merge this? It's a *very* simple change after all...

2017-01-02 17:27 UTC, adrianbroher commented
@Vezzra 

No, as adding unnecessary headers always increase compile time.  If this problem is specific to Vokers fork it is his problem.

2017-01-02 19:37 UTC, Voker57 commented
Oh, my apologies. It's indeed related to non-included patch and supposed to correct include line, not add it. I didn't check it after cherry-picking.

2017-01-02 19:37 UTC, closed without merging

2017-01-03 13:00 UTC, Vezzra commented
@adrianbroher, sorry, I thought @Voker57 had the problem when building master, didn't think of the possibility that this might be an issue with his branch.