Add fighter related info to ship design articles
freeorion/freeorion pull request #1192
Opened 2017-01-02 14:12 UTC by dbenage-cx

Suggested by UrshMost in [forum](http://www.freeorion.org/forum/viewtopic.php?f=28&t=10339#p86772).

Adds fighter damage, capacity and launch capacity to pedia article of ship designs.
In lieu of specific info for flak cannons, adds a total number of weapon shots fired (per round).

2017-01-06 04:09 UTC, MatGB commented
I like this, thanks, it makes designing and comparing easier.

How much extra work would it be to add similar auto generated text for the basic hull info entries? Ideally there should be no game info in them that isn't auto generated, so it should list
[code]
Structure:     Shield: 
Speed:     Fuel Capacity: 
Detection Range:     Stealth:  [/code] as well as ideally number of each slot type, that would let us then remove a lot of the badly worded text I put in as a placeholder years ago.

2017-01-06 04:21 UTC, MatGB commented on default/stringtables/en.txt
> +Total [[encyclopedia DAMAGE_TITLE]]: %2%    [[PC_DIRECT_WEAPON]] Shots: %3%
Direct shots doesn't seem to be working properly, possibly counting parts instead of ROF?

2017-01-06 06:17 UTC, dbenage-cx commented
@MatGB Thanks for reviewing, will look into shots fired

For hull type, does not sound overly complicated to accomplish, will put on todo list ;)

2017-01-07 03:48 UTC, dbenage-cx commented on default/stringtables/en.txt
> +[[metertype METER_DETECTION]]: %8%    [[metertype METER_STEALTH]]: %9%
Fixed (and speed/detection too :/ )

2017-01-07 03:48 UTC, dbenage-cx commented on default/stringtables/en.txt
> +Total [[encyclopedia DAMAGE_TITLE]]: %2%    [[PC_DIRECT_WEAPON]] Shots: %3%
Fixed

2017-01-07 07:20 UTC, MatGB commented on default/stringtables/en.txt
> +[[metertype METER_DETECTION]]: %8%    [[metertype METER_STEALTH]]: %9%
Um, not sure it is, I've recompiled from this branch and both are swapped in my display.

2017-01-07 07:42 UTC, dbenage-cx commented on default/stringtables/en.txt
> +[[metertype METER_DETECTION]]: %8%    [[metertype METER_STEALTH]]: %9%
Fetch/Rebase? Both github and local show `[[metertype METER_DETECTION]]: %6%    [[metertype METER_STEALTH]]: %7%`

2017-01-07 08:04 UTC, MatGB commented on default/stringtables/en.txt
> +[[metertype METER_DETECTION]]: %8%    [[metertype METER_STEALTH]]: %9%
Did both before compiling earlier, will do so again in a bit...

Wait, sorry, I've messed up my git repo and created a branch with the same name as your remote branch and it's throwing errors at me, which means my half hour compiling earlier was a complete waste. oops

2017-01-07 09:23 UTC, dbenage-cx commented
- [ ]  TODO Remove `ENC_SHIP_DESIGN_DESCRIPTION_STR` from all stringtables.

2017-01-07 12:19 UTC, MatGB commented
OK, all now appears to compile, run and display correctly, apologies for my error earlier.

2017-01-08 00:44 UTC, dbenage-cx commented
Rebased with changes for non-default stringtable updates

2017-01-10 02:00 UTC, geoffthemedio requested changes

2017-01-10 02:00 UTC, geoffthemedio commented on default/stringtables/en.txt
> +[[OBJ_FIGHTER]] [[encyclopedia DAMAGE_TITLE]]: %13%    [[ENC_SDD_HANGAR]]: %12%    [[ENC_SDD_BAY]]: %14%
This pulls in strings that reference "Current Fighters" which doesn't make sense for a ship design article, which is not about an actual ship that could contain any fighters currently.

2017-01-10 02:00 UTC, geoffthemedio commented on default/stringtables/en.txt
> +Against enemy attack %17$.1f and shields %18$.1f:       %19$.f   (%20$.2f per PP)
The meaning of this "against enemy attack" stat isn't clear.

2017-01-10 02:00 UTC, geoffthemedio commented on universe/Ship.cpp
> +float Ship::CurrentPartClassMeterValue(MeterType type, ShipPartClass part_class) const {
purpose of function not clear from its name

2017-01-10 22:41 UTC, dbenage-cx commented on default/stringtables/en.txt
> +Against enemy attack %17$.1f and shields %18$.1f:       %19$.f   (%20$.2f per PP)
Adding some formatting to help clarify.

2017-01-10 22:41 UTC, dbenage-cx commented on universe/Ship.cpp
> +float Ship::CurrentPartClassMeterValue(MeterType type, ShipPartClass part_class) const {
any suggestions for a name shorter than `SumCurrentPartMeterValuesForPartClass` highly welcome

2017-01-10 22:43 UTC, dbenage-cx commented on default/stringtables/en.txt
> +[[OBJ_FIGHTER]] [[encyclopedia DAMAGE_TITLE]]: %13%    [[ENC_SDD_HANGAR]]: %12%    [[ENC_SDD_BAY]]: %14%
Fixed

2017-01-11 10:29 UTC, geoffthemedio requested changes

2017-01-11 10:29 UTC, geoffthemedio commented on default/stringtables/en.txt
> +After combat, fighters need to return to a hangar for repairs, fuel, and rearmament.
remove "need to"

2017-01-11 10:29 UTC, geoffthemedio commented on default/stringtables/en.txt
> +Since each hangar is built in support of other hangars on the ship, a ship is limited to one specific hangar type.
Don't need the explanation "Since each hangar ... on the ship,". Would rephrase as just "A ship cannot have more than one type of hangar."

2017-01-11 10:29 UTC, geoffthemedio commented on default/stringtables/en.txt
> +Any fighter that is unable to dock at a hangar will likely be lost to the cold realities of space.
Rephrase without flavour text... "If a carrier is destroyed in combat, any of its fighters that survive the battle will be unable to dock after combat, and will also be lost."

2017-01-11 10:29 UTC, geoffthemedio commented on default/stringtables/en.txt
> +Each launch bay allows a certain number of fighters to launch each combat round.
don't need "certain"

2017-01-11 13:44 UTC, dbenage-cx commented on default/stringtables/en.txt
> +Any fighter that is unable to dock at a hangar will likely be lost to the cold realities of space.
Are fighters tied to a specific ship?  I was under impression they docked wherever there was available room.

2017-01-11 14:25 UTC, geoffthemedio commented on default/stringtables/en.txt
> +AIf a carrier is destroyed in combat, any of its fighters that survive the battle will be unable to dock after combat, and will also be lost.
AIf?

2017-01-11 14:26 UTC, geoffthemedio commented on default/stringtables/en.txt
> +Any fighter that is unable to dock at a hangar will likely be lost to the cold realities of space.
iirc they are specific to a particular ship

2017-01-11 16:10 UTC, MatGB commented on default/stringtables/en.txt
> +Any fighter that is unable to dock at a hangar will likely be lost to the cold realities of space.
Yes, we discussed doing otherwise but then you get sticky issues about crew species and other balance problems.

2017-01-11 18:43 UTC, dbenage-cx commented on default/stringtables/en.txt
> +AIf a carrier is destroyed in combat, any of its fighters that survive the battle will be unable to dock after combat, and will also be lost.
Ugly way to destroy a carrier, fixed. (needs squash/fixup)

2017-01-15 13:37 UTC, geoffthemedio approved these changes

2017-01-15 13:41 UTC, geoffthemedio commented
Maybe it's not related to this pull request, but the estimated combat strength values make no sense to me... Starting up a new game, and looking at the article for a random design, I see:
````
Colonization Capacity: 0    Troops: 0
Fighter Damage: 0    Hangar Capacity: 0    Launch Bay Capacity: 0
Estimated combat strength   (ignoring shields):  29   (0.25 per PP)
            (enemy with attack 3.1 and shields 0.0):  285   (2.38 per PP)
````
What does the (enemy with attack...) value mean? Is that just to compare this design to, or is it a rating for this ship against a particular example enemy?

2017-01-15 15:42 UTC, dbenage-cx commented
Some rating against an enemy (clone of self except for particular stats).
Personally, I have mostly ignored these values when playing, so in favor of removing them if they are confusing.

2017-01-15 16:23 UTC, MatGB commented
I can't remember when they were introduced, and I also mostly ignore them, but IIRC it was either @Morlic-fo or @Dilvish-fo that came up with the idea and some people seemed to really like it at the time. Anyone?

I'd say it needs either better explanation or removal but it's been there for ages now in some form.

2017-01-15 16:30 UTC, merged

2017-01-15 16:30 UTC, geoffthemedio commented
if it has nothing to do with this pull request, then ok...

2017-01-15 18:18 UTC, dbenage-cx commented
TY for reviews