Improve combat log differential serialization
freeorion/freeorion pull request #1216
Opened 2017-01-13 20:44 UTC by LGM-Doyle

Currently, every turn update the server sends all combat logs since turn 1 to every player, human and AI.  The AIs never use the combat reports.  

Profiling on my machine showed that the time spent sending the logs was about 0.8 ms per log, per player, per turn.  If the game goes long enough parsing and sending the logs becomes the biggest time component of processing the turn.

This PR changes the implementation so that each turn all players are informed of the number of available combats logs and then only the human clients request any combat logs that they do not already have.  This means that during a game each combat log is only downloaded once per human client.

2017-01-13 21:15 UTC, Morlic-fo commented
> The AIs never use the combat reports.

Yet. 
It would be nice to have the AI parse combat logs to estimate the strength of an enemy but that probably will not come any time soonish, so it probably makes sense not sending them for now...

2017-01-15 13:17 UTC, geoffthemedio requested changes

2017-01-15 13:17 UTC, geoffthemedio commented on client/human/HumanClientApp.cpp
> +
extra blank line

2017-01-15 13:17 UTC, geoffthemedio commented on client/human/HumanClientApp.cpp
> +    boost::optional<std::vector<int> > incompleteIDs(GetCombatLogManager().IncompleteLogIDs());
rename to incomplete_ids

2017-01-15 13:17 UTC, geoffthemedio commented on client/human/HumanClientApp.cpp
> +    boost::optional<std::vector<int> > incompleteIDs(GetCombatLogManager().IncompleteLogIDs());
why does this need to be an optional?

2017-01-15 13:17 UTC, geoffthemedio commented on combat/CombatLogManager.cpp
> +    if (m_incomplete_logs.empty())
what's wrong with returning an empty vector...?

2017-01-15 19:12 UTC, Vezzra commented
> Yet.
It would be nice to have the AI parse combat logs to estimate the strength of an enemy but that probably will not come any time soonish, so it probably makes sense not sending them for now...

Well, if I understand the description correctly, the combat logs (of past turns) are only downloaded once for each game *session* (meaning, after loading a game each client would request all the past combat logs on the first turn update, but not on the subsequent ones).

So even if the AI clients would request those logs too at some point, that's still a big improvement.

2017-01-15 22:00 UTC, LGM-Doyle reviewed
Thanks for taking the time to review this PR.

2017-01-15 22:00 UTC, LGM-Doyle commented on client/human/HumanClientApp.cpp
> +
fixed.

2017-01-15 22:00 UTC, LGM-Doyle commented on client/human/HumanClientApp.cpp
> +    boost::optional<std::vector<int> > incompleteIDs(GetCombatLogManager().IncompleteLogIDs());
It does not need to be an `optional`.

`optional` has the following advantages:
- `optional` is semantically clearer regardless of the container type.
- an empty `optional` is smaller than an empty STL container.
- I was anticipating the transition to C++11.  Using `optional` with type inference means that the container type can be changed without this code changing.  I wrote this code before the transition to C++11 completed and did not go through and update anything.  I've updated this one line to illustrate why `optional` with type inference is more elegant.

````    
if (auto incomplete_ids {GetCombatLogManager().IncompleteLogIDs()})
        m_networking.SendMessage(RequestCombatLogsMessage(PlayerID(), *incomplete_ids));
````
- `std::optional` is available in C++17 as the standard way to express an optional/possible contained value.

2017-01-15 22:06 UTC, LGM-Doyle commented
@Vezzra your understanding is correct.  

As an aside, the current code has a TODO indicating that filtering of combat logs should be done in the future.  Currently, all combat logs are available to all clients.  In future, if that filtering was added, then clients would only be able to review combat logs for combat that they observed (most generous) or participated in (most mysterious).

2017-01-16 07:03 UTC, merged