Custom define pedia categories from content tags
freeorion/freeorion pull request #1248
Opened 2017-01-27 01:40 UTC by dbenage-cx

Supports custom defined categories for content definitions that are capable of content tags.
As noted on [forum thread](http://www.freeorion.org/forum/viewtopic.php?f=6&t=10343), does not support custom categories for:
* Specials
* Meter Types
* Ship Designs
* Monster Types

For testing, rebase onto: [This Branch](https://github.com/dbenage-cx/freeorion/tree/pedia_predef_category_focs_articles) (focs/stringtable changes only, for tech category)

2017-01-27 08:58 UTC, geoffthemedio requested changes

2017-01-27 08:58 UTC, geoffthemedio commented on UI/EncyclopediaDetailPanel.cpp
> +            if (boost::starts_with(tag, TAG_PEDIA_PREFIX))
Add some comments explaining what this is doing

2017-01-27 08:58 UTC, geoffthemedio commented on UI/EncyclopediaDetailPanel.cpp
> +            // Add articles for content tagged definitions
explain what "content tagged definitions" are a bit? lacking a lot of context, this is hard to understand.

2017-01-27 08:58 UTC, geoffthemedio commented on UI/EncyclopediaDetailPanel.cpp
> +    /** Checks content tags for pedia category, returns category of first match */
elaborate much more on this. I don't understand what it's doing from this comment.

2017-01-27 08:58 UTC, geoffthemedio commented on UI/EncyclopediaDetailPanel.cpp
> +    std::string TaggedCategory(const std::set<std::string>& tags) {
Maybe just this function needs a better name?
Can this return by reference?

2017-01-27 08:58 UTC, geoffthemedio commented on UI/EncyclopediaDetailPanel.cpp
> +    /** @content_tag{PEDIA_} Prefix to define a category for the article of the containing content definition. **/
....? explain more clearly. this comment seems to assume a lot of context that the comment doesn't have.

2017-01-27 17:33 UTC, dbenage-cx commented on UI/EncyclopediaDetailPanel.cpp
> +    std::string TaggedCategory(const std::set<std::string>& tags) {
Renamed function.
When a match is found, the return value would be locally defined.

2017-01-27 17:33 UTC, dbenage-cx commented
Rebased for changes in master

2017-01-29 09:35 UTC, geoffthemedio commented on UI/EncyclopediaDetailPanel.cpp
> +                    {LinkTaggedText(TextLinker::ENCYCLOPEDIA_TAG, article.name) + "\n", article.name)}};
Compile error. End should be }});

2017-01-29 11:28 UTC, geoffthemedio commented on UI/EncyclopediaDetailPanel.cpp
> +                    dir_entries[UserString(entry.first)] = {VarText::SHIP_PART_TAG, entry.first};
don't know why, but I get compile errors on all these lines. switching {} to std::make_pair() works though.

2017-01-29 11:40 UTC, adrianbroher commented on UI/EncyclopediaDetailPanel.cpp
> +                    dir_entries[UserString(entry.first)] = {VarText::SHIP_PART_TAG, entry.first};
@geoffthemedio 
> don't know why, but I get compile errors on all these lines.

Can you be more specific on this?

2017-01-29 11:53 UTC, geoffthemedio commented on UI/EncyclopediaDetailPanel.cpp
> +                    dir_entries[UserString(entry.first)] = {VarText::SHIP_PART_TAG, entry.first};
After swapping )}} to }}) as in an above comment:
````
1>ClCompile:
1>         EncyclopediaDetailPanel.cpp
1>     1>
1>..\..\UI\EncyclopediaDetailPanel.cpp(457): error C2143: syntax error: missing ';' before '}'
1>     1>
1>..\..\UI\EncyclopediaDetailPanel.cpp(462): error C2143: syntax error: missing ';' before '}'
1>     1>
1>..\..\UI\EncyclopediaDetailPanel.cpp(467): error C2143: syntax error: missing ';' before '}'
1>     1>
1>..\..\UI\EncyclopediaDetailPanel.cpp(472): error C2143: syntax error: missing ';' before '}'
1>     1>
1>..\..\UI\EncyclopediaDetailPanel.cpp(477): error C2143: syntax error: missing ';' before '}'
1>     1>
1>..\..\UI\EncyclopediaDetailPanel.cpp(482): error C2143: syntax error: missing ';' before '}'
1>
1>Build FAILED.
````

2017-01-29 15:19 UTC, dbenage-cx commented on UI/EncyclopediaDetailPanel.cpp
> +                    {LinkTaggedText(TextLinker::ENCYCLOPEDIA_TAG, article.name) + "\n", article.name)}};
Fixed

2017-01-29 15:22 UTC, dbenage-cx commented on UI/EncyclopediaDetailPanel.cpp
> +                    dir_entries[UserString(entry.first)] = {VarText::SHIP_PART_TAG, entry.first};
Changed map_value assignments from braced list-initialization to std::make_pair

2017-01-30 14:14 UTC, geoffthemedio commented
still not fully sure about what everything does, but seems ok otherwise...

2017-01-30 14:14 UTC, merged

2017-01-30 18:14 UTC, dbenage-cx commented
Ty for review, I will try to re-summarize.

Normally, an article for a definition is placed into a category for its type (e.g. Tech_A in category Techs).
This PR prevents any definitions with a category tag from listing in their default category.
Instead such articles are placed according to the resulting tag.

If `Tech_A` has a tag `PEDIA_ALPHA_TECHS`, it is removed from `ENC_TECH` category and added to `ALPHA_TECHS` category.

2017-01-30 18:19 UTC, dbenage-cx commented
@Ouaz Would you like me to open a PR for [these Tech categories](https://github.com/dbenage-cx/freeorion/tree/pedia_predef_category_focs_articles) or would you prefer to handle them differently?

2017-02-06 16:01 UTC, Ouaz commented
Oh sorry, I didn't connect to GH since last week, so I didn't see the notification.

I just updated the FR translation based on your PR (merged since your message above), and the Tech categories sorting are top-notch.

Great work!