Merge duplicates of source for empire.
freeorion/freeorion pull request #1250
Opened 2017-01-27 19:37 UTC by LGM-Doyle

This PR addresses https://github.com/freeorion/freeorion/issues/1242.

It also fixes a logic bug in that some universe objects were using invalid sources in their `ScriptingContexts`.

2017-01-28 07:45 UTC, geoffthemedio commented on Empire/Empire.cpp
> +    // "GetEmpire(id)->Source()" without requiring an intervening null check
Just have a GetSourceForEmpire(int id) function that can return nullptr. Not having a check that GetEmpire(id) didn't return nullptr is weird / misleading.

2017-01-28 07:47 UTC, geoffthemedio commented on Empire/Empire.cpp
> +void Empire::SetCapitalID(int id) {
probably shouldn't assume id is valid...

2017-01-28 07:47 UTC, geoffthemedio commented on Empire/Empire.cpp
> +    m_source_id = id;
for purposes of setting the source id at least

2017-01-28 07:49 UTC, geoffthemedio commented on Empire/Empire.h
> +    int                     SourceID() const;
calling a member function on a null pointer is probably undefined behaviour... as above, no.

2017-01-28 10:15 UTC, adrianbroher requested changes

2017-01-28 10:15 UTC, adrianbroher commented on Empire/Empire.cpp
> +    // "GetEmpire(id)->Source()" without requiring an intervening null check
> +    // Make it safe to use with a null this pointer.

That's nonstandard undefined behaviour. Rejected.

2017-01-28 17:37 UTC, LGM-Doyle commented on Empire/Empire.cpp
> +    // "GetEmpire(id)->Source()" without requiring an intervening null check
I added EmpireManager::GetSource(id) and removed the no-standard behavior.

2017-01-28 17:37 UTC, LGM-Doyle commented on Empire/Empire.cpp
> +void Empire::SetCapitalID(int id) {
I've added a check that the capital exists and is owned by the empire.

2017-01-28 17:37 UTC, LGM-Doyle commented on Empire/Empire.cpp
> +    m_source_id = id;
I've added a check that the source id is valid.  Source ids don't always need to exist in the code, it seems.

2017-01-28 17:37 UTC, LGM-Doyle commented on Empire/Empire.h
> +    int                     SourceID() const;
Fixed.

2017-01-28 18:47 UTC, adrianbroher commented on Empire/EmpireManager.cpp
> +    auto it{m_empire_map.find(id)};
The OSX clang compiler spitted out error messages the last time I used a similar construct.

See 89f801cc3e

2017-01-28 18:52 UTC, adrianbroher commented on Empire/Empire.cpp
> +    auto possible_capital {Objects().ExistingObject(id)};
Same here.

> The OSX clang compiler spitted out error messages the last time I used a similar construct.
>
> See 89f801c

2017-01-28 18:52 UTC, adrianbroher approved these changes

2017-01-28 20:42 UTC, LGM-Doyle reviewed
Thanks for the quick reviews.

2017-01-28 20:42 UTC, LGM-Doyle commented on Empire/EmpireManager.cpp
> +    auto it{m_empire_map.find(id)};
New features, new quirks :smile:.  Fixed.

2017-01-28 20:42 UTC, LGM-Doyle commented on Empire/Empire.cpp
> +    auto possible_capital {Objects().ExistingObject(id)};
Fixed.

2017-01-29 09:41 UTC, adrianbroher commented
Looks good.

2017-01-29 09:42 UTC, merged