Add helper script for cpp api python filter
freeorion/freeorion pull request #1255
Opened 2017-01-29 20:11 UTC by dbenage-cx

Workaround for the multiple no file found warnings:
 `sh: @PYTHON_EXECUTABLE@ @FreeOrion_SOURCE_DIR@/doc/tag_filter.py: No such file or directory
`

2017-01-29 20:19 UTC, Cjkjvfnby commented
Does docs work on windows?

2017-01-29 20:36 UTC, dbenage-cx commented
@Cjkjvfnby not to my knowledge unless your using cmake, which I assume would be `Cygwin` or `MinGW`

2017-01-29 23:54 UTC, dbenage-cx commented
As it was no longer working, rewrote the tag filter.

2017-01-30 21:16 UTC, Cjkjvfnby requested changes
I checked python code.
I cant run this code. 

It there a place where I can check documentation?

Here is my attempt for python documentation
https://github.com/Cjkjvfnby/freeorion/pull/15

2017-01-30 21:16 UTC, Cjkjvfnby commented on doc/tag_filter.py
> +if match_found:
Drop `match_found` and this check.  IF buffer is empty nothing will be written to stdout.

I prefer to see something like 
```
sys.stdout.write('\n'.join(buffer))
sys.stdout.write('\n')
```

2017-01-30 21:16 UTC, Cjkjvfnby commented on doc/tag_filter.py
> +        elif prev_line:
Maybe rename to something like `collected_data`

2017-01-30 21:16 UTC, Cjkjvfnby commented on doc/tag_filter.in
> +    eval "$py_exec $py_sh $target_file"
And who is catching stdout?

2017-01-31 00:19 UTC, dbenage-cx commented on doc/tag_filter.in
> +    eval "$py_exec $py_sh $target_file"
Doxygen,  I will explain more in a comment outside of this review block (so others may see it easier)

2017-01-31 00:19 UTC, dbenage-cx commented on doc/tag_filter.py
> +if match_found:
The purpose of `match_found` is to not output the buffer when there is no match.
Unless we want to document all python code within the cpp api?

2017-01-31 00:19 UTC, dbenage-cx commented on doc/tag_filter.py
> +        elif prev_line:
Fixed

2017-01-31 00:19 UTC, dbenage-cx commented on doc/tag_filter.py
> +            ln_void, ln_tag, ln_content = line.partition(tag_comment)
Fixed

2017-01-31 00:19 UTC, dbenage-cx commented on doc/tag_filter.py
> +        # doxygen wont document this alias if it is indented
Fixed

2017-01-31 00:19 UTC, dbenage-cx commented on doc/tag_filter.py
> +prev_line = list()
Fixed

2017-01-31 01:23 UTC, dbenage-cx commented
@Cjkjvfnby TY for reviewing python portion.

The helper script is a workaround to doxygen deciding "`python` `tag_filter.py`" is a single file to be executed (and warns that it can not find).  This file is a shell script as I assume a supporting environment when using the cmake build (`doc` is not a target for MSVC or XCode, only CMake).
I'm not excited about the choice to use a shell script here, but I'd rather not compile some new utility program either.

This helper script is translated from `doc/tag_filter.in` by CMake.
Doxygen is configured to call this script for any `*.py` file, with the input file as the argument
 ( `tag_filter.sh` `source_file.py` -> `python` `tag_filter.py` `source_file.py` ).
The output is then used to determine content and link creation within the generated documentation.
If there is any output, lines can not be added or removed, otherwise anchors are not correctly placed.
When there is no output, there is no generated content.

The purpose of including some of the python code here is to provide a central place for documentation of all `content definition tags`.  The specific page for these tags is: [Content Definition Tags](http://freeorion.github.io/cppapi/master/content_tags.html).  FOCS files are not yet parsed.

> It there a place where I can check documentation?

I can upload a generated cpp-api from this branch if needed, but the main concerns addressed here are not reflected in the current output of master:
* This PR allows cases such as (this change)[https://github.com/freeorion/freeorion/pull/1225#pullrequestreview-17138212] to still be valid.
* More efficient and correct python implementation
* Reduces error warnings when generating the documentation

> Here is my attempt for python documentation

For the purpose of content tag documentation, I do not have a preference between Doxygen and Sphinx.  For a central reference of these tags, c++, python, and definition script files will need to be parsed.  (I will put Sphinx on my todo list to familiarize myself with)

2017-02-01 14:58 UTC, adrianbroher commented
> Does docs work on windows?

Generate your platform specific build system with CMake and run the `doc` target.  This will create the documentation for C++ with Doxygen.  Opposing to @dbenage-cx this isn't limited (or related at all) to `Cygwin` or `MinGW`.  This is not related to your attempt of documentation generation for python.

> It there a place where I can check documentation?

http://freeorion.github.io/cppapi/master/

> Here is my attempt for python documentation.

I am aware of your efforts, but realizing this as part of the CI isn't as easy as you may think.  As far as I know currently there is no way to generate the python documentation without running the freeorion client without human interaction.

> I cant run this code.

As @dbenage-cx already mentioned it is not intended to be run as standalone program, but rather as a [doxygen input filter](http://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_input_filter).

2017-02-01 15:00 UTC, adrianbroher commented
@dbenage-cx 

> fixup 3ef3906

Is there are reason why this isn't fixed up in git (e.g. squashed)?

2017-02-01 15:25 UTC, dbenage-cx commented
@adrianbroher : reviewer preference, I plan to fixup that commit once changes are approved.

2017-02-01 18:34 UTC, Cjkjvfnby commented on doc/tag_filter.py
> +if match_found:
Now I see, that you rebuild full file. I thought that you extract only comments to console.

2017-02-01 18:34 UTC, Cjkjvfnby approved these changes

2017-02-02 10:03 UTC, adrianbroher commented
Works for me.  The reported error is gone.

2017-02-02 10:03 UTC, merged