Replace use of lexical_cast for int to string conversions
freeorion/freeorion pull request #1256
Opened 2017-01-30 02:38 UTC by dbenage-cx

Partial towards #1244

2017-01-30 09:47 UTC, adrianbroher requested changes
Looks good so far.

But I would generally prefer if you and @LGM-Doyle (actually this applies to the whole @freeorion/developers team, including me) would set yourself as assignee to the corresponding issue report as soon as you start working on this.

I don't know if it already happened somewhere but there is always the danger of two people working on the same  project without know that.  There is no need to waste peoples time and disgruntle at least the person(s) that effort was binned.

2017-01-30 09:47 UTC, adrianbroher commented on Empire/Empire.cpp
> +                         " ID: "+ std::to_string(m_id) +
When those lines are touched anyway you can also add the missing space between the string literal and the `+`.

2017-01-30 09:47 UTC, adrianbroher commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(color.r)),
The cast shouldn't be required and does a unsigned to signed conversion.

GG::Clr holds `unsigned char` as color channels.  Also std::to_string only accepts int, long, long long and the unsigned counterpart as integer inputs.  This should implicit cast uchar to uint but better check if the control still displays the correct value and not a character.

2017-01-30 09:47 UTC, adrianbroher commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(m_current_color.h * 359)),
Same here.

> The cast shouldn't be required and does a unsigned to signed conversion.

 Add a 'u' literal suffix instead.

2017-01-30 09:47 UTC, adrianbroher commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(color.g)),
Same here.

> The cast shouldn't be required and does a unsigned to signed conversion.
>
> GG::Clr holds `unsigned char` as color channels.  Also std::to_string only accepts int, long, long long and the unsigned counterpart as integer inputs.  This should implicit cast uchar to uint but better check if the control still displays the correct value and not a character.

2017-01-30 09:47 UTC, adrianbroher commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(color.b)),
Same here.

> The cast shouldn't be required and does a unsigned to signed conversion.
>
> GG::Clr holds `unsigned char` as color channels.  Also std::to_string only accepts int, long, long long and the unsigned counterpart as integer inputs.  This should implicit cast uchar to uint but better check if the control still displays the correct value and not a character.

2017-01-30 09:47 UTC, adrianbroher commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(color.a)),
Same here.

> The cast shouldn't be required and does a unsigned to signed conversion.
>
> GG::Clr holds `unsigned char` as color channels.  Also std::to_string only accepts int, long, long long and the unsigned counterpart as integer inputs.  This should implicit cast uchar to uint but better check if the control still displays the correct value and not a character.

2017-01-30 09:47 UTC, adrianbroher commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(m_current_color.s * 255)),
Same here.

> The cast shouldn't be required and does a unsigned to signed conversion.
>
> Add a 'u' literal suffix instead.

2017-01-30 09:47 UTC, adrianbroher commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(m_current_color.v * 255)),
Same here.

> The cast shouldn't be required and does a unsigned to signed conversion.
>
> Add a 'u' literal suffix instead.

2017-01-30 09:47 UTC, adrianbroher commented on UI/SpecialsPanel.cpp
> +            desc += "\n" + boost::io::str(FlexibleFormat(UserString("ADDED_ON_TURN")) % std::to_string(entry.second.first));
Does this even require a `to_string` at all?

2017-01-30 09:47 UTC, adrianbroher commented on UI/TechTreeWnd.cpp
> +    std::string cost_str = std::to_string(static_cast<int>(this_row_tech->ResearchCost(HumanClientApp::GetApp()->EmpireID()) + 0.5));
That's some ugly way to write `std::round`.

2017-01-30 09:47 UTC, adrianbroher commented on UI/TechTreeWnd.cpp
> +    std::string cost_str = std::to_string(static_cast<int>(this_row_tech->ResearchCost(HumanClientApp::GetApp()->EmpireID()) + 0.5));
Same here.

> That's some ugly way to write `std::round`.

2017-01-30 09:47 UTC, adrianbroher commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_MONSTER_FLEET_NAME")) % std::to_string(ID()));
Same here.

> Does this even require a `to_string` at all?

2017-01-30 09:47 UTC, adrianbroher commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_COLONY_FLEET_NAME")) % std::to_string(ID()));
Same here.

> Does this even require a `to_string` at all?

2017-01-30 09:47 UTC, adrianbroher commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_RECON_FLEET_NAME")) % std::to_string(ID()));
Same here.

> Does this even require a `to_string` at all?

2017-01-30 09:47 UTC, adrianbroher commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_TROOP_FLEET_NAME")) % std::to_string(ID()));
Same here.

> Does this even require a `to_string` at all?

2017-01-30 09:47 UTC, adrianbroher commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_BOMBARD_FLEET_NAME")) % std::to_string(ID()));
Same here.

> Does this even require a `to_string` at all?

2017-01-30 09:47 UTC, adrianbroher commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_BATTLE_FLEET_NAME")) % std::to_string(ID()));
Same here.

> Does this even require a `to_string` at all?

2017-01-30 09:47 UTC, adrianbroher commented on universe/Fleet.cpp
> +    return boost::io::str(FlexibleFormat(UserString("NEW_FLEET_NAME")) % std::to_string(ID()));
Same here.

> Does this even require a `to_string` at all?

2017-01-30 17:50 UTC, dbenage-cx commented on Empire/Empire.cpp
> +                         " ID: "+ std::to_string(m_id) +
Fixed

2017-01-30 17:50 UTC, dbenage-cx commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(color.r)),
Fixed

2017-01-30 17:50 UTC, dbenage-cx commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(color.g)),
Fixed

2017-01-30 17:50 UTC, dbenage-cx commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(color.b)),
Fixed

2017-01-30 17:50 UTC, dbenage-cx commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(color.a)),
Fixed

2017-01-30 17:50 UTC, dbenage-cx commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(m_current_color.h * 359)),
Unchanged: explicit cast to int from double

2017-01-30 17:50 UTC, dbenage-cx commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(m_current_color.s * 255)),
Unchanged: explicit cast to int from double

2017-01-30 17:50 UTC, dbenage-cx commented on GG/src/dialogs/ColorDlg.cpp
> +    m_slider_values.push_back(style->NewTextControl(std::to_string(static_cast<int>(m_current_color.v * 255)),
Unchanged: explicit cast to int from double

2017-01-30 17:51 UTC, dbenage-cx commented on UI/SpecialsPanel.cpp
> +            desc += "\n" + boost::io::str(FlexibleFormat(UserString("ADDED_ON_TURN")) % std::to_string(entry.second.first));
Fixed

2017-01-30 17:51 UTC, dbenage-cx commented on UI/TechTreeWnd.cpp
> +    std::string cost_str = std::to_string(static_cast<int>(this_row_tech->ResearchCost(HumanClientApp::GetApp()->EmpireID()) + 0.5));
Changed to std::round instead of `+ 0.5`, left explicit cast to int

2017-01-30 17:51 UTC, dbenage-cx commented on UI/TechTreeWnd.cpp
> +    std::string cost_str = std::to_string(static_cast<int>(this_row_tech->ResearchCost(HumanClientApp::GetApp()->EmpireID()) + 0.5));
Changed to std::round instead of `+ 0.5`, left explicit cast to int

2017-01-30 17:51 UTC, dbenage-cx commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_MONSTER_FLEET_NAME")) % std::to_string(ID()));
Fixed

2017-01-30 17:51 UTC, dbenage-cx commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_COLONY_FLEET_NAME")) % std::to_string(ID()));
Fixed

2017-01-30 17:51 UTC, dbenage-cx commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_RECON_FLEET_NAME")) % std::to_string(ID()));
Fixed

2017-01-30 17:51 UTC, dbenage-cx commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_TROOP_FLEET_NAME")) % std::to_string(ID()));
Fixed

2017-01-30 17:51 UTC, dbenage-cx commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_BOMBARD_FLEET_NAME")) % std::to_string(ID()));
Fixed

2017-01-30 17:51 UTC, dbenage-cx commented on universe/Fleet.cpp
> +        return boost::io::str(FlexibleFormat(UserString("NEW_BATTLE_FLEET_NAME")) % std::to_string(ID()));
Fixed

2017-01-30 17:51 UTC, dbenage-cx commented on universe/Fleet.cpp
> +    return boost::io::str(FlexibleFormat(UserString("NEW_FLEET_NAME")) % std::to_string(ID()));
Fixed

2017-01-30 17:56 UTC, dbenage-cx commented
TY for review, I've left the casts to int where it is desired for the resulting format.

2017-02-01 11:00 UTC, adrianbroher commented
Revisiting the `std::round` calls it is probably better to use `std::lround` as it return a long int, removing the need for a cast.

Do you want to add additional commits to this PR aside from 28475d9c4 and ongoing?

2017-02-01 15:16 UTC, dbenage-cx commented
I don't mind, I do want to stay away from representations of floating points in this PR as they will need more thorough testing under `std::to_string`.

2017-02-01 23:52 UTC, dbenage-cx commented on UI/TechTreeWnd.cpp
> +    std::string cost_str = std::to_string(static_cast<int>(this_row_tech->ResearchCost(HumanClientApp::GetApp()->EmpireID()) + 0.5));
Changed to `std::lround`

2017-02-01 23:52 UTC, dbenage-cx commented on UI/TechTreeWnd.cpp
> +    std::string cost_str = std::to_string(static_cast<int>(this_row_tech->ResearchCost(HumanClientApp::GetApp()->EmpireID()) + 0.5));
Changed to `std::lround`

2017-02-01 23:57 UTC, dbenage-cx commented
I've reworded commits with a more appropriate message.
Those commits with changes since your initial review were moved to the bottom: c9abe24 onward.
A commit was added for missed cases in UI/OptionsWnd.cpp

2017-02-02 07:41 UTC, geoffthemedio commented
Builds OK on MSVC.

2017-02-02 09:37 UTC, adrianbroher approved these changes

2017-02-02 09:42 UTC, adrianbroher commented
> Are there others cases you would like covered in this PR?

There are probably some cases missing:

```cpp
$ grep -rn 'lexical_cast<std::string>' * | grep -v '\<any_cast\|false\|Eval\|Dump\|size\|type\|Type\|Size\|LARGE_VALUE\|m_meter\|FLT_MAX\>'
client/human/HumanClientApp.cpp:130:    { return boost::lexical_cast<std::string>(glGetString(GL_VERSION)); }
Empire/ResourcePool.cpp:127:                         " stockpile = " + boost::lexical_cast<std::string>(m_stockpile) +
Empire/Empire.cpp:1514:                  boost::lexical_cast<std::string>(meter.second.Initial()) + "\n";
GG/GG/TextControl.h:367:{ SetText(boost::lexical_cast<std::string>(t)); }
GG/GG/Spin.h:436:    m_edit = style->NewSpinEdit(boost::lexical_cast<std::string>(m_value), font, CLR_ZERO, text_color, CLR_ZERO);
GG/src/GUI.cpp:70:                  boost::lexical_cast<std::string>(key) +
GG/src/GUI.cpp:72:                  boost::lexical_cast<std::string>(mod_keys) +
UI/SidePanel.cpp:852:    { return UserString(boost::lexical_cast<std::string>(planet->EnvironmentForSpecies(species_name))); }
UI/SidePanel.cpp:1868:                                                boost::lexical_cast<std::string>(apparent_stealth)                  %
UI/SidePanel.cpp:1869:                                                boost::lexical_cast<std::string>(client_empire_detection_strength));
UI/SidePanel.cpp:1873:                                                boost::lexical_cast<std::string>(client_empire_detection_strength));
UI/SidePanel.cpp:1893:                                                boost::lexical_cast<std::string>(apparent_stealth)                  %
UI/SidePanel.cpp:1894:                                                boost::lexical_cast<std::string>(client_empire_detection_strength));
UI/SidePanel.cpp:1898:                                                boost::lexical_cast<std::string>(client_empire_detection_strength));
UI/DesignWnd.cpp:931:        m_class_buttons[part_class] = new CUIStateButton(UserString(boost::lexical_cast<std::string>(part_class)), GG::FORMAT_CENTER, std::make_shared<CUILabelButtonRepresenter>());
UI/ObjectListWnd.cpp:320:            retval.push_back(boost::lexical_cast<std::string>(enum_val));
UI/ObjectListWnd.cpp:986:            label = new CUIButton(" " + UserString(boost::lexical_cast<std::string>(uot)) + " ");
UI/EncyclopediaDetailPanel.cpp:1745:                detailed_description += UserString(boost::lexical_cast<std::string>(pt_env.first)) + " : " +
UI/EncyclopediaDetailPanel.cpp:1746:                                        UserString(boost::lexical_cast<std::string>(pt_env.second)) + "\n";
UI/EncyclopediaDetailPanel.cpp:2366:                    % UserString(boost::lexical_cast<std::string>(it->second.second))
UI/EncyclopediaDetailPanel.cpp:2380:                    % UserString(boost::lexical_cast<std::string>(it->second.second))
UI/MapWnd.cpp:457:                                                boost::lexical_cast<std::string>(shown_length));
UI/FleetWnd.cpp:932:        ErrorLogger() << "ShipDataPanel::StatValue couldn't get stat of name: " << boost::lexical_cast<std::string>(stat_name);
universe/ValueRef.h:621:{ return UserString(boost::lexical_cast<std::string>(m_value)); }
universe/ValueRef.cpp:285:        return boost::lexical_cast<std::string>(m_value);
universe/Condition.cpp:1215:                   % UserString(boost::lexical_cast<std::string>(m_affiliation))
universe/Condition.cpp:4953:               % UserString(boost::lexical_cast<std::string>(m_class)));
universe/Condition.cpp:4962:    retval += " class = " + UserString(boost::lexical_cast<std::string>(m_class));
universe/Condition.cpp:5994:               % UserString(boost::lexical_cast<std::string>(m_stockpile))
util/ModeratorAction.cpp:99:                       + boost::lexical_cast<std::string>(m_id_1)
util/ModeratorAction.cpp:101:                       + boost::lexical_cast<std::string>(m_id_2);
util/ModeratorAction.cpp:135:                       + boost::lexical_cast<std::string>(m_id_1)
util/ModeratorAction.cpp:137:                       + boost::lexical_cast<std::string>(m_id_2);
util/ModeratorAction.cpp:192:                       + boost::lexical_cast<std::string>(m_x)
util/ModeratorAction.cpp:194:                       + boost::lexical_cast<std::string>(m_y)
```

At least some of the `util/ModeratorAction.cpp` matches are int types.  But you will probably find even more by just running `grep -r '\<lexical_cast<std::string>\>' *`.  You can also remove unnecessary headers and `using` statements if you want to.

2017-02-02 14:56 UTC, dbenage-cx commented
TY, I will post a list of missed cases (and reason) later tonight.

2017-02-02 19:49 UTC, dbenage-cx commented
Instances of `lexical_cast<std::string>` not converted in this PR:

Line | arg/variable | from type
---|---|---
Empire/Empire.cpp:770                       |   build_type                          |   enum BuildType
Empire/Empire.cpp:1514                      |   meter.second.Initial()              |   float
Empire/Empire.cpp:2417                      |   build_type                          |   enum BuildType
Empire/Empire.cpp:2428                      |   build_type                          |   enum BuildType
Empire/Empire.cpp:2449                      |   build_type                          |   enum BuildType
Empire/ResourcePool.cpp:126                 |   m_type                              |   enum MeterType
Empire/ResourcePool.cpp:127                 |   m_stockpile                         |   float
Empire/ResourcePool.cpp:148                 |   m_type                              |   enum MeterType
GG/GG/Spin.h:436                            |   m_value                             |   class T
GG/GG/TextControl.h:367                     |   t                                   |   class T
GG/src/GUI.cpp:70                           |   key                                 |   enum Key
GG/src/GUI.cpp:72                           |   mod_keys                            |   class Flags
UI/BuildDesignmatorWnd.cpp:1159             |   type                                |   enum BuildType
UI/BuildDesignmatorWnd.cpp:1175             |   type                                |   enum BuildType
UI/ClientUI.cpp:458                         |   retval.size()                       |   size_type
UI/DesignWnd.cpp:931                        |   part_class                          |   enum ShipPartClass
UI/EncyclopediaDetailPanel.cpp:81           |   meter_type                          |   enum MeterType
UI/EncyclopediaDetailPanel.cpp:1096         |   part->Class()                       |   enum ShipPartClass
UI/EncyclopediaDetailPanel.cpp:1259         |   item.type                           |   enum UnlockableItemType
UI/EncyclopediaDetailPanel.cpp:1745         |   pt_env.first                        |   enum PlanetType
UI/EncyclopediaDetailPanel.cpp:1746         |   pt_env.second                       |   enum PlanetEnvironment
UI/EncyclopediaDetailPanel.cpp:2222         |   planet->Type()                      |   enum PlanetType
UI/EncyclopediaDetailPanel.cpp:2366         |   it->second.second                   |   enum PlanetEnvironment
UI/EncyclopediaDetailPanel.cpp:2380         |   it->second.second                   |   enum PlanetEnvironment
UI/EncyclopediaDetailPanel.cpp:2839         |   meter_type                          |   enum MeterType
UI/FleetWnd.cpp:932                         |   stat_name                           |   enum MeterType
UI/MapWnd.cpp:457                           |   shown_length                        |   double
UI/MeterBrowseWnd.cpp:126                   |   meter_type                          |   enum MeterType
UI/MilitaryPanel.cpp:110                    |   meter_type                          |   enum MeterType
UI/MultiIconValueIndicator.cpp:154          |   meter_type                          |   enum MeterType
UI/ObjectListWnd.cpp:156                    |   meter                               |   enum MeterType
UI/ObjectListWnd.cpp:320                    |   enum_val                            |   enum T
UI/ObjectListWnd.cpp:986                    |   uot                                 |   enum UniverseObjectType
UI/PopulationPanel.cpp:108                  |   meter_type                          |   enum MeterType
UI/SidePanel.cpp:845                        |   planet->Size()                      |   enum PlanetSize
UI/SidePanel.cpp:849                        |   planet->Type()                      |   enum PlanetType
UI/SidePanel.cpp:852                        |   planet->EnvironmentForSpecies()     |   enum PlanetEnvironment
UI/SidePanel.cpp:857                        |   system->GetStarType()               |   enum StarType
UI/SidePanel.cpp:1868                       |   apparent_stealth                    |   float
UI/SidePanel.cpp:1869                       |   client_empire_detection_strength    |   float
UI/SidePanel.cpp:1873                       |   client_empire_detection_strength    |   float
UI/SidePanel.cpp:1893                       |   apparent_stealth                    |   float
UI/SidePanel.cpp:1894                       |   client_empire_detection_strength    |   float
UI/SidePanel.cpp:1898                       |   client_empire_detection_strength    |   float
UI/SystemResourceSummaryBrowseWnd.cpp:294   |   m_resource_type                     |   enum ResourceType
client/human/HumanClientApp.cpp:130         |   glGetString()                       |   const unsigned char*
server/ServerApp.cpp:388                    |   msg.Type()                          |   enum MessageType
universe/Building.cpp:179                   |   m_capture_result                    |   enum CaptureResult
universe/Condition.cpp:1215                 |   m_affiliation                       |   enum EmpireAffiliationType
universe/Condition.cpp:1746                 |   m_type->Eval()                      |   enum UniverseObjectType
universe/Condition.cpp:2161                 |   -FLT_MAX                            |   float
universe/Condition.cpp:2165                 |   FLT_MAX                             |   float
universe/Condition.cpp:2193                 |   -FLT_MAX                            |   float
universe/Condition.cpp:2194                 |   FLT_MAX                             |   float
universe/Condition.cpp:3255                 |   m_types[i]->Eval()                  |   enum PlanetType
universe/Condition.cpp:3433                 |   m_sizes[i]->Eval()                  |   enum PlanetSize
universe/Condition.cpp:3627                 |   m_environments[i]->Eval()           |   enum PlanetEnvironment
universe/Condition.cpp:4507                 |   m_types[i]->Eval()                  |   enum PlanetType
universe/Condition.cpp:4962                 |   m_class                             |   enum ShipPartClass
universe/Condition.cpp:5383                 |   std::max(0.0, ...)                  |   double
universe/Condition.cpp:5519                 |   Meter::LARGE_VALUE                  |   float
universe/Condition.cpp:5523                 |   Meter::LARGE_VALUE                  |   float
universe/Condition.cpp:5529                 |   m_meter                             |   enum MeterType
universe/Condition.cpp:5535                 |   m_meter                             |   enum MeterType
universe/Condition.cpp:5541                 |   m_meter                             |   enum MeterType
universe/Condition.cpp:5678                 |   -Meter::LARGE_VALUE                 |   float
universe/Condition.cpp:5684                 |   Meter::LARGE_VALUE                  |   float
universe/Condition.cpp:5696                 |   m_meter                             |   enum MeterType
universe/Condition.cpp:5848                 |   Meter::LARGE_VALUE                  |   float
universe/Condition.cpp:5852                 |   Meter::LARGE_VALUE                  |   float
universe/Condition.cpp:5994                 |   m_stockpile                         |   enum ResourceType
universe/Condition.cpp:6531                 |   m_distance-.Eval()                  |   double
universe/Planet.cpp:466                     |   type                                |   enum MeterType
universe/Planet.cpp:472                     |   type                                |   enum MeterType
universe/PopCenter.cpp:63                   |   meter_type                          |   enum MeterType
universe/PopCenter.cpp:71                   |   meter_type                          |   enum MeterType
universe/PopCenter.cpp:79                   |   meter_type                          |   enum MeterType
universe/PopCenter.cpp:97                   |   meter_type       [...]

2017-02-02 20:14 UTC, geoffthemedio commented
meter.second.Initial() should be a float. various ids should be ints. At least some of the ModeratorAction id's are doubles (though I don't know why they're not ints).

2017-02-05 14:36 UTC, adrianbroher requested changes

2017-02-05 14:36 UTC, adrianbroher commented on universe/Condition.cpp
> +                                    m_low->Eval() :
`m_low->Eval()` returns an int, so a `std::to_string` is still required.

2017-02-05 14:36 UTC, adrianbroher commented on universe/Condition.cpp
> +                                      m_high->Eval() :
`m_high->Eval()` returns an int, so a `std::to_string` is still required.

2017-02-05 14:36 UTC, adrianbroher commented on universe/Condition.cpp
> +    std::string number_str = m_number->ConstantExpr() ? std::to_string(m_number->Dump()) : m_number->Description();
`m_number->Dump()` always returns a `std::string` and there exists no `std::to_string` variant that accepts a `std::string`.

2017-02-05 14:53 UTC, adrianbroher commented
> At least some of the ModeratorAction id's are doubles (though I don't know why they're not ints).

I think that's a copy and paste error.  As client of `CreateStarlane` and `RemoveStarlane` are not able to set the member variables to a double value and those values are only passed to functions that have int parameters.  It would be better to change this.

> I assume std::size_t isn't handled by to_string, though I'm not sure if an implicit cast would make it work.

That's right, there is no explicit `std::to_string(size_t)` and yes, an implicit cast to any of `std::to_string(unsigned int)`, `std::to_string(unsigned long)` or `std::to_string(unsigned long long)` should work here.

2017-02-05 18:01 UTC, dbenage-cx commented on universe/Condition.cpp
> +    std::string number_str = m_number->ConstantExpr() ? std::to_string(m_number->Dump()) : m_number->Description();
Fixed

2017-02-05 18:01 UTC, dbenage-cx commented on universe/Condition.cpp
> +                                    m_low->Eval() :
Fixed

2017-02-05 18:01 UTC, dbenage-cx commented on universe/Condition.cpp
> +                                      m_high->Eval() :
Fixed

2017-02-05 18:02 UTC, dbenage-cx commented
TY for careful reviews, rebased to master and caught cases for ModeratorAction and size_t

2017-02-06 21:42 UTC, adrianbroher approved these changes

2017-02-06 21:43 UTC, adrianbroher commented
Looks good. Thank you for looking into this.

2017-02-06 22:05 UTC, merged

2017-02-06 22:12 UTC, dbenage-cx commented
Thank you, will remove myself from issue until I can actually start on testing fp types (in case someone wants to pick it up in meantime).