Replace get_systems_within_jumps() from galaxy.py
freeorion/freeorion pull request #1294
Opened 2017-02-07 18:50 UTC by LGM-Doyle

This PR replaces `get_systems_within_jumps()` with a server provided faster version based on the `Pathfinder` cache.

I mentioned this in PR #1225 about improving the galaxy generation.  The improvement without #1225 is marginal.

2017-02-07 21:14 UTC, genestack-solomatin commented on python/server/ServerWrapper.cpp
> +        def("systems_within_jumps",                 SystemsWithinJumps);
You can add documentation string as third argument here.

2017-02-08 09:55 UTC, adrianbroher requested changes
You should really reconsider your general variable naming style.

2017-02-08 09:55 UTC, adrianbroher commented on python/server/ServerWrapper.cpp
> +        for (auto ii : near) {
ii?

2017-02-08 09:55 UTC, adrianbroher commented on python/server/ServerWrapper.cpp
> +        auto near = GetPathfinder()->WithinJumps(jumps, systems);
near?

2017-02-08 09:55 UTC, adrianbroher commented on universe/Pathfinder.cpp
> +    for (auto it : m_system_id_to_graph_index) {
it?

2017-02-08 09:55 UTC, adrianbroher commented on universe/Pathfinder.cpp
> +    size_t ii, const distance_matrix_storage<short>::row_ref row) const {
ii?

2017-02-08 10:26 UTC, geoffthemedio commented on universe/Pathfinder.cpp
> +    for (auto it : m_system_id_to_graph_index) {
not that unusual for an iterator type in FO code...

2017-02-08 11:07 UTC, adrianbroher commented on universe/Pathfinder.cpp
> +    for (auto it : m_system_id_to_graph_index) {
True, but range based for loops don't use the iterator directly but the type that the iterator dereferences to.

2017-02-08 18:03 UTC, Vezzra approved these changes
Can't comment on the C++ side of things, as your implementation goes over my head, but moving this into the backend code is certainly a good idea.

Everything else looks good to me, builds and runs ok on OSX. LGTM (as far as I'm concerned).

2017-02-08 19:06 UTC, Cjkjvfnby commented
> but moving this into the backend code is certainly a good idea
@Vezzra, why?

Python is slower when C++, but not so slow.  I expect that using cache should give more benefits then changing language. 

Code in python usually more readable.

2017-02-08 22:43 UTC, LGM-Doyle reviewed
This is backend vs frontend issue.  

The backend can access all of the information to compute this result in a single vector.  The provided function `fo.systems_within_jumps(range, [systems])` is an intuitive  addition to the ServerWrapper.  The best place to do the calculation is where the data is.

2017-02-08 22:43 UTC, LGM-Doyle commented on python/server/ServerWrapper.cpp
> +        def("systems_within_jumps",                 SystemsWithinJumps);
Thanks.

2017-02-08 22:43 UTC, LGM-Doyle commented on python/server/ServerWrapper.cpp
> +        auto near = GetPathfinder()->WithinJumps(jumps, systems);
Could you provide suggestions?

I've found that no matter what names I choose someone finds them too terse, too verbose, too cryptic or all of the above.

2017-02-08 22:43 UTC, LGM-Doyle commented on universe/Pathfinder.cpp
> +    size_t ii, const distance_matrix_storage<short>::row_ref row) const {
That is the row index, typically written  `i`.  However `ii` is much easier to grep.  This one I'd like to keep.

2017-02-08 23:12 UTC, adrianbroher commented on python/server/ServerWrapper.cpp
> +        auto near = GetPathfinder()->WithinJumps(jumps, systems);
After looking into the other changes why not use 'systems_in_vicinity'?  It was already a good name and the documentation for the python `get_systems_within_jumps` just provided the information I am missing out at `WithinJumps` so it should be transferred and adapted accordingly.

> I've found that no matter what names I choose someone finds them too terse, too verbose, too cryptic or all of the above.

That's the outcome of cooperative development. Everybody has to deal with different opinions. ;)  In genreal I will always complain about terse or generalized names if the context doesn't provide any information about the code usage. In this case `near` just didn't ring a bell.

2017-02-08 23:12 UTC, adrianbroher commented on python/server/ServerWrapper.cpp
> +        for (auto ii : near) {
`system_id` would probably better.

2017-02-11 18:47 UTC, Vezzra commented
> Python is slower when C++, but not so slow.

IMO the speed advantage C++ offers is still significant enough to justify moving the implementation only for that (and then there are the reasons @LGM-Doyle cited).

> I expect that using cache should give more benefits then changing language.

Sure, but that's no reason not to take advantage of the additional performance boost the change to C++ offers.

> Code in python usually more readable.

Yes, but that's not really relevant in case of this function. Any speed gain, even if it's only a moderate one, is more important than the not quite as good readability.

2017-02-12 22:29 UTC, LGM-Doyle reviewed
I think that I have addressed the concerns.
I've also rebased it and used it to replace uses of get_systems_within_jumps() in the newly merged code from #1225.

2017-02-13 09:59 UTC, Vezzra commented
Just noticed a minor thing: you did not remove the now obsolete `galaxy_topology.py`. Any reason for this?

2017-02-14 09:27 UTC, adrianbroher approved these changes

2017-02-14 11:13 UTC, LGM-Doyle commented
Fixed.

The rebasing removed the original commit that removed the file.

2017-02-14 14:12 UTC, merged