Check color and name uniqueness.
freeorion/freeorion pull request #1314
Opened 2017-02-13 21:05 UTC by o01eg

1. Don't allow to connect if this name used by other player or can be used by AI.
2. Check if empire names have duplicates among other player names. Change empire name when someone use it as a player name.
3. Ignore updates if they lead to duplicate colour, player or empire name.

2017-02-13 22:02 UTC, geoffthemedio commented
As in linked issue, don't reject players; rename.

2017-02-14 20:53 UTC, o01eg commented
Rebased. Add postfix-based rename and remove from player name "AI_" prefix.

2017-02-14 22:19 UTC, geoffthemedio requested changes

2017-02-14 22:19 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +            new_player_name = player_name + std::to_string(++ t); // start alternative names from 2
space b/w ++ and t

2017-02-14 22:19 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +            for (std::pair<int, PlayerSetupData>& plrs : m_lobby_data->m_players) {
plrs is just one player, so should probably not have an s in the name

2017-02-14 22:19 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +        if (! server.IsAvailableName(new_player_name)) {
space

2017-02-14 22:19 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +                    if (m_lobby_data->m_seed!="")
spaces around !=

2017-02-14 22:19 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +                        has_important_changes = has_important_changes || (! is_found_player);
space after !

2017-02-14 22:19 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +                std::list<std::pair<int, PlayerSetupData> >::iterator player_setup_it = m_lobby_data->m_players.begin();
remove extra space between > >

2017-02-14 22:19 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +            std::list<std::pair<int, PlayerSetupData> >::iterator player_setup_it = m_lobby_data->m_players.begin();
space between > >

2017-02-14 22:19 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +                    std::list<std::pair<int, PlayerSetupData> >::iterator erase_it = player_setup_it;
space

2017-02-15 18:53 UTC, o01eg commented
Rebased. Fixed style.

2017-02-15 19:35 UTC, geoffthemedio commented on server/ServerFSM.cpp
>          std::set<std::string> validNames(empire_names.begin(), empire_names.end());
rename to `valid_names`

2017-02-15 19:35 UTC, geoffthemedio commented on server/ServerFSM.cpp
>          static std::vector<std::string> empire_names = UserStringList("EMPIRE_NAMES");
will presumably never refill names list, even if some/all are used by players who then leave the game...

2017-02-15 19:35 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +            m_lobby_data->m_ai_aggr     =    incoming_lobby_data.m_ai_aggr;
weird = placement

2017-02-15 20:57 UTC, o01eg commented
Rebased. Fix empire_names and "=".

2017-02-16 10:51 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +        while (player_name.compare(0, ai_prefix.size(), ai_prefix) == 0)
Is this all safe if either string is or becomes empty?

2017-02-16 10:51 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +    while (t < 200 && collision) { // It should be enough
Could perhaps try as many times as there are players in the lobby + 1 ?

2017-02-16 10:51 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +#ifndef FREEORION_MACOSX
Is there a consequence to doing this on all platforms?

2017-02-16 10:51 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +            if (i_player.first == message.SendingPlayer()) {
Could perhaps reduce the degree of indenting here using `if (!test) continue;` instead of `if (test) {}`

2017-02-16 18:35 UTC, o01eg commented on server/ServerFSM.cpp
> +#ifndef FREEORION_MACOSX
It was introduced here 2b48e33349db5a so I unsure about this code.

2017-02-16 20:38 UTC, geoffthemedio commented on server/ServerFSM.cpp
> +#ifndef FREEORION_MACOSX
ok, disregard the comment then

2017-02-16 20:51 UTC, o01eg commented
Fixed possible empty name, indent with `continue` and try number.

2017-02-16 21:51 UTC, merged

2017-02-17 14:32 UTC, Vezzra commented on server/ServerFSM.cpp
> +#ifndef FREEORION_MACOSX
2b48e33349db5a7d02ff48ea821bfa642c6e764e is a fix for a very weird crash I put in. I *think* I vaguely remember that the crash turned up again soon after I committed that fix, and ultimately turned out to be caused by something completely different (don't ask me what, it's too long ago).

Apparently I forgot to check if my fix could be safely undone now, but that should probably be done at some point.