[python] Cleanup game scripts
freeorion/freeorion pull request #1335
Opened 2017-02-17 23:21 UTC by Cjkjvfnby

This is massive style cleanup for python code.  It is preparation for #1296

I use [pycodestyle](https://pypi.python.org/pypi/pycodestyle) for checks:  

`pycodestyle . --ignore=E501,E402,E226,E722`

- `E226 missing whitespace around arithmetic operator`(asymmetrical number of  whitespaces around operators, this is freeorion code style, approved by @Dilvish-fo, also it is in default ignore list of tool)
- `E402 module level import not at top of file`  will fix later, I expect conflicts with logging branch
- `E501 line too long (87 > 79 characters)` too many of them
- `E722 do not use bare except'`  will fix this in different branch

Result:
- one false-positive item (`E305 expected 2 blank lines after class or function definition, found 1`)
- multiple occurrence in mock generation (will fix in separate PR)

2017-02-18 00:09 UTC, Morlic-fo requested changes
I disagree with breaking of the alignment in the content-definition files.

Readability > PEP8 standard in this case especially as those parts should be (relatively) intuitively editable for non-coders.

2017-02-18 00:09 UTC, Morlic-fo commented on default/python/AI/character/character_module.py
> +    bypassed_empire_id = get_trait_bypass_value("empire-id", empire_id, no_value)
Why?

2017-02-18 00:09 UTC, Morlic-fo commented on default/python/universe_generation/universe_tables.py
> +    fo.galaxySetupOption.high: (-20, -10, 0, 10, 20, 20, 20, 20),
For these and below, see previous comment on table / content definition.

2017-02-18 00:09 UTC, Morlic-fo commented on default/python/AI/AIDependencies.py
> +    "GREAT": {},
also all of there and above

2017-02-18 00:14 UTC, MatGB commented on default/python/AI/AIDependencies.py
> +    "CON_ORBITAL_HAB": [0, 1, 1, 1, 1],
I agree with this: dependencies needs to be completely accessible for non coders, it's set out as a readable table to let scripters like me make amendments easily.

2017-02-18 02:20 UTC, Dilvish-fo commented on default/python/AI/AIDependencies.py
> +    "CON_ORBITAL_HAB": [0, 1, 1, 1, 1],
I myself do have a tendency to align things (and probably created the aligned table in question above), and in cases where there is some notable need to compare within columns across rows, then I might argue in support of such alignment.  In this kind of case, though, I have become persuaded that to the extent the previous version seems 'clearer' or 'cleaner', it is really a more abstract 'prettiness' being contemplated and not actual readability of the given lines. 

This kind of issue is a common point of contention, and even within the pycodestyle community there seems to be a lot of [argument](https://github.com/PyCQA/pycodestyle/issues/381) about how much support should be provided for selectively disabling individual pep8 rules on a line-by-line or file-by-file basis.  

So, to the extent our tools support it, we could consider disabling certain checks for certain parts of code (but should really really minimize any such practice).   For the most part, though, I see a lot of benefit to following the standard in a straightforward fashion.  And so far, in the instances pointed to here, I am not convinced of any significant value to not following PEP8.

2017-02-18 02:34 UTC, Dilvish-fo commented on default/python/AI/ColonisationAI.py
> +    result = 3 * (0.1 + net_count) * (1 + regen_count / 3.0) * (1 + garrison_count / 6.0) * (1 + shield_count / 3.0)
This is a case where I think the original code probably meets PEP8 *better* than the code proposed here does.

> If operators with different priorities are used, consider adding whitespace around the operators with the lowest priority(ies).
Yes:
x = x*2 - 1
No:
x = x * 2 - 1

But it is probably the " * " between the parentheses that is throwing off the tool.  CJ, pycodestyle would support a # noqa directive being added to this line, wouldn't it?  Do the Travis pep8 checks also support that?

2017-02-18 02:34 UTC, Dilvish-fo commented on default/python/AI/InvasionAI.py
> +        troop_cost = math.ceil(planned_troops / 6.0) * (20 * (1 + foAI.foAIstate.shipCount*AIDependencies.SHIP_UPKEEP))
I am not seeing anything inconsistent here.

2017-02-18 03:20 UTC, Dilvish-fo commented on default/python/AI/AIDependencies.py
> +    "CON_ORBITAL_HAB": [0, 1, 1, 1, 1],
Ah, now I just got down to seeing that this PR also has changes to universe_tables.py  -- the tables there are exactly the kind of situation where it is very important to be able to compare within columns across rows, and so I think we should either exclude it entirely from the PEP8 review or at least bypass the whitespace/alignment rules for it.

2017-02-18 09:12 UTC, Morlic-fo commented on default/python/AI/InvasionAI.py
> +        troop_cost = math.ceil(planned_troops / 6.0) * (20 * (1 + foAI.foAIstate.shipCount*AIDependencies.SHIP_UPKEEP))
In this line there is whitespace introduced: ```planned_troops / 6.0```.  In the line above there is not: ```planned_troops/6.0```

2017-02-18 09:33 UTC, Cjkjvfnby commented on default/python/AI/AIDependencies.py
> +    "GRO_SYMBIOTIC_BIO": [0, 0, 0, -1, -1],
xor?

2017-02-18 09:35 UTC, Cjkjvfnby commented on default/python/AI/ColonisationAI.py
> +    result = 3 * (0.1 + net_count) * (1 + regen_count / 3.0) * (1 + garrison_count / 6.0) * (1 + shield_count / 3.0)
Ignoring E226 will allow to pass test for old code in travis.   Will revert this change.

2017-02-18 09:36 UTC, Cjkjvfnby commented on default/python/AI/character/character_module.py
> +    bypassed_empire_id = get_trait_bypass_value("empire-id", empire_id, no_value)
it is local variable, only module level constants should be in capitals.

2017-02-18 10:04 UTC, Cjkjvfnby commented
I revert formatting for "tables".  Unfortunately I don't know how to run  `pycodestyle` in windows shell to skip exactly these files. These files need a special set of errors to ignore, that should not be applied to other code.

Fix other comments.

2017-02-18 10:53 UTC, Morlic-fo commented
> I revert formatting for "tables". Unfortunately I don't know how to run pycodestyle in windows shell to skip exactly these files. These files need a special set of errors to ignore, that should not be applied to other code.

Just skimmed the documentation.

How about running it twice:
1. use ```--exclude``` to ignore AIDependencies.py and universe_tables.py and check for all errors
2. Run it for these 2 files with some checks disabled.

2017-02-18 12:38 UTC, adrianbroher commented
What's the point of using `pycodestyle`?

`pep8` is the tool that you talked about in #1296 and that I invested time in so far.  Why do you waste my time?

2017-02-18 14:42 UTC, Cjkjvfnby commented
@adrianbroher, sorry I forgot to mention about this, pep8 tool was renamed to pycodestyle.  Release of pep8 in pypi is not maintained anymore.  I just found this when start to add description to this PR.

2017-02-19 12:03 UTC, Vezzra commented on default/python/universe_generation/monsters.py
> +                                (fp not in fleet_can_alter_starlanes or starlane_altering_monsters.can_place_at(system, fp))]
Just curious: does the original formatting really violate PEP8? Because, honestly, I think the original formatting is much more readable...

2017-08-02 12:00 UTC, geoffthemedio commented
bump?

2017-08-06 11:19 UTC, Cjkjvfnby commented
> bump?

No, will redone it in small chunks.

2017-08-06 11:19 UTC, closed without merging

2017-08-11 15:16 UTC, Vezzra commented
@Cjkjvfnby, I've tagged this issue as "follow-up", can you post references here to the PRs which replace this one?

2017-08-14 22:18 UTC, Cjkjvfnby commented
> can you post references here to the PRs which replace this one

May be I should reference them to issue #1296? 

Next stage:  #1673

2017-08-18 15:44 UTC, Vezzra commented
A reference to the issue is already in the OP, so no need to post it again. If I understand correctly, you've closed this PR because you split it up into several smaller ones, so it would be good to just post references here to all these PRs which replace this one.