Replace Cpp Api content tag filter with parser script
freeorion/freeorion pull request #1364
Opened 2017-02-24 05:56 UTC by dbenage-cx

Parses python and focs files and creates `all_tags.dox`

The description for content tags are allowed to span multiple lines as well as multiple instances for the same tag.

Resolves #1319

2017-02-24 08:55 UTC, adrianbroher requested changes

2017-02-24 08:55 UTC, adrianbroher commented on doc/CMakeLists.txt
> +    add_custom_target(cpp-apidoc-content-tags
add_custom_target allows multiple COMMAND statements so there is no need for an explicit `cpp-apidoc-content-tags` target but instead you can add the execution statement as the first COMMAND to the cpp-apidoc target. 

https://cmake.org/cmake/help/v3.1/command/add_custom_target.html

2017-02-24 08:55 UTC, adrianbroher commented on doc/tag_parser.py
> +base_link_url = 'https://github.com/freeorion/freeorion/blob/master/'
This breaks local generations of the documentation.  Why don't you use internal linking?

2017-02-24 08:55 UTC, adrianbroher commented on doc/tag_parser.py
> +file_masks = {'*.py', '*.focs.txt', '*.macros'}
The source directories should be application parameters.

2017-02-24 08:55 UTC, adrianbroher commented on doc/tag_parser.py
> +exclude_masks = {'__*'}
The exclude masks should be application parameters.

2017-02-24 08:55 UTC, adrianbroher commented on doc/tag_parser.py
> +dox_target = os.path.join(doc_dir, 'all_tags.dox')
The output file should be an application parameter.  Otherwise you write into the source tree, which hinders the use of multiple build trees.

2017-02-24 08:55 UTC, adrianbroher commented on doc/tag_parser.py
> +class SourceInfo(object):
A tuple is sufficient as a substitute.

2017-02-24 08:55 UTC, adrianbroher commented on doc/tag_parser.py
> +    def __repr__(self):
Wrong use of `__repr__`.

https://docs.python.org/2/library/functions.html#repr

2017-02-24 08:55 UTC, adrianbroher commented on doc/tag_parser.py
> +class TagDescription(object):
Again I think a tuple should be sufficient as substitute for this.

2017-02-24 08:55 UTC, adrianbroher commented on doc/tag_parser.py
> +        for parse_line in f:
`enumerate` should make the intent a bit more clear:

https://docs.python.org/2/library/functions.html#enumerate

2017-02-24 08:55 UTC, adrianbroher commented on doc/tag_parser.py
> +            if parse_line.lstrip().startswith("#"):
To be honest, I have no idea what is happening here (and the following lines) at first glance.  Do you collect multiline comments?

2017-02-24 09:35 UTC, dbenage-cx commented on doc/tag_parser.py
> +            if parse_line.lstrip().startswith("#"):
TY for review and helpful notes.

Yes, the variables are stored locally and moved/copied once an end condition is met (eof, non-comment line, new tag line).
If the next line is a comment line, it is assumed part of the tag description.  Mainly this is to allow pep8 compliance for line length and not hinder the description.  I will try to clarify this section as I work on other changes.

2017-02-24 09:38 UTC, dbenage-cx commented on doc/tag_parser.py
> +base_link_url = 'https://github.com/freeorion/freeorion/blob/master/'
The links for python/focs files would not exist on the `.io` site?  Will look into alternative.

2017-02-24 10:42 UTC, adrianbroher commented on doc/tag_parser.py
> +base_link_url = 'https://github.com/freeorion/freeorion/blob/master/'
> The links for python/focs files would not exist on the .io site?

Well okay.  Now I get your idea.  The documentation nowhere points to the source code.  Why should it in this case?

2017-03-03 06:46 UTC, dbenage-cx commented on doc/tag_parser.py
> +        for parse_line in f:
Fixed

2017-03-03 06:46 UTC, dbenage-cx commented on doc/tag_parser.py
> +    def __repr__(self):
Removed

2017-03-03 06:46 UTC, dbenage-cx commented on doc/tag_parser.py
> +class TagDescription(object):
Fixed

2017-03-03 06:46 UTC, dbenage-cx commented on doc/tag_parser.py
> +class SourceInfo(object):
Removed

2017-03-03 06:46 UTC, dbenage-cx commented on doc/tag_parser.py
> +base_link_url = 'https://github.com/freeorion/freeorion/blob/master/'
I've left in a link to github source, supporting the target being changed or link completely removed if either are requested.

I think some context can be helpful when looking at tags, especially if the documentation is too concise or there are multiple sources of documentation for a single tag.
With FOCS definitions there is no context to follow without pulling in the freeorion parser.
Python could arguably use the containing function/module, though I don't see any benefit over a name/line#.

2017-03-03 06:46 UTC, dbenage-cx commented on doc/tag_parser.py
> +dox_target = os.path.join(doc_dir, 'all_tags.dox')
Fixed, moved target to build dir

2017-03-03 06:47 UTC, dbenage-cx commented on doc/tag_parser.py
> +exclude_masks = {'__*'}
Fixed

2017-03-03 06:47 UTC, dbenage-cx commented on doc/tag_parser.py
> +file_masks = {'*.py', '*.focs.txt', '*.macros'}
Fixed

2017-03-03 06:47 UTC, dbenage-cx commented on doc/CMakeLists.txt
> +    add_custom_target(cpp-apidoc-content-tags
Fixed, though requires `&&` to not append doxygen command as an argument to script.
Not certain if you prefer these arguments as specific cmake variables, so I simply appended for now.

2017-03-07 08:22 UTC, adrianbroher approved these changes

2017-03-07 08:22 UTC, adrianbroher commented
Looks good to me.

2017-03-07 08:23 UTC, merged

2017-03-07 09:35 UTC, dbenage-cx commented
TY for review and assistance.

2017-03-08 10:41 UTC, Vezzra commented
@adrianbroher, same question as in #1319: why assigning this to a milestone? Has no relevance/impact on a release...