Some cleanup
freeorion/freeorion pull request #1438
Opened 2017-03-24 23:16 UTC by Morlic-fo

- Mostly converting some dicts that were used like sets to actual sets.
- Remove some redundant / unused variables
- fix some PEP8 naming style violations
- minor code simplifications

Should be squashed before merge but leaving history as is for easier review.

Tagging this as optional for 0.4.7 as it shouldn't be release blocking but the changes in AIstate break save compatibility as usual so I would strongly prefer to merge this before 0.4.7 (so we can actually use 0.4.7 saves in master for a little while...)

2017-04-02 02:49 UTC, Dilvish-fo commented on default/python/AI/AIstate.py
> +        self.__origin_home_system_id = homeworld and homeworld.systemID or INVALID_ID
this does not work correctly if the homeworld.systemID is 0

but if you want a one-liner I suppose the  = if else
kind of structure could work.

2017-04-02 02:57 UTC, Dilvish-fo commented
Hmm, github is apparently hiding my comment as being for an outdated commit, but it looks to me like the line I commented on appears the same as the one I commented on in the overall changes, so please be sure to check it.

2017-04-02 02:57 UTC, Dilvish-fo requested changes
per previous comment

2017-04-02 03:31 UTC, Dilvish-fo commented
> but the changes in AIstate break save compatibility as usual

Changes to AIstate do not need to break save compatibility; at least, backwards compatibility can be preserved, by providing an ```AIstate.__setstate__``` method to make any necessary adjustments during the unpickling process, and I ***very much*** prefer to preserve backwards compatibility for at least a while after any change, it is often quite helpful for people to be able to test out the change with respect to an existing save file.

At one point we hadn't had any such compatibility issues for a while, though, and the method that deals with such things was stripped out in #414.  I had considered leaving a skeleton method with comments in place, but wound up just putting in a [note on the wiki](http://freeorion.org/index.php/Python_Development#AI_state_in_save_file).

2017-04-03 19:17 UTC, Morlic-fo commented
> Changes to AIstate do not need to break save compatibility; at least, backwards compatibility can be preserved, by providing an AIstate.__setstate__ method to make any necessary adjustments during the unpickling process, and I very much prefer to preserve backwards compatibility for at least a while after any change, it is often quite helpful for people to be able to test out the change with respect to an existing save file.

Right. No reason to do this before 0.4.7

2017-05-16 23:39 UTC, Dilvish-fo commented
So, what do you say, would you add the AIstate.setstate handling so that this need not break savegame compatibility?  It would be nice to get this one merged and out of the way.

2017-05-17 07:02 UTC, Morlic-fo commented
Thanks for the reminder. Yes, I will update this PR some time this weekend.

2017-05-24 19:02 UTC, Morlic-fo commented
How do you want to handle compatibility across multiple revisions of the AIState?

My idea would be to add a version number as class attribute and do something like
```
class AIState():
    def __setstate__(self, state):
        for i in range(state.version, AIState.version):
            convert_to_version(state, i+1)
    self.__dict__ = state

...

def convert_to_version(state, version):
    if state["version"] >= version:
        return
    if version == 1:
        state["new_member"] = some_default_value
        del state["old_member"]
    elif version == 2:
        ....
    state["version"] = version
```

Any other preference?

2017-05-24 20:43 UTC, Morlic-fo commented
> My idea would be to add a version number as class attribute

Relevant PR: #1584

2017-05-25 23:10 UTC, Dilvish-fo approved these changes

2017-05-25 23:11 UTC, Dilvish-fo commented
the compatibility version idea sounds fine; I've made some other comments in that PR.

2017-05-25 23:13 UTC, Dilvish-fo commented
It just sunk in that the approval was perhaps slightly premature, since you hadn't actually added the conversion here yet, so just take this as a reminder to do that before merging.

2017-06-05 16:28 UTC, Vezzra commented
@Morlic-fo, @Dilvish-fo, anything preventing this from being merged?

2017-06-08 19:05 UTC, Morlic-fo commented
Rebased and added the code for savegame compatibility.

Ready to merge from my side. Feel free to merge @Dilvish-fo  if you have no new concerns.

2017-06-14 03:47 UTC, merged