Move Phototrophic effects evaluate after all other effects
freeorion/freeorion pull request #1615
Opened 2017-06-25 10:07 UTC by Morlic-fo

Because the phototrophic effect activates only with a target population
greater than zero, it depends on the order of effect evaluations that
modify the target population.

Prior to this PR, there were effects that modify the target population
with the same priority as the phototrophic trait which is ill-defined
behavior.

This PR adresses the issue by ensuring that the Phototrophic trait is always evaluated after all other effects where applied.

2017-06-25 10:19 UTC, MatGB commented
OK, appears I must've messed this up a bit when I set the priorities, glad we've caught it. Very Late was supposed to be just growth specials or self-sustaining/phototroph stuff so in theory it wouldn't clash.

Also, I had meant and thought I had removed all the population > 0 effects, they never worked properly anyway, but if this fixes it we're good.

2017-06-25 12:26 UTC, Morlic-fo commented
I am not sure if this actually fixes anything or if the previous implementation happened to get the same results by relying on some implicit order of effect evaluation.

This is mostly an observation from reading the scripts and without test cases.

2017-06-25 18:25 UTC, dbenage-cx requested changes

2017-06-25 18:25 UTC, dbenage-cx commented on default/scripting/common/priorities.macros
> +'''99999'''
add newline

2017-06-25 18:43 UTC, dbenage-cx approved these changes

2017-06-25 18:44 UTC, Morlic-fo commented on default/scripting/common/priorities.macros
> +'''99999'''
Fixed.

2017-06-25 18:47 UTC, dbenage-cx commented on default/scripting/common/priorities.macros
> +'''99999'''
Was too hasty clicking approved, looks like other file has the added EOL but not this one (or browser is not updating)

2017-07-20 09:53 UTC, geoffthemedio commented
@MatGB @Morlic-fo any further concerns / comments?

2017-07-20 10:17 UTC, MatGB commented
Nope, LGTM

2017-07-21 00:49 UTC, dbenage-cx commented
Not had time to test, otherwise LGTM

2017-07-25 11:54 UTC, merged