Add instructions to edit premade designs to scripting README files.
freeorion/freeorion pull request #1617
Opened 2017-06-28 13:14 UTC by LGM-Doyle

2017-06-29 10:29 UTC, geoffthemedio commented on default/scripting/monster_designs/README.md
> +1. Move or backup the `shipdesigns` directory in your freeorion data directory.
where is the "freeorion data directory" ?

2017-06-29 10:30 UTC, geoffthemedio commented on default/scripting/monster_designs/README.md
> +data directory and replace your `shipdesigns` directory.
"and replace", or "replacing" or "in place of" ?

2017-06-29 10:31 UTC, geoffthemedio commented on default/scripting/monster_designs/README.md
> +    iii. If you use a stringtable index for **both** the ship name **and** description then it will save the stringtable index and use the translated text for display.  You can check this in the pedi
explain how to use a stringtable index?

2017-06-29 10:31 UTC, geoffthemedio commented on default/scripting/monster_designs/README.md
> +6. Copy the `shipdesigns` directory from your data directory back into the `default/scripting/ship_designs` or `default/scripting/monsters` directory.
does one need to copy the directory, or just its contents?

2017-06-29 18:03 UTC, LGM-Doyle reviewed
Changes made.

2017-06-30 12:23 UTC, geoffthemedio commented on default/scripting/monster_designs/README.md
> +6. Copy the `shipdesigns` directory from your data directory back into the `default/scripting/ship_designs` or `default/scripting/monsters` directory.
Because someone reading it may be confused about what they need to do.

2017-06-30 12:52 UTC, Vezzra commented
As these additions are essentially documentation, this should either be tagged as "user manual" or "technical docs". Not 100% sure which applies here, for now I'm going with "technical docs".

Any opinons/objections? @geoffthemedio, @LGM-Doyle, @adrianbroher?

2017-06-30 13:03 UTC, MatGB commented
I thought user manual was in game Pedia and technical docs was anything else but especially how to change things but I might be wrong.

2017-06-30 15:23 UTC, LGM-Doyle commented
"technical docs" seems reasonable to me.

2017-06-30 21:20 UTC, dbenage-cx requested changes

2017-06-30 21:20 UTC, dbenage-cx commented on README.md
> +`Username/Library/Application Support/FreeOrion/`
Replace `Username` with `$HOME` (or as previous "...which defaults to...") https://github.com/freeorion/freeorion/blob/master/util/Directories.cpp#L87 (and same with data dir)

2017-06-30 21:20 UTC, dbenage-cx commented on README.md
> +`C:\Users\Username\AppData\Roaming\FreeOrion`
similar: `$APPDATA\FreeOrion` https://github.com/freeorion/freeorion/blob/master/util/Directories.cpp#L374 (and same with data dir)

2017-06-30 21:20 UTC, dbenage-cx commented on README.md
> +    `<install_dir>/default/stringtables/`
Possibly define as use `resource directory` for these, in event a packager relocates the default resource directory.

2017-07-01 14:06 UTC, LGM-Doyle reviewed
I've fixed all of the issues. 

Thanks for the comment.

2017-07-01 14:06 UTC, LGM-Doyle commented on README.md
> +`Username/Library/Application Support/FreeOrion/`
Done.

2017-07-01 14:06 UTC, LGM-Doyle commented on README.md
> +`C:\Users\Username\AppData\Roaming\FreeOrion`
Done

2017-07-01 14:06 UTC, LGM-Doyle commented on README.md
> +    `<install_dir>/default/stringtables/`
I added the resource directory with a comment that it can be relocated in `config.xml` or `persistent_config.xml`

2017-07-01 15:00 UTC, dbenage-cx approved these changes

2017-07-02 10:50 UTC, MatGB commented
Before I open an issue, playing a new game from last night compiled from master at a4f1548, the only thing I've done is follow these instructions to reorder the premade designs.

On loading, none of my empire designs are there to build, not originals, not saved designs, not premades. I've tried saving and reloading, and even designs I put in aren't there. However, if I try to create a new design it won't let me add a duplicate of something that ought to be there (eg a basic outpost ship with medium hull and outpost). This is beyond frustrating, could it be because I reorderd the premades or is it a bigger bug?

As a workaround I've put the important premades into my saved designs, I can 'add all saved designs' whenever I reload, but that shouldn't happen.

2017-07-02 13:22 UTC, LGM-Doyle commented
@MatGB I ran into that same bug and fixed it yesterday in https://github.com/freeorion/freeorion/commit/f0d71bd8f82e6ec568de821c012b633409b26bda

I made changes late in the process of PR #1587 to support legacy loading, which broke regular loading.  I removed those changes.

2017-07-08 20:54 UTC, merged