Ai focus dithering fix
freeorion/freeorion pull request #1773
Opened 2017-09-30 07:39 UTC by Dilvish-fo

As discussed in #1766, AI Focus dithering (short term swaps between Research and Industry Focus), is currently underperforming because of a bug that causes the research phase of focus dithering to be cut short too soon.  In addition to fixing that bug, this PR restructures and clarifies the dither code.  I am also working on some further improvements I had mentioned in #1766, but those are taking some more time and I wanted to at least get this primary fix and clarification in for review right away.

2017-09-30 09:27 UTC, Morlic-fo requested changes
Thanks for the clarifying comments.

A top-level comment explaining what research dithering actually is and how it works is still missing. There are some comments about it spread throughout the other comments but a clear introductory comment would be good.

2017-09-30 09:27 UTC, Morlic-fo commented on default/python/AI/ResourcesAI.py
> +                # RP at a good PP cost, and still need some RP, then consider doing it.
I would really like an introductory comment that explains what "research dithering" actually is supposed to do: Abuse the fact that meters fall only by the same rate that they grow. So the fundamental idea is to grow to the research target to maximum while the PP meter is still above its target value at research focus target. 

Also, some explicit math wouldn't hurt. Something like
```
Assuming we switch to a research focus for n turns with a focus penalty of p and assuming integer values of Research(R) and Industry(I) only:

R = {sum(i), i=1..n}  = n(n+1)/2
I = {-sum(i+p), i=1..n} = -n(n+1+2p)/2

Growing up again until industry meter maximum, we need (n+p) turns.
R = {sum(i), i = 0..n-p-1} = (n-p-1)(n-p)/2
I = {-sum(i), i = 1..n+p-1} = (n+p-1)(n+p)/2

Adding both, we have
R = n^2 - np + p^2 / 2 + p/2
I = - (n^2 + 2np +p^2/2 -p/2)

With current p = 1 this yields
R = 1 + n(n-1)
I = - n(n+2)
or a cost ratio of -I/R = n(n+2) / (1+n(n-1))

For example, a cycle consisting of switching 5 turns to research yields (n=5)
R = 21
I = -35
or a cost of ~1.67 PP per RP
```

2017-09-30 09:27 UTC, Morlic-fo commented on default/python/AI/ResourcesAI.py
> +                # changed to Industry (currently allowed to be handled by standed focus code later).  The research_caped
typos: ```standard```, ```capped```

2017-09-30 09:37 UTC, Morlic-fo commented
Somehow didn't get into my review message but the fix seems to work on first sight. In my previous test case where the AI did those 1-turn dithers now performs a full 5 turn cycle.

2017-10-29 13:49 UTC, Vezzra commented
@Dilvish-fo, @Morlic-fo, progress report on this? Anything preventing it from being merged?

2017-10-31 07:58 UTC, Morlic-fo commented
The actual fix works so if @Dilvish-fo rebases I am fine with merging this as is and fix the comment/style post-merge if time does not allow more thorough revision.

Needs a rebase though.

2017-11-02 19:38 UTC, Dilvish-fo commented
Heyas, I've just been very very busy for a while now, but it certainly has been on my mind to get back to this.  There was still a fair bit more I had wanted to do with it, but perhaps I'll just make a reminder for myself to cover the further improvements so that this fix can get in more promptly.  Consider me nudged  :smile:

2017-11-04 07:15 UTC, Dilvish-fo commented
OK, I've rebased this, and also addressed a few more of the suggestions (some additional/clearer comments, AIDependencies, character trait).  I still have some plans to do some more substantive work on this, but I'll see how the time goes, perhaps I'll just leave that for a later PR.

2017-11-14 19:16 UTC, Morlic-fo approved these changes

2017-11-16 12:15 UTC, Vezzra commented
> I still have some plans to do some more substantive work on this, but I'll see how the time goes, perhaps I'll just leave that for a later PR.

Seeing as this is flagged as mandatory for the release, preferrably it should get merged rather sooner than later. So, leaving more substantive work for a later PR and merging this now sounds good to me.

2017-11-16 20:18 UTC, merged