Have ai not honor bad colony buildings
freeorion/freeorion pull request #1955
Opened 2018-01-21 21:16 UTC by Dilvish-fo

When the AI is considering building colony buildings at outposts, it currently first eliminates from consideration all outposts where one is already under construction.

Sometimes the AI will have invaded & acquired a planet that has a colony building under construction but which the AI does not have the requisite colonizer species, and so currently that leaves the planet tied up as an outpost even if the AI has another good colonizer for it.  And sometimes the AI loses a planet providing a key colonizer while it has colony buildings underway.  

In the future we'll probably want to do a more involved projection (in all cases) about when colonizers might become available, but in the meantime, don't lockdown a planet with an incomplete colony building that the AI can't currently build.

Also, somewhat independent but just related enough that I'm including it here, the second commit prevents the AI from squandering its allotment of colony targets considering places that already have a colony building just-completed.

2018-01-22 19:41 UTC, Morlic-fo requested changes
Besides some code-nitpicking, make sure to double check the possible bug in empire_has_colony_bld_species()

The general idea looks good.

2018-01-22 19:41 UTC, Morlic-fo commented on default/python/AI/ProductionAI.py
> +    species_name = 'SP' + building_name.split('BLD_COL_')[1]
Is this correct? On first sight looks like it should be ```"SP_" + ...```, i.e. currently missing an underscore?

2018-01-22 19:41 UTC, Morlic-fo commented on default/python/AI/ProductionAI.py
> +               [universe.getBuilding(bldg).name for bldg in planet.buildingIDs]])
Seems the two list comprehensions can be combined?

```any(universe.getBuilding(bldg).name.startswith('BLD_COL_') for bldg in planet.buildingIDs)```

2018-01-22 19:41 UTC, Morlic-fo commented on default/python/AI/ProductionAI.py
> +def empire_has_colony_bld_species(building_name):
Short docstring?

2018-01-22 19:41 UTC, Morlic-fo commented on default/python/AI/ProductionAI.py
> +def already_has_completed_colony_building(planet_id):
Short docstring?

2018-01-22 19:41 UTC, Morlic-fo commented on default/python/AI/ProductionAI.py
> +                                not already_has_completed_colony_building(entry[0])]
Precedes this PR but should probably unpack the entry tuple into descriptive names rather than using cryptic indexing...

2018-01-23 16:05 UTC, Dilvish-fo commented
Good suggestions there, and a great catch on the species name.  I had tested focused on making sure it was not honoring bad colony buildings, and since failure to honor the good ones nearly always would just mean that it would try (and fail) to re-enqueue the same good one that was already under construction, it hadn't been obvious during game play.

I'll follow up soon with adjustments.

2018-01-29 09:26 UTC, merged