fix some MilitaryAI calculations
freeorion/freeorion pull request #2178
Opened 2018-06-24 17:46 UTC by Dilvish-fo

There are still a few places where the MilitaryAI has been using simple addition and subtraction for assessing fleet rating combinations and differences, even though we have had specialized (more accurate) calculations for those in the CombatRatingsAI for some time now.

This PR cleans up those lingering inaccurate uses of plain addition and subtraction.

@Morlic-fo in addition to your substantive review could you give your assessment of suitability to include in 0.4.8?

2018-06-24 20:13 UTC, Cjkjvfnby submitted a review, later dismissed

2018-06-24 20:13 UTC, Cjkjvfnby commented on default/python/AI/CombatRatingsAI.py
> +    """Estimate the rating of an additional force rating needed to be added to the lesser of the given ratings
It takes me some time and checks other code, to understand what this function does.  Docstring is not helpful.

maybe something like that: 

`Return absolute difference between ratings. Keep in mind that rating is not the linear function.`

2018-06-25 16:49 UTC, Morlic-fo commented
I remember us having some discussion about this some time ago where the conclusion was not to use the CombatRatings functions here ( I think it was you coming up with a good reason for that). I am not exactly sure when that discussion took place and couldn't find it during a quick search.

I think the argument was based on the fact that the quadratic formula for adding combat ratings is only valid if the fleets are actually all in the same system/mission. However, as we (might) assign single ships here to many different missions/systems, the linear approach would be more suitable to estimate how much rating is left... Not sure if I am missing some other aspect, this is rather wishy-washy and not convincing. Maybe you remember? Or maybe I am just imagining things and the discussion never happened which would explain why I can not find it now...

2018-06-25 19:04 UTC, Dilvish-fo commented
I am not really recalling those conversations, but I am still a bit fuzzy-headed from this sinus infection or bad allergy flare-up that I've been experiencing this past week.  It's most likely you are remembering correctly, but if so, my thinking has changed.   And perhaps we had that conversation at a time when we had the combat ratings formula for combining ratings, but had not yet worked out a satisfactory formula for calculating ratings differences.  Using the CombatRatings formula for aggregation but then using simple subtraction for splitting off smaller forces would lead to a serious overestimation of remaining available forces.

The CombatRatings assessment gives the best assessment of the total rating the AI could summon to a single battle, which I feel pretty confident is the best number for the AI to start off considering (especially as it now uses that same max assessment to decide if conquest options are perhaps bigger than it wants to bite off at the moment), and then as it splits off forces for smaller battles it would need to adjust that tally down by also using the CombatRatings calculations.

2018-06-25 19:40 UTC, Morlic-fo commented
I do not understand why you define and use the ```rating_difference``` function here instead of using the ```rating_needed``` function.

If we start with a given remaining_rating which is smaller than the allocation performed, then after the allocation, the remaining rating should be zero. Which is exactly what ```rating_needed``` calculates. However, your function basically calculates the equivalent of abs(x - y) - why is that?

2018-06-25 20:43 UTC, Dilvish-fo commented
> I do not understand why you define and use the rating_difference function here instead of using the rating_needed function.

Well, I tried to explain it in the commit message-- the way we are using this is to determine a 'rating remaining', not really a 'rating needed', so although the math is the same I thought it would be more clear to access this calculation via a function which which explicitly determines a rating difference, and whose tooltips will be more applicable.

The choice of making this more general, allowing the two forces to be specified in either order, versus a more specific one requiring that the larger force be specified first, is not one that matters a lot to me.  It seemed to make more sense to me like this, but if you would prefer to require that the larger force be specified first, that would be ok with me.  

Then we have less of a reason to have both functions, and perhaps simply rename rating_needed to be rating_difference.  Or we could leave the additional function to have more specific tooltips.   This week though, in particular, I am both pressed for time and not feeling well, and not much wanting to try to decide an appropriate error handling to go with a a revised structure.  I'd rather put the structure through as is, and just agree that you are free to restructure it to specifically require a particular order of the arguments (or just eliminate the additional method) if that continues to seem best to you.  Or you could just put in a different PR to supersede this, is OK with me also.  But I'd like to have something equivalent to this get merged in time for RC2.

2018-06-25 21:06 UTC, Morlic-fo commented
My issue with your new function is not based on code style but seemingly incorrect maths. 

Consider the following extreme case:
```
remaining_rating = 0
min_rating = 100
remaining_rating = rating_difference(remaining_rating, min_rating)
print remaining_rating  # 100
```
That is certainly a very different result from the previous ```remaining_rating -= min_rating```.

2018-06-25 21:32 UTC, Morlic-fo submitted a review, later dismissed
For emphasis, see previous discussion

2018-06-25 21:32 UTC, Morlic-fo commented on default/python/AI/MilitaryAI.py
> +        self._remaining_rating = rating_difference(self._remaining_rating,  min_rating)
Maths changed here from ```x = x - y``` to what is basically ``` x = abs(x - y)```

2018-06-25 21:32 UTC, Morlic-fo commented on default/python/AI/MilitaryAI.py
> +            remaining_mil_rating = rating_difference(remaining_mil_rating,  this_alloc)
Maths changed here from ```x = x - y``` to what is basically ``` x = abs(x - y)```

2018-06-25 21:32 UTC, Morlic-fo commented on default/python/AI/MilitaryAI.py
> +            remaining_mil_rating = rating_difference(remaining_mil_rating,  alloc)
Maths changed here from ```x = x - y``` to what is basically ``` x = abs(x - y)```

2018-06-25 21:32 UTC, Morlic-fo commented on default/python/AI/MilitaryAI.py
> +                remaining_mil_rating = rating_difference(local_max_avail, new_rating)
Maths changed here from ```x = x - y``` to what is basically ``` x = abs(x - y)```

2018-06-26 05:13 UTC, Dilvish-fo commented
> That is certainly a very different result from the previous remaining_rating -= min_rating.

?? Actually, it looks to me like you are just citing an issue about the preexisting code structure, the essence of which which is not changed by this PR whatsoever.  And it furthermore looks to me like in two out of the three cases you are ignoring the lines like 
```
this_alloc = min(remaining_mil_rating, max_alloc)
```
which prevents any such problem.  

So I'll add a similar line for the middle case.

2018-06-26 05:47 UTC, Morlic-fo requested changes
> in two out of the three cases

Right, the other case was bugged though as the loop break condition would have never been met. It is a difference if you once allocate a little more than available or do it 100 times more.

Anyway, still one potential bug introduced by your code.

2018-06-26 05:47 UTC, Morlic-fo commented on default/python/AI/MilitaryAI.py
> +        self._remaining_rating = rating_difference(self._remaining_rating,  min_rating)
In this case, there is no check that remaining_rating > min_rating. You rely on external code / calling convention to not break this function which seems like a ticking time bomb.

2018-06-26 07:12 UTC, Dilvish-fo commented
> Right, the other case was bugged though as the loop break condition would have never been met.
  I suppose it can't be met now and is superfluous, but it was possible to have been met before

> Anyway, still one potential bug introduced by your code.

Um, No.  Why do you keep trying to blame this PR for preexisting code issues/constraints/whatever-this-one-is-because-i'm-not-even-sure-I'd-call-it-a-constraint?  

> You rely on external code / calling convention to not break this function which seems like a ticking time bomb.

This PR does not add any reliance that was not already there when you wrote that function in 3dc5c23 (see line 135).

And I hesitate to even confirm that as a 'calling convention'.  You are very much forgetting/misunderstanding how all this works if you characterize that handling as a "ticking time bomb"

All those allocations are really just statements of how much minimum rating the AI should try to assign to this task on down the road; in almost all cases the actual allocation will wind up being slightly greater because the ships that (much later) wind up getting assigned to the task will almost invariably have at least a somewhat greater rating rather than the exactly requested rating.  The whole tracking of remaining rating is very much a rough estimate, and it is highly likely that the allocations that get assigned when the estimated remaining rating is down to a couple or a few ships worth will probably not wind up, at the later stage of actually assigning particular fleets, having any fleets/ships remaining available to get actually assigned to them.

2018-06-26 16:22 UTC, Morlic-fo approved these changes

2018-07-02 02:13 UTC, merged