Translated all races and some other info (ships, monsters and etc).
freeorion/freeorion pull request #2240
Opened 2018-08-02 12:08 UTC by Bestary

Translated ALL races (till the end).
Checked/translated other information (ships, monsters, fleet information).
Checked system messages, menu options.
Translated Production window article (helper about game production). There was syntax error appeared in old version, fixed.
Translated info about stockpiles.
All changes are discussable, hope it's not the last one translate. :)

2018-08-02 12:13 UTC, Bestary commented
Sorry, don't understand why there is conflict... I merged this file with lastest version. :(
(still have problem with Github).

2018-08-02 12:38 UTC, o01eg commented
Looks like you merged wrong branch. You need to merge `master`.

2018-08-02 15:15 UTC, geoffthemedio commented
You should not merge anything; if you've merged master into your branch, the pull request will be rejected. 

You should instead rebase your branch on master.

2018-08-02 17:46 UTC, Dilvish-fo commented
The process I would suggest is as follows (I'll give command line commands, but I strongly recommend a gui like SmartGit to make this sort of thing easier and more reliable)
- first ensure you have your translation branch checked out: ```$ git checkout Russian-Translation```
- then make a backup of your branch, for safety and possible reference: ```$ git branch translation_backup```
- then (if not in GUI) display the first page of commits in the log, to be able to have sha references for the various commits: ```$ git log``` hit the letter `q` to exit from the log display
- hard reset your translation branch to the spot before the test and merge commits that you later revert (i.e, we want 'Edited Mu Ursh short description.'); I'll use the sha indicated here on github, but check that its the same in your log: ```$ git reset --hard 22b7b23```

the Travis log above seems to indicate that those commits have no conflicts, so you might want to restrict this PR to those changes, but you could check if that last good commit is OK also: 
-  cherry pick that last good commit 'All races...' (which is preserved in the backup branch you made): ```$ git cherry-pick e765a29```

read the output there carefully to make sure the cherrypick doesn't get hung up with a conflict, resolve it and finish the cherrypick if it did.

- to update the PR to reflect the cleaned up state so far, just push to your fork ```git push --force```  (you'll need the --force option in this case since you are dropping commits).

If the PR now reports no conflicts, and Travis completes fine, then great.

If either of those problems do happen you should probable do the ```$ git rebase master``` mentioned above, being sure to resolve the conflicts, and then push.

2018-08-02 21:30 UTC, Cjkjvfnby commented
@Bestary , Dilvish-fo instruction looks huge, so it should help :).   

If you will not succeed till Monday evening, I can do it myself,  just give me access to your fork (setting -> Collaborators).

Which tools do you use for GitHub interactions?

2018-08-03 14:28 UTC, Bestary commented
Thanks so much everybody, I'll try to overcome those problems.
Using TortoiseGit now (used GitHub Desktop before, but can't download upstream). Console commands not scaryng me. =)

2018-08-03 16:04 UTC, Bestary commented
Success, no conflicts. ^_^ Thanks so much @Dilvish-fo 's help and one yellow mouse (my other half) he is find also that I merged `master` on my fork but not the my translation branch (it still was on March commits stage). And also thanks to GitHub for another wash of my brain. .-.

2018-08-03 22:19 UTC, Dilvish-fo commented
I'm glad if my instructions helped you, but there is still a problem-- as it shows a little above, with commit 

ddddad4 you again merged the master branch into your feature branch instead of rebasing the feature branch onto current master.  So, the instructions I give above pretty much need to be repeated, and you need to be careful NOT to merge master into your feature branch.   Cj has volunteered to take care of this if you give him access, but I'd be inclined to suggest you stick with it and figure it out so we don't have to go through this more in the future.

The simplest thing might be to use my above instructions for the first three commits, and make this PR be just for them.  Then make a new feature branch based off of current master, apply your last commit to that (clearing up any conflicts) and then make a new PR just for that.

2018-08-05 08:02 UTC, Bestary commented
@Dilvish-fo, thank you so much again. Yes, I want to learn all of this too. That all what I've done:
- trying to rebase master. Thats ok, `master up to date`.
- backup my translation branch again, made another hard reset for this to the last good commit, `pushed --force` it. That's ok.
- `changed files` for this PR still have data of conflicted commit. I don't know, is it normal or not...
- cherry-pick my branch with new commit (`e765a29`, `All races...` etc) from backup. No problems.
- `pushed --force` again. Conflicting files again. :(
Here is the bash log of my actions. (There are no pushing commands, I made it using GUI).

![bash](https://user-images.githubusercontent.com/38672685/43683909-4d0e5894-989e-11e8-989f-94f8179cfc91.png)

I do not mind @Cjkjvfnby helping me if it will still need, but don't know how do give him access, can't find interface for this. :)))))

2018-08-05 08:59 UTC, Dilvish-fo commented
OK, well having looked into this more closely, I guess I was putting too much importance on the fact that the first few commits are shown as passing the Travis CI.  It appears that these same 3 commits were previously merged in #2079.  There have been some other changes to the file since then also.  Apparently the sum of those changes made the situation complicated enough for git that instead of just filtering them out as previously applied, it is seeing them as conflicting.

When I check just the most recent commit https://github.com/freeorion/freeorion/pull/2240/commits/5034434fda8a18f60a1ff9c7a5f9b5509f7078c2
by cherry picking into a branch based on current master, git finds no conflicts at all.

So, it looks to me like
```
$ git remote update upstream
$ git checkout Russian-Translation
$ git rebase upstream/master
$ git cherry-pick 5034434f
$ git push --force
```
should clean up this PR just fine.

And my recollection is that to add collaborators it is under the Settings for your repository, you send an invite.

2018-08-06 10:10 UTC, geoffthemedio commented
looks OK now, I think...

2018-08-06 10:11 UTC, Bestary commented
Hooray! Hooray! ^_____^ No conflicts for now. All what I've done:

- Updating upstream, that's ok.
- Made `hard reset` to the last my good commit (`Mu Ursh short description`) as I learned before. I tried to make `rebase upstream/master` before it but got another conflict and aborted this rebase.
- Push again.
- Made rebase again. Again conflicts. Felt that it was a reason of all. :)
- Resolved conflicts by my paws. Continue. New conflicts. Resolved. It was happened 3 times. After all I watch log and see that my 3 old last good commits was applied above current version of `ru.txt` file (above commits of a current date) by some reason. I don't know is it good or not. Hope I broke nothing...  Look the dates of commits:

![dates](https://user-images.githubusercontent.com/38672685/43704614-e0a68d40-9968-11e8-8f5c-7017a20bc332.png)

- Next push it forced, waited of all Travis CI checks. Travis pleased. ^_^
- Cherry-pick my new translations from backup to Russian-Translation branch. Conflicts appeared again. Resolved it, successfully commit and push forced. No conflicts in PR now. I learned. ^_^'

@Dilvish-fo, THANKS FOR ALL! Q___Q You are cool! Sorry for doing this too long, GitHub really hard for me just now. I can do something only with pretty fresh head. .-. Now it looks more clearly than before.

@Cjkjvfnby, now can you please to check my changes? ^____^'

2018-08-06 14:57 UTC, Dilvish-fo commented
Ack, the reason you had conflicts again was because I had mis-typed one of my lines in my last set of instructions, it was reading 'rebase' instead of 'reset --hard'  I am very sorry about that

So this PR is still reapplying old commits instead of just cleanly applying the new one.  Since you worked out the conflicts it could go through, but would make the history a bit messy.  After all that work I hate to ask anything more, but the cleanup really should be very easy.  You could just re-follow my last (now revised) instructions above, or even simply make a brand new PR with only that last commit in it, that commit is all we need here.  

But if Cj wants to approve it like this, I won't argue with that.

2018-08-06 15:05 UTC, geoffthemedio commented
> this PR is still reapplying old commits

What am I missing then? I don't see them in the master history for ru.txt:

https://github.com/freeorion/freeorion/commits/master/default/stringtables/ru.txt

> Since you worked out the conflicts it could go through, but would make the history a bit messy.

Wouldn't that be pretty much the same as accepting commits that merge master?

2018-08-06 21:09 UTC, Dilvish-fo commented
>this PR is still reapplying old commits
>> What am I missing then? Except for "[ru.txt] Translated/checked some races, checked other translations.", I don't see them in the master history for ru.txt:

So that's at least one reapplied commit, and I am pretty sure there are 3.  The history is seeming a bit tricky to sort out, and I have the same lack of success as you in finding the log entries for the two extra commits,  but I am pretty sure I am right on this, based on a few things:
- PR #2079 lists the same first three commits as here (a bit spread out in the conversation, but they are there), and the status at the top says that Cj merged 3 commits.
- look at the  [SP_MUURSH_GAMEPLAY_DESC changes from the  "Translated/checked some races, checked other translations."  commit from PR2079](https://github.com/freeorion/freeorion/pull/2079/commits/f3711fb8f21aa336f789d184323fb9b91a2aad59#r184886162), then the changes to those same lines from [the "Edited Mu Ursh short description."  commit from PR 2079](https://github.com/freeorion/freeorion/pull/2079/commits/22b7b236b2f5f68156852b8d3d6c5bcda56f0965?utf8=%E2%9C%93&diff=split) making a few more changes, 
then look at [the entry for SP_MUURSH_GAMEPLAY_DESC in the "Translated/checked some races, checked other translations." commit of this PR](https://github.com/freeorion/freeorion/pull/2240/commits/9949c34587e0c3bcaadf4812a32fd86c0a17d719#diff-699b6ed25f4c46d7b3fd2d3c7b309d26L6260),  -- it looks to me like since this first commit had really already been applied before, Bestiary's conflict resolution just seems to have left some newline changes, which for this particular case at least mostly just get undone a couple commits later, where [this repeated "Edited Mu Ursh short description" commit](https://github.com/freeorion/freeorion/pull/2240/commits/de72fb57b0744dd38d00cb7e1903e91c5d32dba8) is just left undoing a newline change from that repeated "Translated/checked some races, checked other translations."  commit. 

> Wouldn't that be pretty much the same as accepting commits that merge master?

I think it poses a similar kind of problem, but much more limited & perhaps sufficiently dealt with in this case since it was just a single file and Bestiary has done conflict resolution for each of the repeated commits (leaving them with just, as far as I noticed, a bit of newline changes).

But this more detailed review leaves me thinking more strongly that the cleanest/best thing would be for this PR to only have the one commit "All races and some other info..."

2018-08-06 23:16 UTC, Cjkjvfnby requested changes
I did not check the whole diff. Will continue tomorrow.

It is good practice to proofreading changes by yourself in a day or two after changes were made. You will see changes in different angle. It is especially useful for translation but works with code changes too.

2018-08-06 23:16 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Белый Кракен - это доисторический предок нынешнего монстра под названием Кракен, имеющий белый цвет.
`под названием Кракен`  можно заменить ссылкой на Кракена

2018-08-06 23:16 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Псионная снежинка - биоинженерный космический монстр с опасным оружием, умеющий брать под контроль судна с экипажем [[encyclopedia ORGANIC_SPECIES_TITLE]] на борту. Для борьбы с ней понадобится мощны
`Они также могут полностью атаковать население планеты.`  Я бы полностью убрал.

2018-08-06 23:16 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +'''Огромный, тяжёлый космический монстр с некоторой защитной бронёй.
`защитной бронёй` масло масленное, предлагаю, защитную убрать.

2018-08-06 23:16 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +[[SM_JUGGERNAUT_ENVIRONMENT]]'''
I have stopped review at this point.  To be continued...

2018-08-08 18:44 UTC, Cjkjvfnby requested changes
@Bestary , It is better to do small PR. It allows the splitting review to chunks.

Translate ships -> PR
Translate option ->  PR

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Скрипты Python вернули события, выполненные с ошибками. Подробнее об этих ошибках смотрите в файлах логов. Игра может быть продолжена, но в её процессе, возможно, возникнут проблемы.
`Скрипты создания событий выполнились с ошибкой.`

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Python AI для %1% вызвал ошибку.
Во время ходя игрока %1% произошла ошибка.

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Неверный пароль для имени игрока %1%.
Пароль для имени?  `Неверный пароль для имени %1%.`

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Если включено, то при выборе нескольких флотов разворачиваются окна для каждого из них. Если нет, то открытие нового флота будет происходить поверх окна со старым.
`то открытие нового флота` -> `то открытие окна нового флота`

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Показывать таймстамп в чате
`таймстамп ` -> `метку времени`

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Очистка файла stringtables
@geoffthemedio,   can you explain what `OPTIONS_FLUSH_STRINGTABLE` do?  Did it just reload stringtable from the disc?

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Планета скрыта от датчиков.
Может сенсоров?

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Автоматический выбор нападения.
Адаптивная тактика

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Автоматически выбирать нападение для нового флота на основе имеющегося у корабля оружия.
Выбор уровня агрессии для нового флота на основе наличия у коробля вооружения.

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Общая вместимость войск кораблём.
Предлагаю здесь и далее убрать кораблём.

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Доступные очки - это все очки, которые вы можете потратить на промышленность. Во втором числе указан максимум PP для выбранной вами системы, и он может быть больше суммарного количества очков, если с
`больше` -> `меньше`

This may be less than the total available when all of your empire's systems are not [[metertype METER_SUPPLY]] connected.

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Для заказов кораблей существует дополнительная опция меню - "Собирать в системе...". Когда заказ завершается, новый корабль (или корабли) по умолчанию получают пункт назначения указанной системы. Что
`Собирать в системе` -> `Собраться  в системе`  И в других частях абзаца.

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Файлы проектов
Должно быть однообразно.  Тогда нужно все остальные дизайны менять на проекты.

2018-08-08 18:44 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Невозможно записать файл:\n"%1%"
Stop point.

2018-08-09 09:47 UTC, Bestary commented on default/stringtables/ru.txt
> +Эскортный авианосец
Мне нравится Лёгкий авианосец) Сделала замену в трёх местах сразу.

2018-08-09 09:55 UTC, Bestary commented on default/stringtables/ru.txt
> +Крейсер, оборудованный для длительной независимой работы, с улучшенными лазерами и бронёй. [[BLD_SHIPYARD_BASE_REQUIRED]]
Перепроверила - действительно нет. Одно электромагнитное и одно зенитное. =) Занятно, но в английском файле тоже написано про лазеры. :D

2018-08-09 10:02 UTC, Bestary commented on default/stringtables/ru.txt
> +Поточный десант
Выглядит монструозно, если честно D: это притом, что есть ещё и отдельно Десантный корабль.

```
SD_ROBO_FLUX_TROOPS
Поточный десантный корабль

SD_ROBO_FLUX_TROOPS_DESC
Быстрый поточный десантный корабль

SD_ROBO_FLUX_TROOPS_HVY
Тяжелый поточный десантный корабль

SD_ROBO_FLUX_TROOPS_HVY_DESC
Очень быстрый поточный десантный корабль
```
Я как представлю, как это потом из очереди строительства выбирать... Увы, не сильная в военной терминологии, чтобы предложить что-то лучше(

2018-08-09 10:03 UTC, Bestary commented on default/stringtables/ru.txt
> +Авианосец флота MBs
Я не видела. :(

2018-08-09 10:09 UTC, Bestary commented on default/stringtables/ru.txt
> +Самогравитирующий корабль, предназначенный для масштабных действий флота. [[BLD_SHIPYARD_BASE_ORBITAL_DRYDOCK_CON_GEOINT_REQUIRED]]
Да почему, вполне понятно вроде всё) Но ничего не имею против замены.
У меня корабли с этим корпусом вообще Гравицапами называются. :DDD

2018-08-09 10:12 UTC, Bestary commented on default/stringtables/ru.txt
> +Крионический колониальный корабль
Я немного доведу до совершенства, с вашего позволения - 
Колониальный корабль с модулем криозаморозки.

2018-08-09 10:26 UTC, Bestary commented on default/stringtables/ru.txt
> +Невооруженный спутник, который может активировать планетарную защиту даже против пассивных врагов, однако, при её отсутствии, ничем не примечателен и может быть уничтожен на пути вражеского огня. Мож
Да, мудрое дополнение. На первых шагах в игре не сразу поняла, зачем соперники строят кучу спутников в своих системаз - полагаю, с описанием другим новичкам будет понятнее. =)

2018-08-09 10:37 UTC, Bestary commented on default/stringtables/ru.txt
> +Десантный отряд
Это два разных корабля. 

```SD_TROOP_DROP``` - десантный отряд (ранее - транспорт).
```SD_TROOP_SHIP``` - десантный корабль, и также некоторые его разновидности (SD_SMALL_TROOP_SHIP)

Не нашла лучшей замены для слова DROP, кроме как просто отряд. Кстати, слово "Транспорт", похоже, действительно теперь лишнее)

2018-08-09 10:39 UTC, Bestary commented on default/stringtables/ru.txt
> +[[SM_KRILL_MACRO_1]]. Хотя обычно они не агрессивны, даже в небольшом количестве космический планктон может создавать проблемы в навигации и пополнении запасов. [[SM_KRILL_MACRO_2]]
Наверное, автор английского оригинала обобщил - написал припасы, имелось ввиду запасы топлива) я исправила, чтоб было понятнее.

2018-08-09 10:44 UTC, Bestary commented on default/stringtables/ru.txt
> +Наполненный газом, луковичной формы мешок, блуждающий в космосе. Семя, отправленное существом [[predefinedshipdesign SM_TREE]] для создания новых лесов вокруг новых звёзд. Рекомендуются как можно ско
Понаизобретали уродов. :)

2018-08-09 10:45 UTC, Bestary commented on default/stringtables/ru.txt
> +Наполненный газом, луковичной формы мешок, блуждающий в космосе. Семя, отправленное существом [[predefinedshipdesign SM_TREE]] для создания новых лесов вокруг новых звёзд. Рекомендуются как можно ско
Я исправила на:
```Существо в форме луковицы, наполненное газом, блуждающее в космосе.```

2018-08-09 10:47 UTC, Bestary commented on default/stringtables/ru.txt
> +Белый Кракен - это доисторический предок нынешнего монстра под названием Кракен, имеющий белый цвет.
Только на какого из трёх? Я сделала ссылку на обычного Кракена.

2018-08-09 10:48 UTC, Bestary commented on default/stringtables/ru.txt
> +Псионная снежинка - биоинженерный космический монстр с опасным оружием, умеющий брать под контроль судна с экипажем [[encyclopedia ORGANIC_SPECIES_TITLE]] на борту. Для борьбы с ней понадобится мощны
Почему? Они неплохо так фигачат по планетам, я убедилась. :(

2018-08-09 10:49 UTC, Bestary commented on default/stringtables/ru.txt
> +Псионная снежинка - биоинженерный космический монстр с опасным оружием, умеющий брать под контроль судна с экипажем [[encyclopedia ORGANIC_SPECIES_TITLE]] на борту. Для борьбы с ней понадобится мощны
Извиняюсь, не поняла, что убрать надо просто слово "полностью". :)

2018-08-09 10:59 UTC, Bestary commented
@Cjkjvfnby, yep, re-read all changes 2-4 times (when it's need). :) Thanks for review so much. Don't hurry, I see, I did too much changes. I will try to do less changes in future.

I will have a trip next days, so can't review changes quickly - don't worry everyone, please, I'll not dissappear.

2018-08-09 11:03 UTC, Bestary commented on default/stringtables/ru.txt
> +Туманное существо, дающее [[metertype METER_STEALTH]] случайным планетам.
А фиг знает :) сделала просто "облако".

2018-08-09 11:11 UTC, Bestary commented on default/stringtables/ru.txt
> +Для заказов кораблей существует дополнительная опция меню - "Собирать в системе...". Когда заказ завершается, новый корабль (или корабли) по умолчанию получают пункт назначения указанной системы. Что
Так называется сама опция в меню очереди промышленности, если менять, тогда всё и сразу (иначе путаница), но по мне "собирать" как-то благозвучнее, чем "собраться" :)

...А вообще оба названия вызывают путаницу, ибо по факту корабль не собирается в указанной системе, а просто летит туда после сборки)

2018-08-09 11:12 UTC, Bestary commented on default/stringtables/ru.txt
> +Файлы проектов
Мы работаем над этим :))))
В исходном переводе тоже то проект было, то дизайн.

2018-08-09 17:04 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Крейсер, оборудованный для длительной независимой работы, с улучшенными лазерами и бронёй. [[BLD_SHIPYARD_BASE_REQUIRED]]
По хорошему там тоже стоит исправить.

2018-08-09 17:16 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Для заказов кораблей существует дополнительная опция меню - "Собирать в системе...". Когда заказ завершается, новый корабль (или корабли) по умолчанию получают пункт назначения указанной системы. Что
`Собирать в системе`  Строители решили собирать корабль из детелей в системе Х.
`Собраться в системе` После успешной сборки корабля строители решили собраться в баре. 

Может что-то типа `отправить в систему`

2018-08-11 08:02 UTC, Cjkjvfnby requested changes

2018-08-11 18:28 UTC, Dilvish-fo submitted a review, later dismissed
Just to formally note, since the comment might get lost amongst all the content comments-- In addition to the content changes Cj is requesting, I think the superfluous/repeat commits issue should be dealt with before this gets merged. 

Since CJ has already given so many content comments,  it might be best (the most reliable process) for Bestary to first deal with them and push corresponding commits, and then afterwards we'd look at clearing out the initial repeated commits.  (Removing them first, and rebasing, would probably mark all the existing comments as outdated all at once and restrict Bestary's ability to use the github 'outdated' comment feature to help track which comments he had already dealt with).

2018-08-11 19:27 UTC, Cjkjvfnby commented
> then afterwards we'd look at clearing out the initial repeated commits.

Can I just press squash and merge instead?  Like this [[ru.txt] Translated/checked some races, checked other translations.](https://github.com/freeorion/freeorion/commit/061bce03ce99f25be2883bed052bec1a0d95c23f#diff-699b6ed25f4c46d7b3fd2d3c7b309d26)

2018-08-12 03:28 UTC, Dilvish-fo commented
>  Like this

Ah, so that's what happened there!  Geoff and I were both a bit confused by what that did to the history-- the PR had 3 commits but Geoff and I could not locate 2 of the commits in the history when we tried to confirm they had been committed, and although I did wind up noticing the status on the top of the PR said that you had merged 3 commits, it still seemed a bit uncertain/confusing to not find them in the log, though in hindsight, now that you mention the squash merge, it seems I should have been able to figure out that's what happened.

I suppose another squash would be the simplest way to clean this one up reasonably well, fine with me.

2018-08-12 07:45 UTC, Cjkjvfnby commented
> although I did wind up noticing the status on the top of the PR said that you had merged 3 commits

On top: `Cjkjvfnby merged 3 commits into freeorion:master from Bestary:Russian-Translation on May 2 `
In history: `@Cjkjvfnby Cjkjvfnby merged commit 061bce0 into freeorion:master on May 2
1 check passed `

I have reported it to github.

2018-08-22 07:43 UTC, geoffthemedio commented
Status update on this?

2018-08-29 20:57 UTC, Bestary commented on default/stringtables/ru.txt
> +Крейсер, оборудованный для длительной независимой работы, с улучшенными лазерами и бронёй. [[BLD_SHIPYARD_BASE_REQUIRED]]
Ок, исправлю, сделаю PR следом за этим. ;) (если до меня никто не исправит)

2018-08-29 21:04 UTC, Bestary commented on default/stringtables/ru.txt
> +Туманное существо, дающее [[metertype METER_STEALTH]] случайным планетам.
Хм, так ведь по сути эти 4 "туманных" монстра только и различаются, что картинками и названиями, описания и действия у них одинаковые.

2018-08-29 21:09 UTC, Bestary commented on default/stringtables/ru.txt
> +Неверный пароль для имени игрока %1%.
Я думаю, даже "имя" можно убрать)

2018-08-29 21:15 UTC, Bestary commented on default/stringtables/ru.txt
> +Автоматический выбор нападения.
Мне было бы непонятно. :(

2018-08-29 21:16 UTC, Bestary commented on default/stringtables/ru.txt
> +Автоматический выбор нападения.
Пардон, там же дальше описание есть - тогда ок. :)

2018-08-29 21:26 UTC, Bestary commented on default/stringtables/ru.txt
> +Автоматически выбирать нападение для нового флота на основе имеющегося у корабля оружия.
Немного переделала
`Выбор тактики поведения для нового флота осуществляется на основе наличия/отсутствия у его кораблей оружия.`

2018-08-29 21:30 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Туманное существо, дающее [[metertype METER_STEALTH]] случайным планетам.
Тогда хотябы простое существо, отчего ж оно туманное?

2018-08-29 22:04 UTC, Bestary commented on default/stringtables/ru.txt
> +Эти гигантские мощности (излучаемые Ациремами отдельно и при помощи Портала) дают большое преимущество в промышленности. Однако, это же делает Портал очень лакомым кусочком для пришельцев. По этой пр
Так со своей всё добыли, а с других - не могут физически. :) Я перефразировала, ок.

2018-08-29 22:15 UTC, Bestary commented
@Cjkjvfnby, thanks so much for review, added all changes you requested (or commented). I'll do less PR in future. :)

2018-08-30 13:48 UTC, Bestary commented
Hm, something goes wrong again... C++ check failed. Ill-fated PR. :)

2018-08-30 15:59 UTC, geoffthemedio commented
@Cjkjvfnby I think I accidentally removed the question, but flushing the stringtable deletes all of the loaded strings and causes the stringtable files to be reloaddd from disk.

2018-08-30 16:00 UTC, geoffthemedio commented
A C++ error is probably no problem for merging this pull request as it doesnt touch files outside the stringtables.

2018-08-30 16:08 UTC, Bestary commented on default/stringtables/ru.txt
> +Туманное существо, дающее [[metertype METER_STEALTH]] случайным планетам.
Вернее будет как раз оставить про туманность, ибо оно всё-таки не существо, а "живая" туманность. :)

2018-08-30 16:10 UTC, Bestary commented
@geoffthemedio, not touching any files except ru.txt. Well, ok. :)

2018-08-30 16:30 UTC, Cjkjvfnby requested changes

2018-08-30 16:30 UTC, Cjkjvfnby commented on default/stringtables/ru.txt
> +Время и стоимость (или оба) %1% этого элемента зависят от местоположения.
`и` не вяжется с `(или оба)`

2018-08-30 21:54 UTC, Bestary commented on default/stringtables/ru.txt
> +Время и стоимость (или оба) %1% этого элемента зависят от местоположения.
убрала эти "или оба" нафиг %)

2018-08-30 22:32 UTC, merged