Update ru.txt
freeorion/freeorion pull request #2893
Opened 2020-04-25 10:17 UTC by geoffthemedio

Resolves conflicts of and supercedes #2793

2020-04-25 18:13 UTC, o01eg commented
I remember I left some notes about previous PR. Also it's a still very big PR to be correctly reviewed.

2020-04-25 21:08 UTC, geoffthemedio commented
> I remember I left some notes about previous PR. Also it's a still very big PR to be correctly reviewed.

It looked like there were replies to all your comments, with no additional follow up or re-reply for some time...

I'd like to merge this before the next release, but will certainly wait for your approval.

2020-04-25 21:54 UTC, Cjkjvfnby commented
> Also it's a still very big PR to be correctly reviewed.

Technically it is easy to split PR to separate PRs because translation entries are not related(almost).  I can help @naiffuR  with it.     

@o01eg what do you think?

2020-04-26 05:52 UTC, o01eg requested changes

2020-04-26 05:52 UTC, o01eg commented on default/stringtables/ru.txt
> +Ход вперед через фиксированные промежутки времени, независимо от того, когда и когда игроки отправили приказы хода.
@naiffuR `когда и когда`

2020-04-26 05:52 UTC, o01eg commented
@Cjkjvfnby Yes, splitting PR would be nice.

2020-04-26 14:46 UTC, naiffuR commented on default/stringtables/ru.txt
> +Ход вперед через фиксированные промежутки времени, независимо от того, когда и когда игроки отправили приказы хода.
fix: когда и какой игрок отправил приказ хода

2020-05-01 07:29 UTC, naiffuR commented
Fix [ru.txt](https://github.com/freeorion/freeorion/files/4562892/ru.txt)

2020-05-01 15:16 UTC, geoffthemedio commented
> Fix [ru.txt](https://github.com/freeorion/freeorion/files/4562892/ru.txt)

Not sure what you mean...

2020-06-14 15:57 UTC, closed without merging