Migrate Python related CI jobs onto GitHub actions CI
freeorion/freeorion pull request #3098
Opened 2020-07-08 22:06 UTC by adrianbroher

This PR migrates the existing Travis CI jobs related to Python:

* Syntax check (compileall)
* PEP-8 conformance test
* Unit test

onto GitHub Actions CI infrastructure.

The PR contains some intentional bugs to show the integration of GitHub Check annotations, which display errors and warnings within the PR file diff for easier reviewing.

I'm not sure if the annotations are already created on this initial PR, so you can take a look into a PR in private repository: adrianbroher/freeorion#8.  Most relevant aspects are the `Checks` tab for looking into the CI run logs and the `Files` tab to see the in-place annotations for the provoked error messages.

2020-07-11 14:08 UTC, Cjkjvfnby commented
We have 3 checks
- name: Syntax check AI sources
- name: Lint AI sources against PEP8
- name: Unit test AI sources

As I understand the second one includes the first one.   Removing it will save us some time. 

To run tests and linter we need only python and pip, so we can remove CMake and ninja parts. 

I want to keep Python only checks separately from other checks. So this action will be triggered only if Python files in the default/python directory were changes.

C++ and string tables checks should go to different actions. 

@adrianbroher what do you think?

2020-07-11 14:54 UTC, adrianbroher commented
> To run tests and linter we need only python and pip, so we can remove CMake and ninja parts.

I will not look up any of those tools command line usage, environment setup and dependency checks when I can encode those into the build system the same way I won't invoke g++ manually, even when it is perfectly possible to build a C++ project without a build system.

2020-07-11 15:42 UTC, Cjkjvfnby commented
> I will not look up any of those tools command line usage, environment setup and dependency checks when I can encode those into the build system 

It is not achieved yet. Dependencies are installed separately. You invoke pytest via the command line. 
It is pretty ok to have these tools embedded in development instruments.

But we talking about the CI pipeline. That should be fast. Really fast. Compile a bunch of tools to run bash command `flake8 .` is a huge overhead.

2020-07-11 16:09 UTC, adrianbroher commented
Are you maintaining the CI pipeline or the build system despite lackluster interest from others on this topic the last years?  Or did I so far?  I'm implementing it the way  it is the easiest maintainable for me.  If you don't like it the way it is done do it yourself ffs.

2020-07-11 21:32 UTC, geoffthemedio commented
> Are you maintaining the CI pipeline or the build system despite lackluster interest from others on this topic the last years?

What do you mean by that? I, at least, use the CI builds regularly to test if changes will break the OSX and Linux builds. I've seen a few other people do the same. If you mean interest in maintaining it, then sure... but there's certainly interest in using it.

2020-07-11 22:34 UTC, Cjkjvfnby commented
> Are you maintaining the CI pipeline or the build system despite lackluster interest from others on this topic the last years? 

Tests and flake8 were initially added by me. So I am interested in that exact part of the pipeline.

> but all of it.

Let me clarify, what I intend to do:  I want to remove part of the existing pipeline and create a new one.
So we will end with 2 pipelines. One for Python and one for C++.  
The migration of the second pipeline is also in plans. I would like to have a button: get `recent windows build`.  But now it is out of the scope of this PR.

Lets back for the way how python is called:

We have 3 python tasks: 
Lint AI with Python 3.5 
Lint string tables
Unittest AI

One of them significantly longer. Just because we run a Python script in a specific way.  We got CI for free and we should not waste resources for no reason.

![image](https://user-images.githubusercontent.com/171597/87234719-77e5ed00-c3dc-11ea-89b4-8413461684b3.png)

Linter task:
![image](https://user-images.githubusercontent.com/171597/87234667-f1311000-c3db-11ea-9b3b-3c37d7ae4fa5.png)

2020-07-11 22:47 UTC, Cjkjvfnby commented
@adrianbroher I cannot request a review or mention you in other PRs. 
https://github.com/freeorion/freeorion/pull/3101

2020-07-11 22:49 UTC, adrianbroher commented
@Cjkjvfnby As noted:

> If you don't like it the way it is done do it yourself ffs, but all of it.

2020-07-21 09:07 UTC, geoffthemedio commented
@adrianbroher Is this still a draft?

2020-07-25 16:24 UTC, adrianbroher commented
@geoffthemedio No, but the intentional bug triggering commits need to be removed and the draft flag prevents unintentional merging.

2020-07-29 21:02 UTC, Cjkjvfnby commented
Her is my version of the same pr.  https://github.com/freeorion/freeorion/pull/3106/files

2020-08-02 10:50 UTC, adrianbroher commented
Removed intenional buggy code for testing.

2020-08-02 13:12 UTC, geoffthemedio commented
@Cjkjvfnby any comments? I would otherwise defer to @adrianbroher for stuff such as this...

2020-08-02 17:45 UTC, Cjkjvfnby requested changes
Stringtables check deserves a separate task.  But since it shares the same configuration, I would recommend adding it to this build.

2020-08-02 17:45 UTC, Cjkjvfnby commented on .github/workflows/test-AI.yml
> +on: push
```
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
```

2020-08-02 17:45 UTC, Cjkjvfnby commented on .github/workflows/test-AI.yml
> +name: Test AI with linting and unit tests
and string tables check

2020-08-02 17:45 UTC, Cjkjvfnby commented on .github/workflows/test-AI.yml
> +          - 3.6
Lets test on 3.5

2020-08-02 17:45 UTC, Cjkjvfnby commented on .github/workflows/test-AI.yml
> +      - name: Set up system dependencies
It is the longest step. I would recommend to remove it.  Or try to cache it. 

![image](https://user-images.githubusercontent.com/171597/89128558-20303280-d4ff-11ea-93bd-141ce850ea65.png)

2020-08-02 17:45 UTC, Cjkjvfnby commented on .github/workflows/test-AI.yml
> +      - name: Create build directory
Why do we need to spend 5 seconds on this step?

2020-08-02 17:45 UTC, Cjkjvfnby commented on .github/workflows/test-AI.yml
> +        if: always()
You can remove it.

2020-08-02 17:45 UTC, Cjkjvfnby commented on .github/workflows/test-AI.yml
> +        if: always()
You can remove it.

2020-08-02 17:45 UTC, Cjkjvfnby commented on default/python/tox.ini
> +  default/python/AI/FreeOrionAI.py:E402
You don't need to duplicate these settings, just add `*`:  

```
*FreeOrionAI.py:E402
 *AIDependencies.py: E241
 *AI/savegame_codec/__init__.py: F401
 *AI/freeorion_tools/__init__.py: F401,F403
 *auth/auth.py: E402
 *chat/chat.py: E402
 *turn_events/turn_events.py: E402
 *universe_generation/teams.py: E402
 *universe_generation/universe_generator.py: E402
 *universe_generation/universe_tables.py: E201,E122,E231
 *stub_generator/__init__.py: F401
 *tests/conftest.py: E402,F401
```

2020-08-02 17:52 UTC, adrianbroher commented
Not interested on your feedback.

2020-08-02 18:23 UTC, Cjkjvfnby commented
> @Cjkjvfnby any comments? I would otherwise defer to @adrianbroher for stuff such as this...

I am unhappy, with this situation.  Not because of relations with Marcel, but because this task is moving too slow.  The current CI is not acting well. It runs too long, builds fails for no reason, reporting is confusing.  
Another thing that features I would like to have will never be implemented: skip checks if they are not required, publish windows build with CI.

2020-08-02 18:46 UTC, geoffthemedio commented
If @adrianbroher isn't interested in feedback or collaborating on this, then I'm not sure what to do besides ask @Cjkjvfnby if this pull request better merged than not? If yes, then I can just merge it and any future improvements can happen in future. Regardless of issues collaborating smoothly, that's probably when they should be dealt with. If not, I suppose I can somewhat reluctantly just merge it anyway, as the whole CI system is largely @adrianbroher's work, so I'd probably defer to his preference for it. Also, just merging this as is will speed up the improvements more than not doing so, presumably...

@Cjkjvfnby From what I understand from various posts and last week's group call, @adrianbroher has plans for further improvements, possibly including things like automating generation of daily or weekly builds. Hopefully that's a bit reassuring...?

2020-08-02 20:04 UTC, Cjkjvfnby commented
> last week's group call

I have missed you doing meetings.  I'll read agendas.

>  I suppose I can somewhat reluctantly just merge it anyway

This PR is not enough, repo configuration is required, leave merging to the author.

2020-08-02 20:20 UTC, geoffthemedio commented
> This PR is not enough, repo configuration is required

Whether it's "enough" for something you'd like isn't the question... Rather, is it an improvement or progress?

> leave merging to the author.

@adrianbroher seemingly prefers to have others merge his pull requests rather than commit directly or do so himself. Since he removed the "draft" designation from this, I assume that means he would like it merged now. (I assume the text above "adrianbroher marked this pull request as ready for review" is misleading, since he apparently isn't actually interested in review...?)

2020-08-02 21:17 UTC, Cjkjvfnby commented
This PR will disable mandatory python checks. 

To make it mandatory you need to trigger it once and https://docs.github.com/en/github/administering-a-repository/enabling-required-status-checks

To trigger it you need to push to THIS repo because this check is triggered only by pushes. Push to fork triggers it in the fork.

2021-11-09 11:31 UTC, o01eg commented
I suppose it could be closed as all checks was moved to Github Actions

2021-11-09 11:31 UTC, closed without merging