Use github actions for checks
freeorion/freeorion pull request #3106
Opened 2020-07-15 22:27 UTC by Cjkjvfnby

This is a rework of the https://github.com/freeorion/freeorion/pull/3098

This PR is ready for merge but will require more steps after that.  I expect the following workflow:

- merge this PR, action will become available and will be triggered on each build.
- configure this action as required for PRs to master. [Enabling required status checks](https://docs.github.com/en/github/administering-a-repository/enabling-required-status-checks) 
- remove Travis checks

## Important changes
I have removed a pytest run on Python 3.8.  Python backward compatibility is good enough. 

## Benefits
- GitHub action has a cool feature, it is possible to leave a comment at the line that caused an error. It is already enabled for flake8 and pytest.
- It is much faster.
- Code is simpler (we don't need to put C++ and python configuration into the same file, as we do with Travis)

## Next steps
- Add annotation to the string tables check
- Allow skipping checks if no corresponding files are affected.
- Move C++ checks to GitHub actions
- Automate the creation of the windows build

2020-12-28 21:17 UTC, o01eg commented
I suppose it is very actual because of issues with Travis CI.

2021-02-23 22:23 UTC, geoffthemedio commented
please rebase on master, rather than merging master into your branch...

2021-02-23 23:43 UTC, Cjkjvfnby commented
I think it is ready to be merged.

2021-03-11 19:54 UTC, o01eg requested changes
Could we test it against different python versions?
I see it uses matrix.python-version but I don't see its definition.

2021-03-21 18:02 UTC, Cjkjvfnby commented
> Could we test it against different python versions?

I think we can test only the minimum required version.  

There are 2 reasons for it:
- Python preserves compatibility and we don't expect any failures.
- I don't remember any compatibility problem since we introduce testing on two versions.

Testing only one Python version saves resources and make thing a bit easier.

2021-03-23 06:15 UTC, o01eg commented
As I know Blender discourages to use python 3.9 due compatibility issues https://bugs.gentoo.org/737388 . Also I see it takes less a minute to execute python tests.

2021-04-03 19:31 UTC, o01eg requested changes

2021-04-03 19:31 UTC, o01eg commented on .github/workflows/python-check.yml
> +        python-version: ['3.6', '3.9']
It gets `No steps defined in `steps` for the following jobs: build` error. Maybe it should use options without quotes?

2021-04-04 00:15 UTC, o01eg approved these changes
Looks good

2021-04-05 21:02 UTC, o01eg requested changes

2021-04-05 21:02 UTC, o01eg commented on .github/workflows/python-check.yml
> +          ./check/st-tool.py check --reference default/stringtables/en.txt default/stringtables/*.txt
@Cjkjvfnby You should use `??.txt` pattern as I moved includes here too.

2021-04-05 21:30 UTC, Cjkjvfnby commented
I have split the script into 2 workflows.  One is run with multiple pythons (check and linter) and another one with the single one (string tables check).

2021-04-06 03:07 UTC, o01eg commented
> I have split the script into 2 workflows. One is run with multiple pythons (check and linter) and another one with the single one (string tables check).

It possible to use conditions.

2021-04-06 19:34 UTC, Cjkjvfnby commented
> It possible to use conditions.

This will make the code a bit dirty. I'd prefer to have a simple and straightforward code, which is easy to understand modify and support.

2021-04-06 19:47 UTC, o01eg approved these changes

2021-04-16 22:12 UTC, geoffthemedio commented
@Cjkjvfnby @o01eg Is this resolved and ready to merge or still under discussion?

2021-04-17 05:03 UTC, o01eg commented
@geoffthemedio It's fine for me.

2021-05-03 12:54 UTC, merged

2021-05-03 12:59 UTC, Cjkjvfnby commented
@geoffthemedio , since these new jobs are never failed for no reason and always executed we could make them mandatory for merge.

See https://github.com/freeorion/freeorion/settings/branch_protection_rules

This will look like:
![image](https://user-images.githubusercontent.com/171597/116878535-2c7d2380-ac28-11eb-86e9-dfb68791d3ef.png)

2021-05-03 13:14 UTC, geoffthemedio commented
I'm hesitant to make test builds mandatory for merging if they can take 30+ min to run, even if they don't fail randomly...

2021-05-03 14:05 UTC, Cjkjvfnby commented
> I'm hesitant to make test builds mandatory for merging if they can take 30+ min to run, even if they don't fail randomly...

Check that introduced here takes less than a minute.  Look ok for me to make them required. 

Looks like I have messed with task names, they are not informative. I will make new PR to fix it.

2021-05-03 16:42 UTC, geoffthemedio commented
> Check that introduced here takes less than a minute. Look ok for me to make them required.

OK then.