Add the ability to terraform planets to AI
freeorion/freeorion pull request #3112
Opened 2020-07-21 08:48 UTC by rrobgill

* Terraformer and gaia transformation can be built by AI after
  each relevant tech is researched

  Limits:

  - No more than one of each building may be queued per turn

  - Will be queued in turn on the planet with the largest
    population, and planet must already be at its target population

  - Will not be enqueued if enemy ships are present in system

* GRO_TERRAFORM and GRO_GAIA_TRANS added to Growth techs

Signed-off-by: Rob Gill <rrobgill@protonmail.com>

2020-07-21 09:04 UTC, geoffthemedio commented
````
./AI/ProductionAI.py:1111:17: E129 visually indented line with same indent as next logical line
./AI/ProductionAI.py:1112:21: E117 over-indented
````

2020-07-21 19:39 UTC, Cjkjvfnby requested changes
I am not sure how it will affect AI behavior. 
As I recall this is a huge building. We don't evaluate the benefits of them.  Is they always worth building?

2020-07-21 19:39 UTC, Cjkjvfnby commented on default/python/AI/ProductionAI.py
> +        queued_locs = [element.locationID for element in production_queue if (element.name in terraformers)]
Use set
```python
queued_locs = {element.locationID for element in production_queue if (element.name in terraformers)}
```

2020-07-21 19:39 UTC, Cjkjvfnby commented on default/python/AI/ProductionAI.py
> +        if candidates:
Lets remove `if`  

It is ok to iterate over empty list. 

You still can use else:  https://book.pythontips.com/en/latest/for_-_else.html#for-else

2020-07-21 19:39 UTC, Cjkjvfnby commented on default/python/AI/ProductionAI.py
> +            candidates.sort(key=itemgetter(1), reverse=True)
Switch order of values on candidates and you can omit `key` argument.

2020-07-21 19:39 UTC, Cjkjvfnby commented on default/python/AI/ProductionAI.py
> +                    candidates.append([pid, planet.currentMeterValue(fo.meterType.population)])
Please add tuples, not lists.

2020-07-21 19:39 UTC, Cjkjvfnby commented on default/python/AI/ProductionAI.py
> +                for pid in candidates:
it is not pid, it is a pair of pid and population.  

You can use unpacking:  `for pid, _ in candidates: planet = universe.getPlanet(pid)`

2020-09-03 07:10 UTC, geoffthemedio commented
@rrobgill ?

2021-04-06 03:40 UTC, closed without merging

2021-04-06 03:41 UTC, rrobgill commented
no plans.