Some more translations into spanish
freeorion/freeorion pull request #3671
Opened 2022-01-18 15:58 UTC by rsf92

Some more translations, awaiting @Oberlus's comments.

2022-01-18 16:51 UTC, rsf92 commented
I've had a look at the errors on the pipeline, but I can't see how they're related to my changes...

2022-01-18 17:30 UTC, Oberlus requested changes

2022-01-18 17:30 UTC, Oberlus commented on default/stringtables/es.txt
> +Vías Estelares Completas
Great, you found a much better translation for starlanes: vías estelares.
Whenever you find mentions to "línea(s) estelare(s)", don't hesitate to replace "línea" by "vía".

2022-01-18 17:30 UTC, Oberlus commented on default/stringtables/es.txt
> +Todos los sismteas visibles
typo: sistemas

2022-01-18 17:30 UTC, Oberlus commented on default/stringtables/es.txt
> +Las naves fuera del sistema pueden otorgan capacidad de detección
I like this more:
"Las naves fuera de sistemas solares tienen visión"
It is more explicative for casual players than the English "provide detection" (provide who with detection? the ship provides itself with detection).
If you prefer to be stick to a more direct translation, it should be this:
"Las naves fuera de sistemas solares otorgan detección" (_sistemas_ in plura)

2022-01-18 17:30 UTC, Oberlus commented on default/stringtables/es.txt
> +Planetas Sigilosos Indetectables
"Planetas sigilosos invisibles" (not indetectable!)

"Sigiloso" sounds so weird for planets, but using "ocultos" here could be confusing if we use "sigilo" and "sigiloso" everywhere for "stealth" and "stealthy".

Side note that applies to several entries: In Spanish, title-ish stuff is expected to capitalize the first letter of only the first word, "El señor de los anillos", "Resultados y discusión".

2022-01-18 17:30 UTC, Oberlus commented on default/stringtables/es.txt
> +'''<u>Activado</u>: Los planetas con mayor sigilo que la capacidad de detección de un imperio no pueden ser detectadas simplemente con que dicho imperio disponga de un objeto en el mismo sistema,salv
"sistema,salvo" -> "sistema, salvo" (lacks a space)

2022-01-18 17:34 UTC, Oberlus commented
> I've had a look at the errors on the pipeline, but I can't see how they're related to my changes...

No idea about that.
@geoffthemedio

2022-01-19 09:22 UTC, geoffthemedio commented
> > I've had a look at the errors on the pipeline, but I can't see how they're related to my changes...
> 
> No idea about that. @geoffthemedio

Don't ask me about the unit tests or why `SmokeTestHostless` seemingly [randomly fails](https://github.com/freeorion/freeorion/runs/4856593083?check_suite_focus=true#step:13:5297)... I didn't set them up...

2022-01-19 17:52 UTC, Oberlus commented
Good to merge

2022-01-19 17:52 UTC, Oberlus approved these changes

2022-01-21 12:01 UTC, merged