Update README.md
freeorion/freeorion pull request #3673
Opened 2022-01-19 13:11 UTC by geoffthemedio

-newish builds require Windows 8.1 as far as I'm aware
-mention probably-supported Ubuntu versions

2022-01-19 13:11 UTC, geoffthemedio commented
@Vezzra what's the status of support MacOS versions?

2022-01-23 11:27 UTC, Vezzra requested changes
> what's the status of support MacOS versions?

macOS 10.9 for the 0.4.10.x release branch, macOS 10.12 for current master. Meaning, the macOS version in the README in master needs to be updated too.

2022-01-23 11:27 UTC, Vezzra commented on README.md
>  *Mac OSX 10.9* or later or any reasonably recent Linux distribution on x86
```suggestion
*macOS 10.12* or later or any reasonably recent Linux distribution on x86
```

2022-01-23 12:15 UTC, geoffthemedio commented
> the macOS version in the README in master

not sure which README you're referring to, if not the one being edited in this pull request...

2022-01-23 12:27 UTC, Vezzra commented
Sorry, my bad, of course I'm referring to the README in this PR (adding "in master" was confusing superfluous information 😉).

2022-01-23 12:27 UTC, Vezzra approved these changes

2022-01-23 12:44 UTC, merged