Translate more strings into spanish
freeorion/freeorion pull request #3680
Opened 2022-01-23 18:31 UTC by rsf92

I translated a few more strings. For some reason, it does not detect that [[BEGINNER_HINT_XX] ] is a link to another element of the pedia, it seems to happen only with my strings so there might be an error there, but I wasn't able to find it...

2022-01-23 20:15 UTC, geoffthemedio commented
> it does not detect that [[BEGINNER_HINT_XX] ] is a link

The line `#*BEGINNER_HINT_15` string is commented out in your stringtable... But it would be just a macro subsitution anyway, not a clickable link.

2022-01-23 20:59 UTC, rsf92 commented
> > it does not detect that [[BEGINNER_HINT_XX] ] is a link
> 
> The line `#*BEGINNER_HINT_15` string is commented out in your stringtable... But it would be just a macro subsitution anyway, not a clickable link.
> 

Oh yeah makes sense. I thought it would display the English text instead.

I'll add the translation when I find some spare time

2022-01-23 21:21 UTC, geoffthemedio commented
Substitutions with `[[KEY]]` are done **within each stringtable** when it is loaded, as far as I recall.

Fallbacks to the english stringtable are done for keys that are looked up within C++ code or used in content scripts, but those are resolved at runtime as strings are displayed.

2022-01-24 09:34 UTC, Oberlus requested changes

2022-01-24 09:34 UTC, Oberlus commented on default/stringtables/es.txt
> +Indice
Índice

2022-01-24 11:35 UTC, rsf92 commented
> 
> Edit2: Fallbacks from spanish to english work for me with this pull request applied... )

I'll check again, but i'm pretty sure it wasn't working for me...

2022-01-28 15:59 UTC, rsf92 commented on default/stringtables/es.txt
> +Indice
Should be fixed in this new commit

2022-01-29 15:17 UTC, Oberlus requested changes

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +Enfoque
I think Foco is better than Enfoque, but this is a tough one.

"Foco" is where you concentrate your attention or efforts, also the source of something, from where it expands.
"Enfoque" is more easily understood as point of view (how you look at something), camera focusing (to make image clearer), or shining a light on something.
So Enfoque is more about how (Enfoque industrial: I do this with the POV of an industrial businessman), and Foco is more about what (Foco en industria: concentrate efforst on industry).

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +Enfoque de crecimiento
Foco en crecimiento

(I like that more than "Foco de crecimiento")

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +Enfoque
Foco

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +1: Al empezar la partida, construir más [[predefinedshipdesign SD_SCOUT]]s puede facilitar explorar la región en cercana al mundo de origen.
```suggestion
1: Al empezar la partida, construir más [[predefinedshipdesign SD_SCOUT]]s puede facilitar explorar la región cercana al mundo de origen.
```

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +5: Todos los sistemas comparten punto de [[metertype METER_RESEARCH]] (PI) que generan incluso sin tener líneas de [[metertype METER_SUPPLY]] entre ellos. Cuándo no existan dichas líneas, establecer
```suggestion
5: Todos los sistemas comparten puntos de [[metertype METER_RESEARCH]] (PI) que generan incluso sin tener líneas de [[metertype METER_SUPPLY]] entre ellos. Cuándo no existan dichas líneas, establecer el [[encyclopedia FOCUS_TITLE]] a investigación puede resultar más eficiente para un planeta que otras opciones.
```

We've got a problem here. We need to decide how to translate Research and Influence. If both end up starting with an "in", then we can't use PI or PIn.

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +7: Algunos edificios, como el [[buildingtype BLD_INDUSTRY_CENTER]], afectarán a cada planeta que tenga una conexión de [[metertype METER_SUPPLY]]. Otros, como [[buildingtype BLD_GAS_GIANT_GEN]], sólo
```suggestion
7: Algunos edificios, como el [[buildingtype BLD_INDUSTRY_CENTER]], afectarán a cada planeta que tenga una conexión de [[metertype METER_SUPPLY]]. Otros, como [[buildingtype BLD_GAS_GIANT_GEN]], sólo afectan al sistema en el que se construyeron. Revise la sección [[encyclopedia ENC_BUILDING_TYPE]] para conocer las funciones que cumplen los distintos edificios.
```

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +11: La [[metertype METER_POPULATION]] máxima alcanzable por un planeta puede ser aumentada investigando varias tecnologías de creciciemto. Algunos especiales inusuales pueden incrementar la [[meterty
```suggestion
11: La [[metertype METER_POPULATION]] máxima alcanzable por un planeta puede ser aumentada investigando varias tecnologías de crecimiento. Algunos especiales inusuales pueden incrementar la [[metertype METER_TARGET_POPULATION]] para especies con metabolismos específicos, consulte [[encyclopedia GROWTH_FOCUS_TITLE]] para más información sobre estos especiales.
```

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +12: Presta atención a los planetas con [[encyclopedia ENC_SPECIAL]], habitualmente indican la presencia de algún recurso especial que puede beneficiar a tu imperio si lo utilizas de manera apropiada
```suggestion
12: Presta atención a los planetas con [[encyclopedia ENC_SPECIAL]]es, habitualmente indican la presencia de algún recurso especial que puede beneficiar a tu imperio si lo utilizas de manera apropiada. Clica con el botón derecho sobre el icono del recurso especial para acceder a su página de la Pedia y descubrir más.
```

That "!" in the original English is quite out of place.

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +13: Únicamente los [[species SP_EXOBOT]] pueden colonizar cinturones de asteroides. Si descubres muchos cinturones de asteroides próximos, ¡Puede que quieras investigar como construirlos más pronto q
```suggestion
13: Únicamente los [[species SP_EXOBOT]]s pueden colonizar cinturones de asteroides. Si descubres muchos cinturones de asteroides próximos, puede que quieras investigar como construirlos más pronto que tarde.
```

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +14: Investiga mejoras en [[metertype METER_SUPPLY]],  como [[tech CON_ORBITAL_CON]], para incrementar la distancia que alcanzan tus lineas de suministro desde tu sistema.
```suggestion
14: Investiga mejoras en [[metertype METER_SUPPLY]], como [[tech CON_ORBITAL_CON]], para incrementar la distancia que alcanzan tus lineas de suministro desde tu sistema.
```

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +15: La mayoria de las especies comienzan con un [[metertype METER_HAPPINESS]]  de 0 cuando su planeta es capturado, que - usualmente - irá aumentando en 1 por cada turno que pase. ¡Presta atención a
```suggestion
15: La mayoria de las especies comienzan con una [[metertype METER_HAPPINESS]] de 0 cuando su planeta es capturado, que (usualmente) irá aumentando en 1 por cada turno que pase. Presta atención a las especies [[encyclopedia XENOPHOBIC_SPECIES_TITLE]]s. No les gusta estar cerca de otras especies, lo cual afectará a la estabilidad u otros valores tanto suyos como de especies cercanas.
```

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +18: [[encyclopedia FOCUS_TITLE]] - presta atención al medidor de enfoque de los nuevos planetas que añadas a tu imperio, tanto colonizados como conquistados. Este medidor controla si el planeta se en
```suggestion
18: [[encyclopedia FOCUS_TITLE]]: presta atención foco planetario de los nuevos planetas que añadas a tu imperio, tanto colonizados como conquistados. El foco seleccionado controla en que se concentra la producción: en industria, en investigación, en influencia, en defensa, etc. Avanzada la partida, más opciones de foco pueden ser desbloqueadas a medida que se investigan nuevas [[encyclopedia ENC_TECH]]s. Distintas especies pueden tener diferentes opciones de foco disponibles.
```

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +20: Informes de situación concretos (como este) pueden ser temporalmente ignorados haciendo click con el botón derecho del ratón en su icono y seleccionando una de las opciones disponibles. Ciertos t
```suggestion
20: Informes de situación concretos (como este) pueden ser temporalmente ignorados haciendo clic con el botón derecho del ratón en su icono y seleccionando una de las opciones disponibles. Ciertos tipos de reportes pueden ser filtrados de manera permanente usando el menú de filtros en la parte inferior de esta pantalla. Estas pistas iniciales están agrupadas como [[encyclopedia BEGINNER_HINTS]] en la lista de filtros.
```

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +21: Puedes fijar un destino para una nave mientras está todavía en la cola de producción. Con la pantalla de producción abierta: haz click en el sistema destino en el mapa galáctico y haz click con e
```suggestion
21: Puedes fijar un destino para una nave mientras está todavía en la cola de producción. Con la pantalla de producción abierta: haz clic en el sistema destino en el mapa galáctico y haz click con el botón derecho del ratón sobre la nave en la cola de producción. Cuando aparezca el menú con las distintas opciones, elige 'Ir a' y entonces debería aparecer el nombre del sistema seleccionado al que quieres que viaje la nave tan pronto como esté construida.
```

2022-01-29 15:17 UTC, Oberlus commented on default/stringtables/es.txt
> +22: Seleccionar un systema y pulsar ALT-C proporciona un círculo de rango para ese sistema, haz zoom para comparar la distancia mirando el tamaño del medidor de distancia.
```suggestion
22: Seleccionar un sistema y pulsar ALT-C proporciona un círculo de rango para ese sistema, haz zoom para comparar la distancia mirando el tamaño de la barra de escala en la esquina superior izquierda del mapa.
```

I'm deliverately improving this hint for the Spanish version (the scale bar is not a distance meter indeed).

2022-01-29 15:18 UTC, Oberlus commented
I just found the "insert suggestion" option :dancing_men:

2022-01-30 09:19 UTC, rsf92 commented
I squashed all the suggested commits @Oberlus  and fixed the Focus thing on my own on a separate commit

2022-01-30 09:39 UTC, Oberlus commented
> I squashed all the suggested commits @Oberlus and fixed the Focus thing on my own on a separate commit

There are a few suggested corrections pending, like this one:

https://github.com/freeorion/freeorion/pull/3680/files#r795063339

Check out for "creciciemto", "conocedr"...

2022-01-30 11:50 UTC, rsf92 commented
Okay, now,  I think

2022-01-30 12:22 UTC, Oberlus approved these changes

2022-01-30 21:59 UTC, merged