Update BUILD.md
freeorion/freeorion pull request #4410
Opened 2023-02-28 22:41 UTC by geoffthemedio

-link to SDK13
-tweak Visual Studio URL

2023-03-01 08:56 UTC, geoffthemedio commented
@o01eg does this look accurate to you?

2023-03-01 12:26 UTC, o01eg commented
@geoffthemedio Yes, looks fine. Still it quite sad memory requirements now twice of previous.

2023-03-01 13:13 UTC, geoffthemedio commented
> memory requirements now twice of previous.

Probably not actually needed unless running parallel builds...

2023-03-03 13:49 UTC, Vezzra requested changes
In addition to the suggested changes, all "Mac OSX" / "Mac OS X" etc. occurences should be replaced by "macOS".

2023-03-03 13:49 UTC, Vezzra commented on BUILD.md
>  Mac OS X 10.9 SDK with Xcode 6.4 or later on Mac OS X.
```suggestion
macOS 10.12 SDK with Xcode 10.1 or later on macOS.
```

2023-03-03 13:49 UTC, Vezzra commented on BUILD.md
> +FreeOrion should compile on Windows 8.1 (or later), Mac OS X 10.10 (or later) and
```suggestion
FreeOrion should compile on Windows 8.1 (or later), macOS 10.12 (or later) and
```

2023-03-05 11:43 UTC, Vezzra approved these changes
LGTM.

As this is marked for cherry picking, shall I merge this before I produce RC2 on Tuesday (if it hasn't been merged by then)?

2023-03-05 12:07 UTC, geoffthemedio commented
yes... updated instructions are relevant for v0.5

2023-03-07 11:55 UTC, merged