Move artefact generation to the cmake-2022
freeorion/freeorion pull request #4480
Opened 2023-04-15 07:57 UTC by Cjkjvfnby

I move the section that builds binaries from 2019 to 2020.

At some point, we will decide to remove 2019 and this change will make it easier. 

FYI: @o01eg @geoffthemedio

2023-04-15 08:09 UTC, geoffthemedio commented
I'm not sure what this does...

2023-04-15 12:22 UTC, o01eg commented
@geoffthemedio I suppose intention was to generate and publish binaries with MS VS 2022 instead of MS VS 2019.

2023-04-15 12:25 UTC, o01eg requested changes
Key decryption should be moved also to 2022 part.

2023-04-15 13:41 UTC, geoffthemedio commented
I have no relevant input then.

2023-04-15 15:54 UTC, o01eg approved these changes

2023-04-16 09:35 UTC, Vezzra commented
Any action required from my part...?

2023-04-17 20:18 UTC, Cjkjvfnby commented
>Any action/input required from my part...?

No, this is more like refactoring.  Same features as before but from a different workflow run.

2023-04-17 20:26 UTC, merged