[focs] Convert Biegegoo
freeorion/freeorion pull request #4591
Opened 2023-06-30 16:39 UTC by Cjkjvfnby

This is the initial step of the conversion.  

I just converted the file without comparing checksums and dumps. 

No errors in AI logs.

2023-06-30 19:19 UTC, o01eg requested changes
Difference in dump: [1.diff.txt](https://github.com/freeorion/freeorion/files/11919841/1.diff.txt)

Lost `Native` marker, `PRIMITIVE` check, turn high check. Not sure about `accountinglabel = "GREAT_TROOPS_LABEL"`, I seemed to be broken in old FOCS macroses so I commented out such things.

2023-06-30 20:07 UTC, Cjkjvfnby commented
I have pushed fixes.  

Do you think we could remove all or some  `accountinglabel` things from FOCS?

2023-07-04 19:38 UTC, o01eg commented
Could you rebase it over `master` so it could be tested with fixed descriptions in effects?

> Do you think we could remove all or some `accountinglabel` things from FOCS?

I don't know how it works and why some of them disabled. @geoffthemedio, do you known anything about it?

2023-07-04 22:10 UTC, Cjkjvfnby commented
> Could you rebase it over master so it could be tested with fixed descriptions in effects?

Done.

2023-07-04 23:34 UTC, agrrr3 commented
> > Do you think we could remove all or some `accountinglabel` things from FOCS?

@Cjkjvfnby why would you want that?

> 
> I don't know how it works and why some of them disabled. @geoffthemedio, do you known anything about it?

The accountinglabels are UI descriptions for the effects. So, e.g.  hover the mouse over the troops on a supertesters' planet, and you will find a line "Super Testers Great Ground Troops +X.XX"

I am not aware what is disabled.

2023-07-05 05:17 UTC, o01eg requested changes

2023-07-05 05:17 UTC, o01eg commented on default/scripting/species/SP_BEIGEGOO.focs.py
> +            activation=Planet() & Turn(hight=0) & (GalaxyMaxAIAggression >= 1) & (GalaxyMonsterFrequency >= 1),
Should be `high`, not `hight`.

2023-07-05 07:52 UTC, geoffthemedio commented
> > I don't know how it works and why some of them disabled. @geoffthemedio, do you known anything about it?
> 
> The accountinglabels are UI descriptions for the effects. So, e.g. hover the mouse over the troops on a supertesters' planet, and you will find a line "Super Testers Great Ground Troops +X.XX"

More specifically, they replace the defaults. For example, left with and right without an accounting label specified for the imperial palace stability effect:

![accounting label](https://github.com/freeorion/freeorion/assets/11386908/9a479a2c-ff72-4492-8f3b-eed632fe3bf7)

2023-07-05 16:54 UTC, Cjkjvfnby commented on default/scripting/species/SP_BEIGEGOO.focs.py
> +            activation=Planet() & Turn(hight=0) & (GalaxyMaxAIAggression >= 1) & (GalaxyMonsterFrequency >= 1),
This looks like a critical issue, we need to prevent such cases.  I think I could address it with the focs skeletons and some linters.

2023-07-05 17:08 UTC, Cjkjvfnby commented
Summary on account label: old macros just ignore this field, so technically we could remove it from here.
New Implementation allows this field to be parsed and used. 

We have a couple of options: 
1) Remove these labels from a converted script (maybe even support for some objects in the parser)
2) Start using them (I hope they have some meaning in the current context)
3) Totally remove this feature and make defaults great. 

I'd vote for the 3 one.  On the screenshot, both versions look good.   And `accountinglabel` brings extra complexity for FOCS writers.

We don't need to make a decision right now, this PR could be merged without waiting for this.

```
GREAT_DEFENSE_TROOPS
'''[[BASIC_DEFENSE_TROOPS]]

    EffectsGroup
        description = "GREAT_DEFENSE_TROOPS_DESC"
        scope = Source
        activation = Planet
        effects = SetMaxTroops value = Value * 2
        accountinglabel = "GREAT_TROOPS_LABEL"

[[UNSTABLE_REBEL_TROOPS]]

[[PROTECTION_FOCUS_TROOPS]]
'''
```

2023-07-05 17:09 UTC, o01eg approved these changes

2023-07-05 17:14 UTC, o01eg commented on default/scripting/species/SP_BEIGEGOO.focs.py
> +            activation=Planet() & Turn(hight=0) & (GalaxyMaxAIAggression >= 1) & (GalaxyMonsterFrequency >= 1),
Yes, there should be check of available keywords in C++ code which isn't yet implemented.

2023-07-05 17:15 UTC, merged

2023-07-05 19:03 UTC, geoffthemedio commented
>     3. Totally remove this feature and make defaults great.

Making defaults "great" is probably not possible...

> On the screenshot, both versions look good.

Many people disagree, which was/is the motivation for this feature. In the case in the screenshot, the default effect description doesn't give any indication what the reason for the effect is. It just indicates that it has something to do with the imperial palace. But that's actually just an implementation detail; the effect happens to be attached to the imperial palace, but that's not the point of the effect and describing it as just coming from the palace loses the meaning for the player.

> And `accountinglabel` brings extra complexity for FOCS writers.

It's an important and optional feature that improves the UI description of effects to players. That is worth some extra (optional!) complexity...

2023-07-05 20:48 UTC, agrrr3 commented
> Summary on account label: old macros just ignore this field,

? uhm ? No. That is simply and plainly wrong. The field is used in the UI.

2023-07-05 20:53 UTC, agrrr3 commented
> We have a couple of options:

as said I am not sure what your problem is. But if you think it is too much boilerplate, with the macro features (especially with the string manipulation have with python) one can reduce that. So

4) Make it a single function which takes the level and the multiplier as parameters and use that function for all troop levels.