[FOCS] Convert CELESTEPHYTE
freeorion/freeorion pull request #4603
Opened 2023-07-06 21:53 UTC by Cjkjvfnby

- Covert CELESTEPHYTE 
- Improve skeletons

This code requires double, but I don't know how to pass it.
```python
SetCapacity(partname="GT_TROOP_POD", value=0.0),
```

```
PythonCommon.cpp:101 : TypeError: No registered converter was able to produce a C++ rvalue of type struct value_ref_wrapper<double> from this Python object of type float
23:48:21.151623 {0x00002070} [error] ai : PythonParser.cpp:442 : Unable to parse module file j:/projects/freeorion/default\scripting\species\common\troops.py
```

2023-07-07 09:03 UTC, o01eg requested changes
Tests get failed with: 
```
  2: [2023-07-06 23:21:36.018503] [0x000003f4] [info]    Couldn't find file for module spec focs
  2: [2023-07-06 23:21:36.018503] [0x000003f4] [info]    Traceback (most recent call last):
  2: [2023-07-06 23:21:36.018503] [0x000003f4] [info]      File "<string>", line 1, in <module>
  2: [2023-07-06 23:21:36.018503] [0x000003f4] [info]    ModuleNotFoundError: No module named 'focs'
  2: [2023-07-06 23:21:36.018503] [0x000003f4] [info]    Unable to parse data file D:\a\freeorion\freeorion\build\Release\test-scripting\species\SP_ABADDONI.focs.py
```

You should copy `focs` to `test-scripting` because some tests use it as root for its python modules.

2023-07-07 20:19 UTC, Cjkjvfnby commented
> Tests get failed with:

Is it on your machine? I could not find it in logs.

2023-07-07 21:17 UTC, o01eg commented
> Is it on your machine? I could not find it in logs.

No, it's in Github Actions CI.

2023-07-08 06:20 UTC, o01eg requested changes
There is difference in dump: [1.txt](https://github.com/freeorion/freeorion/files/11988720/1.txt)

I'll fix `SetCapacity` but it different in `NO_OFFENSE_TROOPS_DESC` effect

```diff
                 Source
             activation =
-                And [
-                    Ship
-                    Or [
+                Or [
+                    And [
+                        Ship
                         DesignHasPart name = "GT_TROOP_POD"
-                        DesignHasPart name = "GT_TROOP_POD_2"
-
                     ]
+                    DesignHasPart name = "GT_TROOP_POD_2"
+
                 ]
             accountinglabel = "NO_OFFENSIVE_TROOPS_LABEL"
             stackinggroup = "NO_OFFENSIVE_TROOPS_STACK"
```

2023-07-09 11:16 UTC, Cjkjvfnby commented
I have force-pushed changes and added CHATO species

Fix for the compilation was done n a separate branch.
Skeletons update was done in a separate branch

2023-07-14 19:53 UTC, o01eg commented
Could you rebase it over `master`? I've merged `Armed` support. I suppose it better not mix completed species and uncompleted.

Also it should use `.focs.py` extension, not `.focs..py`

2023-07-14 22:52 UTC, Cjkjvfnby commented
> Also it should use .focs.py extension, not .focs..py

Good catch.  

Rebased.

2023-07-15 00:10 UTC, Cjkjvfnby commented
There is a couple of problems I have with converting some other species:

---

**SP_FULVER**, common/telepathic.py
```
effects=SetVisibility(empire=Source.Owner, visibility=MaxOf(int, Basic, Value)), 


Traceback (most recent call last):
01:14:06.147114 {0x000029cc} [error] ai : PythonCommon.cpp:101 :   File "<string>", line 104, in <module>
01:14:06.147114 {0x000029cc} [error] ai : PythonCommon.cpp:101 :   File "<string>", line 28, in PRECOGNITIVE_DETECTION
01:14:06.147114 {0x000029cc} [error] ai : PythonCommon.cpp:101 : TypeError: No registered converter was able to produce a C++ rvalue of type int from this Python object of type __Visibility
```
---

**SP_EAXAW**, xenophobic.py

I don't know how to convert
<details><summary>This code</summary>
<p>

```
XENOPHOBIC_SELF
'''
        // Give the concentration camp tech at game start
        EffectsGroup
            scope = Source
            activation = Turn high = 0
            effects = GiveEmpireTech name = "CON_CONC_CAMP"

        // Xenophobic Frenzy: stability malus for xenophobic species nearby other species
        EffectsGroup
            scope = Source
            activation = Number low = 1 condition = [[CONDITION_OTHER_SPECIES_NEARBY]]
            stackinggroup = "XENOPHOBIC_LABEL_SELF"
            accountinglabel = "XENOPHOBIC_LABEL_SELF"
            priority = [[TARGET_AFTER_SCALING_PRIORITY]]
            effects = SetTargetHappiness value = Value
                + (NamedReal name = "XENOPHOBIC_TARGET_STABILITY_PERJUMP" value = -0.5)
                * Statistic Sum
                    value = (1 + NamedIntegerLookup name = "XENOPHOBIC_MAX_JUMPS"
                        - JumpsBetween object = Target.ID object = LocalCandidate.ID)
                    condition = And [
                        Planet
                        VisibleToEmpire empire = Source.Owner
                        Species
                        Not Species name = Source.Species
                        Not HasTag name = "LOW_BRAINPOWER"
                        Not Contains Building name = "BLD_CONC_CAMP"
                        Or [
                            Not OwnedBy empire = RootCandidate.Owner
                            Not EmpireHasAdoptedPolicy empire = Source.Owner name = "PLC_RACIAL_PURITY"
                        ]
                        WithinStarlaneJumps jumps = (NamedIntegerLookup name = "XENOPHOBIC_MAX_JUMPS") condition = Source
                    ]

        // Pop malus for self-sustaining xenophobic species based on the number of nearby planets with other species
        EffectsGroup
            scope = Source
            activation = And [
                Planet
                HasTag name = "SELF_SUSTAINING"
                (0 < [[XENOPHOBIC_SELFSUSTAINING_QUALIFYING_PLANET_COUNT]])
            ]
            stackinggroup = "XENOPHOBIC_POP_SELF"
            accountinglabel = "XENOPHOBIC_LABEL_SELF"
            priority = [[TARGET_POPULATION_LAST_BEFORE_OVERRIDE_PRIORITY]]

            effects = SetTargetPopulation value = Value + max(
                -3 * Target.HabitableSize,  // Cap malus at the self-sustaining bonus
                Target.HabitableSize * (NamedReal name = "XENOPHOBIC_TARGET_POPULATION_PERJUMP" value = -0.2)
                * Statistic Sum
                    value = (1 + NamedIntegerLookup name = "XENOPHOBIC_MAX_JUMPS"
                        - JumpsBetween object = Target.ID object = LocalCandidate.ID)
                    condition = And [
                        Planet
                        Species
                        Not Species name = Source.Species
                        Not HasTag name = "LOW_BRAINPOWER"
                        WithinStarlaneJumps jumps = (NamedIntegerLookup name = "XENOPHOBIC_MAX_JUMPS") condition = Source
                    ]
                )
'''
```
</p>
</details> 

<details><summary>With this conversion</summary>
<p>

```python
EffectsGroup(
        scope=IsSource,
        activation=Planet()
        & HasTag(name="SELF_SUSTAINING")
        & (0 < XENOPHOBIC_SELFSUSTAINING_QUALIFYING_PLANET_COUNT()),
        stackinggroup="XENOPHOBIC_POP_SELF",
        accountinglabel="XENOPHOBIC_LABEL_SELF",
        priority=TARGET_POPULATION_LAST_BEFORE_OVERRIDE_PRIORITY,
        effects=SetTargetPopulation(
            value=Value
            + MaxOf(
                float,
                -3 * Target.HabitableSize,  # Cap malus at the self-sustaining bonus
                Target.HabitableSize
                * NamedReal(name="XENOPHOBIC_TARGET_POPULATION_PERJUMP", value=-0.2)
                * Statistic(
                    float,
                    Sum,
                    value=1
                    + NamedIntegerLookup(name="XENOPHOBIC_MAX_JUMPS")
                    - JumpsBetween(Target.ID, LocalCandidate.ID),
                    condition=Planet()
                    & HasSpecies()
                    & ~HasSpecies(name=[Source.Species])
                    & ~HasTag(name="LOW_BRAINPOWER")
                    & WithinStarlaneJumps(jumps=NamedIntegerLookup(name="XENOPHOBIC_MAX_JUMPS"), condition=IsSource),
                ),
            )
        ),
    ),
```

</p>
</details> 

Gives: 

```
01:14:06.137111 {0x000029cc} [error] ai : PythonCommon.cpp:101 : TypeError: unsupported operand type(s) for -: 'ValueRefDouble' and 'ValueRefInt'
```
In the line `value=1`  (after `Sum`).

2023-07-17 21:10 UTC, Cjkjvfnby commented
I have pushed a bunch of species I have converted so far.

2023-07-20 08:05 UTC, o01eg commented
`SP_CELESTEPHYTE`: `SetCapacity` was fixed so it doesn't requires `Value`.
`SP_CHATO`: Good.
`SP_CRAY`: mistyped `stackinggroup = "SP_CRAY)_TOWARDS_TARGET_OPINION_OF_EMPIRE"`, additional `accountinglabel = "GOOD_TROOPS_LABEL"`, and bad industry misses:
```
                    Planet
                    TargetIndustry low = 0.000000
                    Happiness low = 0.000000
```
`SP_CYNOS`: mistyped `stackinggroup = "SP_CYNOS)_TOWARDS_TARGET_OPINION_OF_EMPIRE"`, additional `accountinglabel = "GOOD_TROOPS_LABEL"`
`SP_DERTHREAN`: mistyped `stackinggroup = "SP_DERTHREAN)_TOWARDS_TARGET_OPINION_OF_EMPIRE"`, `SetCapacity` with `Value`
...

Could you split out `SP_CHATO` and macroses to separate PR so it could be merged while other will be fixed?

2023-07-20 18:41 UTC, Cjkjvfnby commented
I'm on vacation, out of my computer. Feel free to extract it yourself, or lets vait till 31 of July

2023-07-30 06:13 UTC, Cjkjvfnby commented
> SP_CELESTEPHYTE: SetCapacity was fixed so it doesn't requires Value.

Done.

> mistyped stackinggroup = "...)_TOWARDS_TARGET_OPINION_OF_EMPIRE"

Done.

> accountinglabel = "GOOD_TROOPS_LABEL"

Removed accounting label from defence troops.  Should I remove it from offence as well?

> Could you split out SP_CHATO and macroses to separate PR so it could be merged while other will be fixed?

Removed chato from this PR.

2023-07-30 07:34 UTC, o01eg requested changes
`SP_CELESTEPHYTE`: Had `SetCapacity partname = "GT_TROOP_POD" value = 0.000000` became `SetCapacity partname = "GT_TROOP_POD" value = Value`
`SP_CRAY`: Bad industry still misses: 
```
                    Planet
                    TargetIndustry low = 0.000000
                    Happiness low = 0.000000
```
`SP_CYNOS`: Good.
`SP_DERTHREAN`: Had `SetCapacity partname = "GT_TROOP_POD" value = 0.000000`, became `SetCapacity partname = "GT_TROOP_POD" value = Value`

2023-07-30 07:46 UTC, Cjkjvfnby commented
> SP_CRAY: Bad industry still misses:

it was `and` instead of `&`, can we report such things in logs?

```diff
-        activation=Planet() & TargetIndustry(low=0) & Happiness(low=0) and Focus(type=["FOCUS_INDUSTRY"]),
+        activation=Planet() & TargetIndustry(low=0) & Happiness(low=0) & Focus(type=["FOCUS_INDUSTRY"]),
```

2023-07-30 08:00 UTC, o01eg commented
> it was `and` instead of `&`, can we report such things in logs?

No, `and` uses Python short-circuit rules and not visible from C++ code.

> Removed accounting label from defence troops. Should I remove it from offence as well?

No, they are presented in old dump.

2023-07-30 08:06 UTC, o01eg commented
`SP_CELESTEPHYTE`, `SP_CRAY`, and `SP_DERTHREAN` are good too. Could you split out completed species to separate PR too?

2023-07-30 08:27 UTC, o01eg commented
Also could you open separate PR for Fulver so I'll try to solve `MaxOf` for `Visibility`?

2023-07-31 19:16 UTC, Cjkjvfnby commented
FULIVER is in a separate branch.  https://github.com/freeorion/freeorion/pull/4651 

What would be Python versions for `MinimumNumberOf` and `Field` in the SP_NIGHTSIDERS.focs

```python
EffectsGroup(
            scope=MinimumNumberOf(
                number=1,
                sortkey=DirectDistanceBetween(target=Source.ID, source=LocalCandidate.ID),
                condition=Field(name=["FLD_METEOR_BLIZZARD"]),
            ),
            effects=MoveTowards(speed=5, target=IsSource),
        ),
```

2023-08-02 20:12 UTC, Cjkjvfnby commented
One more API mismatch.

```python
SetEmpireMeter(empire=Source.Owner, meter="METER_DETECTION_STRENGTH", value=200)
```

Fails with:
```
PythonCommon.cpp:101 : TypeError: No registered converter was able to produce a C++ rvalue of type struct value_ref_wrapper<double> from this Python object of type int
PythonParser.cpp:358 : Unable to parse data file j:/projects/freeorion/default\scripting/species\SP_SUPERTEST.focs.py
```

The same problem with using float as well.  I think we should support both float and int or only float.

2023-08-02 20:15 UTC, Cjkjvfnby commented
@o01eg Species in this branch do not produce any errors.  Could you check if we could merge them?

2023-08-13 09:34 UTC, Cjkjvfnby commented
@o01eg , I have rebased on the latest master.   Could you check if we could merge some species of these 17 converted to master?

2023-08-13 17:44 UTC, o01eg commented
`SP_EXOBOT`: Good.
`SP_EXPERIMENTOR`: Good.
`SP_FIFTYSEVEN`: Good.
`SP_FURTHEST`: Good.
`SP_GEORGE`: Good.

2023-08-14 00:51 UTC, Cjkjvfnby commented
I have extracted mentioned species to a separate review.  https://github.com/freeorion/freeorion/pull/4680

2023-08-16 21:21 UTC, Cjkjvfnby commented
Have detected some space errors in the code, will wait until https://github.com/freeorion/freeorion/pull/4683 is merged to push my fixes.

2023-08-17 21:55 UTC, Cjkjvfnby commented
@o01eg , I have pushed updated species, including all missed coma fixes.

2023-08-19 23:03 UTC, Cjkjvfnby commented
Rebased on master added more species that are ready.

2023-08-29 08:49 UTC, o01eg commented
`SP_ETTY`:
Was
```
            activation =
                (GameRule name = "RULE_BASELINE_PLANET_STABILITY" != 0)
```
became
```
            activation =
                And [
                    Unowned
                    (GameRule name = "RULE_BASELINE_PLANET_STABILITY" != 0)
                ]
```

and 

was
```
            effects = [
                SetSpeciesEmpireOpinion empire = Target.Owner
                SetSpeciesEmpireOpinion empire = Target.Owner
            ]
```
became
```
            effects = [
                NoOp
                SetSpeciesEmpireOpinion empire = Target.Owner
                SetSpeciesEmpireOpinion empire = Target.Owner
            ]
```

I suppose it need another rebase on `master`. Did you tried `fo_unittest_parse.exe` from weekly test builds?

2023-08-29 12:49 UTC, geoffthemedio commented
> became
> 
> ```
>             effects = [
>                 NoOp
>                 SetSpeciesEmpireOpinion empire = Target.Owner
>                 SetSpeciesEmpireOpinion empire = Target.Owner
>             ]
> ```

What does "became" mean here? the `NoOp` effect presumably isn't necessary...

2023-08-29 13:22 UTC, o01eg commented
@geoffthemedio It's a comparison of dumps.

2023-08-29 16:31 UTC, Cjkjvfnby commented
> I suppose it need another rebase on master. 

I'll do it.

> Did you tried fo_unittest_parse.exe from weekly test builds?

I did not know about this file.  I run it and nothing happens.  Could you share any instructions?

2023-08-29 16:41 UTC, Cjkjvfnby commented
>    NoOp

This is a change in the macros file since this branch was created.  https://github.com/freeorion/freeorion/commit/9a8521b02d1e51c6c02a064131bf72c5fc735ad6

2023-08-29 16:44 UTC, Cjkjvfnby commented
Pushed the latest version with fixes.

2023-08-29 17:54 UTC, o01eg commented
> I did not know about this file. I run it and nothing happens. Could you share any instructions?

You can download fresh weekly test build binaries, put them to repository. Not sure about correct syntax on Windows but on Linux this command saves species dump to file:

```bash
FO_CHECKSUM_SPECIES_NAME=SP_BEIGEGOO ./fo_unittest_parse --run_test=TestPythonParser/parse_species_full --log_level=message 2>&1 >file.dump
```

Without environment options and arguments it simply runs tests and ensure tests pass.

2023-08-29 18:33 UTC, o01eg commented
`SP_ETTY`: Good.
`SP_HHHOH`: Good.
`SP_HUMAN`: descriptions have unneeded ")" at end.
`SP_KHAKTURIAN`: Good.
`SP_KILANDOW`: Good.
`SP_KOBUNTURA`: Good.
`SP_LAENFA`: Good.
`SP_LEMBALALAM`: Good.
`SP_MISIORLA`:

Was:

```
        EffectsGroup // from SP_MISIORLA
            description = "ULTIMATE_WEAPONS_DESC"
...
        EffectsGroup // from SP_MISIORLA
            description = "BAD_FUEL_DESC"
            scope =
                And [
                    Source
                    Ship
                ]
            accountinglabel = "BAD_FUEL_LABEL"
            priority = 110
            effects =
                SetMaxFuel value = Value - 0.500000
```

Became:
```
        EffectsGroup // from SP_MISIORLA
            description = "GOOD_WEAPONS_DESC"
...
        EffectsGroup // from SP_MISIORLA
            description = "BAD_FUEL_DESC"
            scope =
                And [
                    Source
                    Ship
                ]
            accountinglabel = "@1@_FUEL_LABEL"
            priority = 110
            effects =
                SetMaxFuel value = Value + -0.500000
```

2023-08-29 20:46 UTC, o01eg commented
Could you also extract correctly converted species to separate PR?

2023-08-29 20:53 UTC, Cjkjvfnby commented
> You can download fresh weekly test build binaries, put them to repository. Not sure about correct syntax on Windows but on Linux this command saves species dump to file:


I did it, but it did not talk to me. The exit code is 3221225781 and not stderr and stdout.

2023-08-29 20:55 UTC, o01eg commented
> I did it, but it did not talk to me. The exit code is 3221225781 and not stderr and stdout.

Did you extract both archives with binaries?

2023-08-29 21:00 UTC, Cjkjvfnby commented
> Did you extract both archives with binaries?

Where should I put game binaries?  

I have game installation (j:/games/freeorion) and the config redirects AI to my repo (j:/projects/freeorion/).

2023-08-29 21:17 UTC, o01eg commented
> Where should I put game binaries?

In a root folder with `default` and `test-scripting` subfolders.

2023-08-31 17:50 UTC, Cjkjvfnby commented
Extracted OK species to a separate review, lets merge it first.

https://github.com/freeorion/freeorion/pull/4723

2023-09-01 16:29 UTC, Cjkjvfnby commented
@o01eg , I have rebased changes to the latest master.

2023-09-07 21:48 UTC, Cjkjvfnby commented
@o01eg , I have rebased changes

2023-09-14 13:00 UTC, o01eg requested changes
There were changes in Influence and Research focus about Exobots

2023-09-14 18:54 UTC, Cjkjvfnby commented
> There were changes in Influence and Research focus about Exobots

Can we speed up a little bit with species conversion?  Solving this kind of conflict is unproductive.

2023-09-14 20:52 UTC, Cjkjvfnby commented
Updated, rebased

2023-09-15 07:29 UTC, o01eg commented
> Can we speed up a little bit with species conversion? Solving this kind of conflict is unproductive.

I've added test binaries to weeky test build so it could be checked quicker.

2023-09-15 17:10 UTC, Cjkjvfnby commented
> I've added test binaries to weeky test build so it could be checked quicker.

It exits with 3221225781.  Probably some dll are missed.

2023-09-18 06:11 UTC, o01eg commented
> It exits with 3221225781. Probably some dll are missed.

You need game binaries archive too. Test binaries includes only tests and Boost.Test library.

2023-09-18 17:30 UTC, Cjkjvfnby commented
If I run it via the UI, I see the message:

![изображение](https://github.com/freeorion/freeorion/assets/171597/31b99aff-b8f4-42cd-86d4-261c9885584a)

The file in the archive is `boost_unit_test_framework.lib`, not dll.

2023-09-19 14:16 UTC, o01eg commented
@Cjkjvfnby Should be fixed today weekly test build.

2023-09-19 19:27 UTC, Cjkjvfnby commented
> @Cjkjvfnby Should be fixed today weekly test build.

Now it runs. 

What is `m_test_scripting_dir` and how to set it? 

I have put both binaries and test folders in the game installation folder. 
And got this error:
```
D:/a/freeorion/freeorion/test/parse/ParserAppFixture.cpp:21: error: fatal error: in "TestPythonParser/parse_species_full": critical check fs::exists(m_test_scripting_dir) has failed
```

My persistent config is
```xml
<?xml version="1.0"?>
<XMLDoc>
    <resource>
    <path>j:\projects\freeorion\default</path>
    <stringtable>
      <path>j:\projects\FreeOrion\default\stringtables\en.txt</path>
    </stringtable>
  </resource>
</XMLDoc>
```

2023-09-20 06:36 UTC, o01eg commented
> What is m_test_scripting_dir and how to set it?

It should point to <repo>/test-scripting/ folder. You can add `--log_level=message` argument to see where test expects it.

2023-09-20 19:53 UTC, Cjkjvfnby commented
> It should point to /test-scripting/ folder. You can add --log_level=message argument to see where test expects it.

It's inside the game installation, not in the repository. I would like to have it as params or pass it via the Freeorion config file.

How this directory is related to the testing of changes in "default/scripting/species"?

2023-09-21 07:09 UTC, o01eg commented
> How this directory is related to the testing of changes in "default/scripting/species"?

Tests are shared for `default/scripting/` and `test-scripting/` so folders initialized together. Maybe I can split tests for those folders to separate groups.

2023-09-24 08:59 UTC, Cjkjvfnby commented
> Still it's quite strange, I supposed Windows uses folders relative to the executable and test-scripting is searched in fs::system_complete(GetBinDir()).

As I know you compile the game in the repository folder.  I work differently, I have the game installed with the Windows installer and configure the folder for AI in the `config.xml`.


It would be nice if this config is taken into account.

<details><summary>my config</summary>
<p>

```xml
<?xml version="1.0"?>
<XMLDoc>
    <resource>
    <path>j:\projects\freeorion\default</path>
    <stringtable>
      <path>j:\projects\FreeOrion\default\stringtables\en.txt</path>
    </stringtable>
  </resource>
</XMLDoc>
```

</p>
</details> 

I copied the code to the folders and the tests passed.  How do we get the diff of the species?

2023-09-25 08:56 UTC, o01eg commented
@Cjkjvfnby Next you need to run `fo_unittest_parse.exe` with environment `FO_CHECKSUM_SPECIES_NAME` of tested species and arguments `--run_test=TestPythonParser/parse_species_full --log_level=message`

2023-09-25 20:45 UTC, Cjkjvfnby commented
When I add the env variable, things don't work well.



```
*** 1 failure is detected in the test module "FreeOrion unit/coverage tests parser"
Running 1 test case...
:0: error: Entering test module "FreeOrion unit/coverage tests parser"
D:\a\freeorion\freeorion\test\parse\TestEnumParser.cpp:88: error: Test suite "TestEnumParser" is skipped because disabled
D:\a\freeorion\freeorion\test\parse\TestPythonParser.cpp:27: error: Entering test suite "TestPythonParser"
D:\a\freeorion\freeorion\test\parse\TestPythonParser.cpp:29: error: Test case "TestPythonParser/parse_game_rules" is skipped because disabled
D:\a\freeorion\freeorion\test\parse\TestPythonParser.cpp:39: error: Test case "TestPythonParser/parse_techs" is skipped because disabled
D:\a\freeorion\freeorion\test\parse\TestPythonParser.cpp:213: error: Test case "TestPythonParser/parse_species" is skipped because disabled
D:\a\freeorion\freeorion\test\parse\TestPythonParser.cpp:437: error: Test case "TestPythonParser/parse_techs_full" is skipped because disabled
D:\a\freeorion\freeorion\test\parse\TestPythonParser.cpp:475: error: Entering test case "parse_species_full"
Init parse tests j:/games/FreeOrion/fo_unittest_parse.exe
unknown location:0: error: fatal error: in "TestPythonParser/parse_species_full": memory access violation
D:\a\freeorion\freeorion\test\parse\TestPythonParser.cpp:475: error: last checkpoint: "parse_species_full" fixture ctor
Test is aborted
D:\a\freeorion\freeorion\test\parse\TestPythonParser.cpp:475: error: Leaving test case "parse_species_full"; testing time: 170us
Test is aborted
D:\a\freeorion\freeorion\test\parse\TestPythonParser.cpp:27: error: Leaving test suite "TestPythonParser"; testing time: 26us
Test is aborted
:0: error: Leaving test module "FreeOrion unit/coverage tests parser"; testing time: 7us
201
```

2023-09-26 08:42 UTC, o01eg commented
Could you try to get backtrace of memory access violation?

2023-09-27 20:15 UTC, Cjkjvfnby commented
> Could you try to get backtrace of memory access violation?

I have no idea how to do it, and no toolset installed.

2023-09-28 06:29 UTC, o01eg commented
@geoffthemedio Could you look into this crash?

2023-09-28 22:09 UTC, geoffthemedio commented
> @geoffthemedio Could you look into this crash?

There's a lot of messages in this thread so I'm not sure what to test. I tried, with master:
````
C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\build\Release>set FO_CHECKSUM_SPECIES_NAME=SP_HUMAN

C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\build\Release>fo_unittest_parse.exe --run_test=TestPythonParser/parse_species_full --log_level=message
Test setup error: no test cases matching filter or all test cases were disabled
````

With the pull request applied:
````
C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\buildceleste\Release>set FO_CHECKSUM_SPECIES_NAME=SP_CELESTEPHYTE

C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\buildceleste\Release>fo_unittest_parse.exe --run_test=TestPythonParser/parse_species_full --log_level=message
Test setup error: no test cases matching filter or all test cases were disabled
````

Log of same without the `--run_test=...` attached.
[test_parse_pr.log](https://github.com/freeorion/freeorion/files/12754262/test_parse_pr.log)

2023-09-28 22:13 UTC, geoffthemedio commented
On a hunch, I changed the name of the build directory (after having built) to have some Cyrillic characters in it and tried again:
````
C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\buildДЄЖ\Release>fo_unittest_parse.exe
Running 18 test cases...
[2023-09-29 00:12:07.081887] [0x00003394] [info]    Initializing FreeOrion Python interface
[2023-09-29 00:12:07.082887] [0x00003394] [info]    Python home set to C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\build???\Release
[2023-09-29 00:12:07.086906] [0x00003394] [info]    Unable to initialize Python interpreter
C:/Users/g_top/Desktop/SDK14_unbootstrapped/FreeOrion/test/parse/ParserAppFixture.cpp:12: error: fatal error: in "TestPythonParser/parse_game_rules": critical check m_python.Initialize() has failed
[2023-09-29 00:12:07.096908] [0x00003394] [info]    Initializing FreeOrion Python interface
[2023-09-29 00:12:07.098908] [0x00003394] [info]    Python home set to C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\build???\Release
[2023-09-29 00:12:07.102909] [0x00003394] [info]    Unable to initialize Python interpreter
C:/Users/g_top/Desktop/SDK14_unbootstrapped/FreeOrion/test/parse/ParserAppFixture.cpp:12: error: fatal error: in "TestPythonParser/parse_techs": critical check m_python.Initialize() has failed
[2023-09-29 00:12:07.114194] [0x00003394] [info]    Initializing FreeOrion Python interface
[2023-09-29 00:12:07.117194] [0x00003394] [info]    Python home set to C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\build???\Release
[2023-09-29 00:12:07.122196] [0x00003394] [info]    Unable to initialize Python interpreter
C:/Users/g_top/Desktop/SDK14_unbootstrapped/FreeOrion/test/parse/ParserAppFixture.cpp:12: error: fatal error: in "TestPythonParser/parse_species": critical check m_python.Initialize() has failed
[2023-09-29 00:12:07.130197] [0x00003394] [info]    Initializing FreeOrion Python interface
[2023-09-29 00:12:07.133198] [0x00003394] [info]    Python home set to C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\build???\Release
[2023-09-29 00:12:07.137200] [0x00003394] [info]    Unable to initialize Python interpreter
C:/Users/g_top/Desktop/SDK14_unbootstrapped/FreeOrion/test/parse/ParserAppFixture.cpp:12: error: fatal error: in "TestDefaultPythonParser/parse_techs_full": critical check m_python.Initialize() has failed
[2023-09-29 00:12:07.147202] [0x00003394] [info]    Initializing FreeOrion Python interface
[2023-09-29 00:12:07.150202] [0x00003394] [info]    Python home set to C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\build???\Release
[2023-09-29 00:12:07.155202] [0x00003394] [info]    Unable to initialize Python interpreter
C:/Users/g_top/Desktop/SDK14_unbootstrapped/FreeOrion/test/parse/ParserAppFixture.cpp:12: error: fatal error: in "TestDefaultPythonParser/parse_species_full": critical check m_python.Initialize() has failed

*** 5 failures are detected in the test module "FreeOrion unit/coverage tests parser"
````

2023-09-29 07:56 UTC, o01eg commented
> Test setup error: no test cases matching filter or all test cases were disabled

Test was renamed to `TestDefaultPythonParser/parse_species_full`

2023-09-29 09:38 UTC, geoffthemedio commented
````
C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\buildCEL\Release>set FO_CHECKSUM_SPECIES_NAME=SP_CELESTEPHYTE

C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\buildCEL\Release>fo_unittest_parse.exe --run_test=TestDefaultPythonParser/parse_species_full --log_level=message > parse_test.log

*** No errors detected

C:\Users\g_top\Desktop\SDK14_unbootstrapped\FreeOrion\buildCEL\Release>git branch --show-current
Cjkjvfnby-sa/convert-CELESTEPHYTE
````
[parse_test.log](https://github.com/freeorion/freeorion/files/12763177/parse_test.log)

2023-10-02 20:19 UTC, Cjkjvfnby commented
I am putting both binary files and test files to the game installation, copy test-scripting to it and run test. 
With the recent binaries and new test name the result is the same.  

My win folders does not have cyrilic or spaces. 

Is it possible to test code that it will print declarations during CI run both for focs.txt and py files?

2023-10-04 09:12 UTC, o01eg commented
I've add test of selected species dump https://github.com/freeorion/freeorion/pull/4763

2023-10-21 09:35 UTC, Cjkjvfnby commented
> I've add test of selected species dump


I don't think that my problem is related to the content.  It's more like a configuration/operation system.

You work in the same environment where you build the tool and the project.  And for me, I use compiled binaries.

Maybe you could just make it a part of the game itself?  Developing a tool in UNIX to make it run on a clean window machine, might be too complicated.

If text and py files are present for the same species,  print both of them, to the logs.  I'll do a Python tool to parse the logs and build a diff.

Or add a new argument to freeorion.exe that just dumps all species to log and exits.

2023-10-21 10:44 UTC, geoffthemedio commented
> Or add a new argument to freeorion.exe that just dumps all species to log and exits.

Perhaps: #4768

2023-10-23 22:21 UTC, Cjkjvfnby commented
I am back on track.  I have access to the diff now, thanks for the changes in https://github.com/freeorion/freeorion/pull/4768

I'll put instructions and helper scripts into the repo a bit later when it becomes more stable.

A couple of reviews to make the diff less noisy
- https://github.com/freeorion/freeorion/pull/4771
- https://github.com/freeorion/freeorion/pull/4770

It looks like SetFocus is not supported in Python.  https://github.com/freeorion/freeorion/commit/3c8af7e6c9f5f802038e126f999a5e31403aec05  @geoffthemedio

2023-10-26 15:01 UTC, geoffthemedio commented
> It looks like SetFocus is not supported in Python. [3c8af7e](https://github.com/freeorion/freeorion/commit/3c8af7e6c9f5f802038e126f999a5e31403aec05) @geoffthemedio

that effectsgroup was included only by accident anyway... #4777

2023-10-30 18:47 UTC, Cjkjvfnby commented
Pushed changes, looks good.

<details><summary>Diff</summary>
<p>

```diff
--- SP_LEMBALALAM.txt.master
+++ SP_LEMBALALAM.txt.sa-convert-CELESTEPHYTE
@@ -361,7 +361,7 @@
             accountinglabel = "VERY_BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + -0.333333 * abs(Value)
+                SetTargetInfluence value = Value + -0.330000 * abs(Value)
         EffectsGroup // from SP_LEMBALALAM
             scope =
                 Source
--- SP_MUURSH.txt.master
+++ SP_MUURSH.txt.sa-convert-CELESTEPHYTE
@@ -407,7 +407,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_MUURSH
             scope =
                 Source
--- SP_THENIAN.txt.master
+++ SP_THENIAN.txt.sa-convert-CELESTEPHYTE
@@ -1758,8 +1758,8 @@
                 SetPopulation value = Value * 0.500000
                 GenerateSitRepMessage
                     message = "EFFECT_THENIAN_NATURAL_DIEOFF" icon = icons/sitrep/colony_starvation.png
-                    parameters = tag = planet data = (Target.ID) // StringCast{int}
-                        
+                    parameters = [  tag = tag data = "planet"  tag = data data = (Target.ID) // StringCast{int}
+                         ]
                     affiliation = TheEmpire
                     empire = Target.Owner
             ]
--- SP_MISIORLA.txt.master
+++ SP_MISIORLA.txt.sa-convert-CELESTEPHYTE
@@ -421,7 +421,7 @@
             accountinglabel = "BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (0.800000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + -0.200000 * abs(Value)
         EffectsGroup // from SP_MISIORLA
             description = "BAD_STOCKPILE_DESC"
             scope =
--- SP_OURBOOLS.txt.master
+++ SP_OURBOOLS.txt.sa-convert-CELESTEPHYTE
@@ -407,7 +407,7 @@
             accountinglabel = "VERY_BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (2.000000 / 3.000000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + -0.330000 * abs(Value)
         EffectsGroup // from SP_OURBOOLS
             scope =
                 Source
--- SP_SCYLIOR.txt.master
+++ SP_SCYLIOR.txt.sa-convert-CELESTEPHYTE
@@ -408,7 +408,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_SCYLIOR
             scope =
                 Source
--- SP_HUMAN.txt.master
+++ SP_HUMAN.txt.sa-convert-CELESTEPHYTE
@@ -394,7 +394,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_HUMAN
             scope =
                 Source
--- SP_PHINNERT.txt.master
+++ SP_PHINNERT.txt.sa-convert-CELESTEPHYTE
@@ -357,7 +357,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_PHINNERT
             scope =
                 Source
--- SP_SLY.txt.master
+++ SP_SLY.txt.sa-convert-CELESTEPHYTE
@@ -407,7 +407,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_SLY
             description = "GREAT_STOCKPILE_DESC"
             scope =
--- SP_SILEXIAN.txt.master
+++ SP_SILEXIAN.txt.sa-convert-CELESTEPHYTE
@@ -382,7 +382,7 @@
             accountinglabel = "VERY_BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (2.000000 / 3.000000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + -0.330000 * abs(Value)
         EffectsGroup // from SP_SILEXIAN
             scope =
                 Source
--- SP_UGMORS.txt.master
+++ SP_UGMORS.txt.sa-convert-CELESTEPHYTE
@@ -422,7 +422,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_UGMORS
             scope =
                 Source
--- SP_TAEGHIRUS.txt.master
+++ SP_TAEGHIRUS.txt.sa-convert-CELESTEPHYTE
@@ -394,7 +394,7 @@
             accountinglabel = "GREAT_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.500000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.500000 * abs(Value)
         EffectsGroup // from SP_TAEGHIRUS
             scope =
                 Source
--- SP_KILANDOW.txt.master
+++ SP_KILANDOW.txt.sa-convert-CELESTEPHYTE
@@ -407,7 +407,7 @@
             accountinglabel = "VERY_BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + -0.333333 * abs(Value)
+                SetTargetInfluence value = Value + -0.330000 * abs(Value)
         EffectsGroup // from SP_KILANDOW
             scope =
                 Source
--- SP_TRITH.txt.master
+++ SP_TRITH.txt.sa-convert-CELESTEPHYTE
@@ -394,7 +394,7 @@
             accountinglabel = "GREAT_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.500000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.500000 * abs(Value)
         EffectsGroup // from SP_TRITH
             scope =
                 Source
--- SP_NYMNMN.txt.master
+++ SP_NYMNMN.txt.sa-convert-CELESTEPHYTE
@@ -347,7 +347,7 @@
             accountinglabel = "BAD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (0.800000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + (-1.200000) * abs(Value)
         EffectsGroup // from SP_NYMNMN
             scope =
                 Source
--- SP_SUPER_TEST.txt.master
+++ SP_SUPER_TEST.txt.sa-convert-CELESTEPHYTE
@@ -422,7 +422,7 @@
             accountinglabel = "GREAT_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.500000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.500000 * abs(Value)
         EffectsGroup // from SP_SUPER_TEST
             description = "GREAT_STOCKPILE_DESC"
             scope =
--- SP_VOLP.txt.master
+++ SP_VOLP.txt.sa-convert-CELESTEPHYTE
@@ -392,7 +392,7 @@
             accountinglabel = "GOOD_INFLUENCE_LABEL"
             priority = 105
             effects =
-                SetTargetInfluence value = Value + (1.250000 - 1.000000) * abs(Value)
+                SetTargetInfluence value = Value + 0.250000 * abs(Value)
         EffectsGroup // from SP_VOLP
             scope =
                 Source
```

</p>
</details>

2023-11-01 04:24 UTC, o01eg approved these changes

2023-11-01 04:25 UTC, merged