[FOCS] WIP convert buildings (expected to fail builds)
freeorion/freeorion pull request #4867
Opened 2024-02-10 10:09 UTC by Cjkjvfnby

This is my progress on building conversion so far. 

It won't pass the tests, because some entries are missed (full list is here: https://github.com/freeorion/freeorion/issues/4815). 

I propose the following process: 

This branch is used for testing if FOCS runs without errors. I am sure that diff does not match, but at this point, we should not care about it, when all C++ API will be in place, I'll fix it. 

All changes for C++ part could be done as separate PR's, I propose just merging them to master, it's easy for me to test it that way. 

It's ok to merge and push changes to this branch.  In general, I don't plan to merge it at the end, I'll extract things that work as separate PR and merge them.  So maybe we could avoid rebates to not mess up with our own versions.

2025-02-10 18:21 UTC, o01eg commented
@Cjkjvfnby Could you rebase branch and check it again?

2025-02-10 18:51 UTC, Cjkjvfnby commented
It will take me some time,  I am a bit busy with other things, and lost context.   I'll try to do it by the end of the week.

2025-02-16 01:35 UTC, Cjkjvfnby commented
I have a couple of problems listed here:
https://github.com/freeorion/freeorion/issues/5105

Fixes for the parser https://github.com/freeorion/freeorion/pull/5104

2025-02-16 06:49 UTC, o01eg requested changes

2025-02-16 06:49 UTC, o01eg commented on default/scripting/buildings/buildings.py
> +    & ~StarlaneToWouldCrossExistingStarlane(condition=Object(id=Source.SystemID))
It accepts `from_` argument have like in `HasStarlane` or other places where were `from` in old FOCS

2025-02-16 06:49 UTC, o01eg commented on default/scripting/buildings/buildings.py
> +            & ~Contains(scope=IsSource)
It accepts single argument by position not by name like in `ContainedBy`

2025-02-16 08:04 UTC, o01eg requested changes

2025-02-16 08:04 UTC, o01eg commented on default/scripting/buildings/CULTURE_ARCHIVES.focs.py
> +    location=Described(description="NOWHERE", condition=~All),
It is `IsAnyObject`.

2025-02-16 09:56 UTC, o01eg requested changes

2025-02-16 09:56 UTC, o01eg commented on default/scripting/buildings/GAIA_TRANS.focs.py
> +        & IsBuilding(name=["BLD_TERRAFORM_BEST"])
Here should be `Enqueued`

2025-02-20 04:13 UTC, o01eg requested changes

2025-02-20 04:13 UTC, o01eg commented on default/scripting/buildings/FIELD_REPELLOR.focs.py
> +                    "FLD_SUBSPACE_RIFT" "FLD_VOID_RIFT",
Missing comma, Python treats it as a single string.

2025-02-20 10:33 UTC, geoffthemedio commented on default/scripting/buildings/buildings.py
> +            & ~Contains(scope=IsSource)
Why is the parameter named `scope`?

2025-02-20 10:35 UTC, geoffthemedio commented on default/scripting/buildings/CULTURE_ARCHIVES.focs.py
> +    location=Described(description="NOWHERE", condition=~All),
Or `None` since it's `~`?

2025-02-20 10:39 UTC, o01eg commented on default/scripting/buildings/CULTURE_ARCHIVES.focs.py
> +    location=Described(description="NOWHERE", condition=~All),
It was `location = Described description = "NOWHERE" condition = Not All` before not sure why.

2025-02-20 10:57 UTC, Cjkjvfnby commented
My process of conversion is following: 

- Reformats text to Python (not even valid Python) with hacky script (I don't want to input the pages of code manully)
- Edit Python to make it valid
- Run game and collect the dumps
- Work with code (cycle)
  - Compare dumps with master dumps, fix mismatches
  - Check logs for errors


If any C++ API is broken, the diff for that parts is not generated. So this code could have a lot of "conversion mistakes".   Since last time I run it, many fixes for C++ was merged, so I'll give it a try once again.

2025-02-20 13:48 UTC, o01eg requested changes

2025-02-20 13:48 UTC, o01eg commented on default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.py
> +                | ContainedBy(condition=Contains(scope=Monster & Unowned & ~HasDesign(name="SM_EXP_OUTPOST")))
```
default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.py:136: error: Unexpected keyword argument "scope" for "Contains"  [call-arg]
default/scripting/focs/_effects.pyi:325: note: "Contains" defined here
```

2025-02-20 13:48 UTC, o01eg commented on default/scripting/buildings/CULTURE_LIBRARY.focs.py
> +    tags="ANTIQUATED",
default/scripting/buildings/CULTURE_LIBRARY.focs.py:29: error: Argument "tags" to "BuildingType" has incompatible type "str"; expected "list[str] | None"  [arg-type]

2025-02-20 21:54 UTC, Cjkjvfnby commented
Lets merge this reviews, related to parsing:

https://github.com/freeorion/freeorion/pull/5116
https://github.com/freeorion/freeorion/pull/5115
https://github.com/freeorion/freeorion/pull/5110

2025-02-20 22:10 UTC, Cjkjvfnby commented on default/scripting/buildings/CULTURE_LIBRARY.focs.py
> +    tags="ANTIQUATED",
I forgot to run a check for all files after I changed typing.

2025-02-20 22:16 UTC, Cjkjvfnby commented
When typing, I can define declaration by using only keywords and positional. 

I have defined `def ContainedBy(condition: _Condition, /) -> _Condition: ...`  to use only positional (`/` at the end), and in IDE and by tools, I can detect wrong usages. 

Can we agree that all functions with a single argument use positional and all functions with multiple arguments strictly use keyword arguments? 

In that case, I can update all typing declarations and this will save me and other people from errors.

2025-02-21 03:23 UTC, o01eg commented
> Can we agree that all functions with a single argument use positional and all functions with multiple arguments strictly use keyword arguments?

Then we need to rewrite C++ implementation to use positional arguments in all those functions.

2025-02-21 06:09 UTC, o01eg commented
> Lets merge this reviews, related to parsing:
> 
> #5116 #5115 #5110

Filename is broken for some unknown reason on python 3.9 and actually all those PRs aren't solve any errors in parsing.

2025-02-21 11:13 UTC, Cjkjvfnby commented
> Filename is broken for some unknown reason on python 3.9 and actually all those PRs aren't solve any errors in parsing.

Specifically filename should make my life a bit better.

I'll get the master build this evening and continue to work on conversion.  I think we can extract some building and already merge them as separate review.

2025-02-21 17:46 UTC, Cjkjvfnby commented
Do we build Windows binary after each master? 

I don't see them in the last master:

https://github.com/freeorion/freeorion/actions/runs/13449328737

2025-02-21 17:55 UTC, o01eg commented
I suppose I lost them when I worked on automatic weekly test builds.

2025-02-22 15:57 UTC, o01eg requested changes

2025-02-22 15:57 UTC, o01eg commented on default/scripting/buildings/CONC_CAMP_REMNANT.focs.py
> +                    & HasIndustry(high=Source.Planet.TargetIndustry + 2)
Looks like there should be `Industry` but there is ambiguous using of `Industry` as condition for industry meter and as resource enum.

2025-02-22 15:57 UTC, o01eg commented on default/scripting/buildings/CONC_CAMP_REMNANT.focs.py
> +    location=~All,
`IsAnyObject`

2025-02-22 16:03 UTC, Cjkjvfnby commented on default/scripting/buildings/CONC_CAMP_REMNANT.focs.py
> +                    & HasIndustry(high=Source.Planet.TargetIndustry + 2)
give me 10 minutes and I'll push a bunch of fixes.  I am working in it right now. 

Same problem with `HasDesign`

2025-02-22 16:11 UTC, Cjkjvfnby commented
I have problems with `Industry` and `TypeError: '<=' not supported between instances of 'ValueRefInt' and 'int'`

```
EXPERIMENTOR_SPAWN_AI_AGGRESSION_CHECK: bool = GalaxyMaxAIAggression <= 2
```


Raw logs:
```
[debug] timer : ScopedTimer.cpp:67 : parse_file "CONC_CAMP.focs.py" time:     1239 µs
[error] ai : PythonCommon.cpp:142 : Traceback (most recent call last):
[error] ai : PythonCommon.cpp:142 :   File "<string>", line 48, in <module>
[error] ai : PythonCommon.cpp:142 : TypeError: '__ResourceType' object is not callable
[error] ai : PythonParser.cpp:364 : Unable to parse data file .../scripting/buildings\CONC_CAMP_REMNANT.focs.py
[debug] timer : ScopedTimer.cpp:67 : parse_file "EVACUATION.focs.py" time:     1397 µs
[error] ai : PythonCommon.cpp:142 : Traceback (most recent call last):
[error] ai : PythonCommon.cpp:142 :   File "<string>", line 59, in <module>
[error] ai : PythonCommon.cpp:142 : TypeError: '<=' not supported between instances of 'ValueRefInt' and 'int'
[error] ai : PythonParser.cpp:364 : Unable to parse data file .../scripting/buildings\EXPERIMENTOR_OUTPOST.focs.py
```

2025-02-22 16:12 UTC, Cjkjvfnby commented on default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.py
> +                | ContainedBy(Contains(Monster & Unowned & ~Design(name="SM_EXP_OUTPOST")))
Maybe Convert Design to IsDesign?

2025-02-22 16:12 UTC, o01eg commented on default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.py
> +                | ContainedBy(Contains(Monster & Unowned & ~Design(name="SM_EXP_OUTPOST")))
Or `HasDesign`? @geoffthemedio

2025-02-24 19:40 UTC, o01eg requested changes

2025-02-24 19:40 UTC, o01eg commented on default/scripting/buildings/COLONY_INDEPENDENCE_DECREE.focs.py
> +    captureresult=Destroy,
`DestroyOnCapture`

2025-02-24 19:51 UTC, geoffthemedio commented on default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.py
> +                | ContainedBy(Contains(Monster & Unowned & ~Design(name="SM_EXP_OUTPOST")))
I prefer `HasDesign`

2025-02-25 14:54 UTC, o01eg commented
All checks passed, could we merge it, @Cjkjvfnby  ?

2025-02-25 21:31 UTC, Cjkjvfnby commented
Most of the building works, I extract them as a separate request  https://github.com/freeorion/freeorion/pull/5133

2025-02-28 19:51 UTC, o01eg commented
@Cjkjvfnby Could you rebase it and fix conflicts?

2025-02-28 20:41 UTC, Cjkjvfnby commented
Some math thing is left.  (Since this file was not parsed it could have some mismathces)
```
[error] ai : PythonCommon.cpp:142 : Traceback (most recent call last):
[error] ai : PythonCommon.cpp:142 :   File "<string>", line 69, in <module>
[error] ai : PythonCommon.cpp:142 : TypeError: No registered converter was able to produce a C++ rvalue of type double from this Python object of type ValueRefInt
[error] ai : PythonParser.cpp:367 : Unable to parse data file j:/projects/freeorion/default\scripting/buildings\EXPERIMENTOR_OUTPOST.focs.py
```

2025-03-01 06:17 UTC, o01eg requested changes

2025-03-01 06:17 UTC, o01eg commented on default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.py
> +            sortkey=DirectDistanceBetween(target=Source.ID, source=LocalCandidate.ID),
positional arguments

2025-03-01 07:11 UTC, o01eg requested changes

2025-03-01 07:11 UTC, o01eg commented on default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.py
> +                | ContainedBy(Contains(Monster & Unowned & ~Design(name="SM_EXP_OUTPOST")))
@Cjkjvfnby It's landed in parser as `HasDesign`

2025-03-04 23:00 UTC, Cjkjvfnby commented
I have two repeating items in the diff: 

I don't get where this affiliation = AnyEmpire is set.  [original file](https://github.com/freeorion/freeorion/blob/3192718e00ef91b2739c80508949ab6a0ac8d5ef/default/scripting/buildings/EXPERIMENTOR_OUTPOST.focs.txt)
```diff
                           tag = predefinedshipdesign data = "SM_PSIONIC_SNOWFLAKE"  tag = species data = "SP_EXPERIMENTOR"  tag = rawtext data = "2" ]
-                    affiliation = AnyEmpire                AddStarlanes endpoints =                 NumberOf number = 1 condition =
+                    affiliation = TheEmpire                AddStarlanes endpoints =                 NumberOf number = 1 condition =
                     And [
                         MinimumNumberOf number = 5 sortkey = DirectDistanceBetween object = Source.ID object = LocalCandidate.ID condition =
```


Values are printed in different formats. 
```diff
-                    Turn low = ((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN" + 50.000000 * (5.000000 - () // StaticCast{int,double}
-                        ) + 1000.000000 * (() // StaticCast{int,double}
-                         <= 2.000000)) * (1.200000 - () // StaticCast{int,double}
-                         / 10.000000) * max(1.000000, () // StaticCast{int,double}
-                         / 200.000000) ^ 0.400000 + 71.000000) // StaticCast{double,int}
-                         high = ((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN" + 50.000000 * (5.000000 - () // StaticCast{int,double}
-                        ) + 1000.000000 * (() // StaticCast{int,double}
-                         <= 2.000000)) * (1.200000 - () // StaticCast{int,double}
-                         / 10.000000) * max(1.000000, () // StaticCast{int,double}
-                         / 200.000000) ^ 0.400000 + 130.000000) // StaticCast{double,int}
+                    Turn low = (((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN") // StaticCast{int,double}
+                         + 50.000000 * (5.000000 - () // StaticCast{int,double}
+                        ) + 1000.000000 * (( <= 2)) // StaticCast{int,double}
+                        ) * (1.200000 - ( / 10) // StaticCast{int,double}
+                        ) * max(1.000000, ( / 200) // StaticCast{int,double}
+                        ) ^ 0.400000 + 71.000000) // StaticCast{double,int}
+                         high = (((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN") // StaticCast{int,double}
+                         + 50.000000 * (5.000000 - () // StaticCast{int,double}
+                        ) + 1000.000000 * (( <= 2)) // StaticCast{int,double}
+                        ) * (1.200000 - ( / 10) // StaticCast{int,double}
+                        ) * max(1.000000, ( / 200) // StaticCast{int,double}
+                        ) ^ 0.400000 + 130.000000) // StaticCast{double,int}
```

2025-03-05 17:32 UTC, o01eg commented
Default value of `affiliation` in `GenerateSitRepMessage` depends on other argument what I haven't implem`ented yet.

`Turn` values looks hard, I'll try to see if I can fix their appearances and make it more pretty.

2025-03-07 21:30 UTC, Cjkjvfnby commented
Now everything looks in place.  Diff is quite big.  

Most of the cases are becasue formatting, and one because of the Or with a single argument.  I think we can merge it, and start converting other building.

```diff
@@ -44,11 +44,12 @@
             priority = 100
             effects = [
                 SetMaxShield value = Value + 60000.000000 * GameRule name = "RULE_SHIP_STRUCTURE_FACTOR"
-                SetMaxDefense value = Value + (GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN" + 50.000000 * (5.000000 - (GalaxyMaxAIAggression) // StaticCast{int,double}
-                    ) + 1000.000000 * ((GalaxyMaxAIAggression) // StaticCast{int,double}
-                     <= 2.000000)) * (1.200000 - (GalaxyPlanetDensity) // StaticCast{int,double}
-                     / 10.000000) * max(1.000000, (GalaxySize) // StaticCast{int,double}
-                     / 200.000000) ^ 0.400000 * GameRule name = "RULE_SHIP_WEAPON_DAMAGE_FACTOR"
+                SetMaxDefense value = Value + ((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN") // StaticCast{int,double}
+                     + 50.000000 * (5.000000 - (GalaxyMaxAIAggression) // StaticCast{int,double}
+                    ) + 1000.000000 * ((GalaxyMaxAIAggression <= 2)) // StaticCast{int,double}
+                    ) * (1.200000 - (GalaxyPlanetDensity / 10) // StaticCast{int,double}
+                    ) * max(1.000000, (GalaxySize / 200) // StaticCast{int,double}
+                    ) ^ 0.400000 * GameRule name = "RULE_SHIP_WEAPON_DAMAGE_FACTOR"
                 SetMaxTroops value = Value + 300.000000
                 SetDetection value = Value + 100.000000
             ]
@@ -56,16 +57,13 @@
             scope =
                 Object id = Source.PlanetID
             activation =
-                Or [
-                    Not
-                        ContainedBy condition =
-                            Contains condition =
-                                And [
-                                    Ship
-                                    OwnedBy affiliation = AnyEmpire
-                                ]
-
-                ]
+                Not
+                    ContainedBy condition =
+                        Contains condition =
+                            And [
+                                Ship
+                                OwnedBy affiliation = AnyEmpire
+                            ]
             priority = 100
             effects = [
                 SetDefense value = Value + 10.000000 * GameRule name = "RULE_SHIP_WEAPON_DAMAGE_FACTOR"
@@ -337,11 +335,12 @@
                 ]
             activation =
                 Or [
-                    Turn high = ((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN" + 50.000000 * (5.000000 - (GalaxyMaxAIAggression) // StaticCast{int,double}
-                        ) + 1000.000000 * ((GalaxyMaxAIAggression) // StaticCast{int,double}
-                         <= 2.000000)) * (1.200000 - (GalaxyPlanetDensity) // StaticCast{int,double}
-                         / 10.000000) * max(1.000000, (GalaxySize) // StaticCast{int,double}
-                         / 200.000000) ^ 0.400000) // StaticCast{double,int}
+                    Turn high = (((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN") // StaticCast{int,double}
+                         + 50.000000 * (5.000000 - (GalaxyMaxAIAggression) // StaticCast{int,double}
+                        ) + 1000.000000 * ((GalaxyMaxAIAggression <= 2)) // StaticCast{int,double}
+                        ) * (1.200000 - (GalaxyPlanetDensity / 10) // StaticCast{int,double}
+                        ) * max(1.000000, (GalaxySize / 200) // StaticCast{int,double}
+                        ) ^ 0.400000) // StaticCast{double,int}
                         
                     Not
                         ContainedBy condition =
@@ -364,16 +363,18 @@
                 Source
             activation =
                 And [
-                    Turn low = ((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN" + 50.000000 * (5.000000 - (GalaxyMaxAIAggression) // StaticCast{int,double}
-                        ) + 1000.000000 * ((GalaxyMaxAIAggression) // StaticCast{int,double}
-                         <= 2.000000)) * (1.200000 - (GalaxyPlanetDensity) // StaticCast{int,double}
-                         / 10.000000) * max(1.000000, (GalaxySize) // StaticCast{int,double}
-                         / 200.000000) ^ 0.400000) // StaticCast{double,int}
-                         high = ((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN" + 50.000000 * (5.000000 - (GalaxyMaxAIAggression) // StaticCast{int,double}
-                        ) + 1000.000000 * ((GalaxyMaxAIAggression) // StaticCast{int,double}
-                         <= 2.000000)) * (1.200000 - (GalaxyPlanetDensity) // StaticCast{int,double}
-                         / 10.000000) * max(1.000000, (GalaxySize) // StaticCast{int,double}
-                         / 200.000000) ^ 0.400000 + 35.000000) // StaticCast{double,int}
+                    Turn low = (((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN") // StaticCast{int,double}
+                         + 50.000000 * (5.000000 - (GalaxyMaxAIAggression) // StaticCast{int,double}
+                        ) + 1000.000000 * ((GalaxyMaxAIAggression <= 2)) // StaticCast{int,double}
+                        ) * (1.200000 - (GalaxyPlanetDensity / 10) // StaticCast{int,double}
+                        ) * max(1.000000, (GalaxySize / 200) // StaticCast{int,double}
+                        ) ^ 0.400000) // StaticCast{double,int}
+                         high = (((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN") // StaticCast{int,double}
+                         + 50.000000 * (5.000000 - (GalaxyMaxAIAggression) // StaticCast{int,double}
+                        ) + 1000.000000 * ((GalaxyMaxAIAggression <= 2)) // StaticCast{int,double}
+                        ) * (1.200000 - (GalaxyPlanetDensity / 10) // StaticCast{int,double}
+                        ) * max(1.000000, (GalaxySize / 200) // StaticCast{int,double}
+                        ) ^ 0.400000 + 35.000000) // StaticCast{double,int}
                         
                     Random probability = 0.200000 * (1.000000 + (GalaxyMaxAIAggression) // StaticCast{int,double}
                         ) / 5.000000
@@ -441,11 +442,12 @@
                 Source
             activation =
                 And [
-                    Turn low = ((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN" + 50.000000 * (5.000000 - (GalaxyMaxAIAggression) // StaticCast{int,double}
-                        ) + 1000.000000 * ((GalaxyMaxAIAggression) // StaticCast{int,double}
-                         <= 2.000000)) * (1.200000 - (GalaxyPlanetDensity) // StaticCast{int,double}
-                         / 10.000000) * max(1.000000, (GalaxySize) // StaticCast{int,double}
-                         / 200.000000) ^ 0.400000 + 36.000000) // StaticCast{double,int}
+                    Turn low = (((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN") // StaticCast{int,double}
+                         + 50.000000 * (5.000000 - (GalaxyMaxAIAggression) // StaticCast{int,double}
+                        ) + 1000.000000 * ((GalaxyMaxAIAggression <= 2)) // StaticCast{int,double}
+                        ) * (1.200000 - (GalaxyPlanetDensity / 10) // StaticCast{int,double}
+                        ) * max(1.000000, (GalaxySize / 200) // StaticCast{int,double}
+                        ) ^ 0.400000 + 36.000000) // StaticCast{double,int}
                         
                     Random probability = 0.100000 * (1.000000 + (GalaxyMaxAIAggression) // StaticCast{int,double}
                         ) / 5.000000
@@ -513,16 +515,18 @@
                 Source
             activation =
                 And [
-                    Turn low = ((GameRule name = "RULE_EXPERIMENTORS_SPAWN_BASE_TURN" + 50.000000 * (5.000000 - (GalaxyMaxAIAggression) // StaticCast{int,double}
-         [...]

2025-03-08 04:53 UTC, o01eg approved these changes

2025-03-08 21:06 UTC, merged