do not stack nest removal with nest spawning
freeorion/freeorion pull request #4957
Opened 2024-06-16 01:23 UTC by Blue-Award

fixes https://github.com/freeorion/freeorion/issues/4952

maybe the effect stacking was to prevent monster spawning when nest is eradicated, but in practice I see nest eradication prevented when monster spawns.

Removing stacking group was easiest fix for me though it may mean that monster spawns as nest is being eradicated, by I suppose that's better than nest not being eradicated and losing production on the building

I am open to suggestions what other stacking group it could be so that eradication triggers first and monster spawning doesn't trigger later, if that's possible. Ultimately I don't mind though if monster spawns but nest gets removed

2024-06-16 16:33 UTC, agrrr3 commented
>  I don't mind though if monster spawns but nest gets removed

+1 from me

if we really want to prevent the spawn on removal, the stackinggroup must not be removed, but instead the removal should happen first by getting happening at earlier priority.

2024-06-17 16:32 UTC, Blue-Award commented
I don't know how to set up a stacking group priority order. Tried to find if the _NEST_STACK is defined somewhere and at least I've found that comment in monster_nest.macros could be fixed too to no longer mention stacking with eradicator

But from what you say, I am guessing the stacking group is just a label to group common effects, and then separate Priority stuff should be added to distinguish what should be happening in given stacking group?

I found there are bunch of priorities defined in priorities.macros so maybe I could reuse something there rather than introducing new priorities? I guess using BEFORE_ANYTHING_ELSE_PRIORITY for eradicator and DEFAULT_PRIORITY for spawning monsters is not an offensive use of the pre-existing priorities?

2024-06-17 17:12 UTC, Blue-Award commented
OK I've added the priorities, while I don't mind preventing monster to spawn it is nicer to do it

2024-06-18 14:27 UTC, agrrr3 commented
> I don't know how to set up a stacking group priority order. 

there is no such thing explicitely. there is an order in which effects are applied which is partly deterministic, first checking effectgroup priority and then implicit order (see [FOCS scripting details application ordering](https://freeorion.org/index.php/FOCS_Scripting_Details#Effect_Evaluation_.26_Application_Ordering)).
stackinggroup only allows the first instance of an effect to apply, ignoring any others. You might create a new building or tech with the same stackinggroup name, and only the first one would apply. 

if multiple effects have the same stackinggroup, only the first one per target object which activates gets applied.
it is like when an effect is executed, a sticker with the stackinggroup label is applied to all target objects. and if there an effect is executed and it already has such a sticker, the effect is not applied. 

My guess how that works in the backend: such objects get excluded from scope; (or maybe on application? or activation??).

Note that if no priority is set, it uses DEFAULT_PRIORITY

> I found there are bunch of priorities defined in priorities.macros so maybe I could reuse something there rather than introducing new priorities? I guess using BEFORE_ANYTHING_ELSE_PRIORITY for eradicator and DEFAULT_PRIORITY for spawning monsters is not an offensive use of the pre-existing priorities?

yes, that is a good idea; I think BEFORE_ANYTHING_ELSE_PRIORITY is also fine.

2024-06-18 14:29 UTC, agrrr3 requested changes
some files include the priorities.macros without actually using it. please remove those includes.
i think the include belongs into the monster_nest.macros
else looks good to mie

2024-06-19 11:33 UTC, Blue-Award commented
> some files include the priorities.macros without actually using it. please remove those includes. i think the include belongs into the monster_nest.macros else looks good to mie

Yea I wasn't entirely sure where to put that include, seemed to me from looking at other places that it shouldn't go to macros file, but rather to the actual focs files, so I went with that, but if you advise otherwise, then sure, thank you!

Suppose I could get away with it by not putting [[DEFAULT_PRIORITY]] explicitly, since it is, well, default if nothing is provided. I kinda liked that it is provided explicitly with a comment about eradication, but maybe could be skipped?

2024-06-19 16:40 UTC, Blue-Award commented
ok I've put the priorities' include into nest macros so the individual nests have no change, only the macros file

2024-06-22 21:00 UTC, Blue-Award commented
ready for re-review and hopefully merged, not sure if we're getting update to server while @o01eg is away but maybe?

2024-06-25 09:08 UTC, agrrr3 approved these changes
LGTM

2024-06-25 18:46 UTC, geoffthemedio commented
I'm a bit concerned about the `BEFORE_ANYTHING_ELSE_PRIORITY` prioirty... Is this particularly special to warrant that? Seems like it potentially could cause some weird issue... Is there a less drastic priority that could be used?

2024-06-25 20:36 UTC, agrrr3 commented
> I'm a bit concerned about the `BEFORE_ANYTHING_ELSE_PRIORITY` prioirty... Is this particularly special to warrant that? Seems like it potentially could cause some weird issue... Is there a less drastic priority that could be used?

With the current two rounds of effect application (resource-production & post-object-creation) in theory I think it would make sense to have the effect after production meters  (which is very late) in order not to skew the predicted values. At the same time it should before all non-production effects (?default priority?) because in the post-object-creation effect application the nest does not exist anymore. Anyway default priority is much earlier than very late, so this timing is impossible.

Probably there is a reason why default priority is where it is (at TARGET_BEFORE_SCALING_PRIORITY). Else Priority 650 would make sense to me (after focus change penalty, but before final meter override). 

Does effect production meter prediction calculate with removed items from effects? In that case anything early would make sense.

currently AFAICT no effect interacts with the eradictor and also not with the spawned monsters, so any combination where the eradication happens before the spawn is fine (e.g. eradicator at TARGET_FIRST_PRIORITY, spawning at DEFAULT priority).

2024-06-25 21:37 UTC, Blue-Award commented
I guess there are species that like or dislike this or that nest, so the removal of nest can cause stability shift. No clue how it interacts though, and generally game isn't good in accounting what will happen when stability goes down or up anyway

2024-06-25 22:35 UTC, agrrr3 commented
> I guess there are species that like or dislike this or that nest, so the removal of nest can cause stability shift. No clue how it interacts though, and generally game isn't good in accounting what will happen when stability goes down or up anyway

Ok. I checked with imperial palace destruction on turn 2. The stability meter prediction does not care for destroy effects. 
So we should make the removal consistent with that, i.e. remove the special later.
So I also checked what happens when i do the destruction after everything else.. and it is not different from an early destruction. I think because of the second effect application and we should really get rid of that/make that a phase. 

If making this future-proof, we should use different stacking groups, remove the building very late like at e.g. prio CONCENTRATION_CAMP_PRIORITY or END_CLEANUP_PRIORITY, add a `Not Contains And [ Building name = "BLD_NEST_ERADICATOR" OwnedBy empire = Source.Owner ]` to the activation condition of both effect groups in `default/scripting/specials/planet/monster_nest/monster_nest.macros` MONSTER_NEST macro.

2024-06-26 15:12 UTC, Blue-Award commented
does it mean in the end we don't prevent the monster spawn?

I'm bit hazy on what you're talking about, especially the part about using different stacking groups. Is it something I may pass onto you? I mean as far as using different priorities names would be bit weird and I don't understand what's the trouble with accounting for effects here, like moving threshold of stability to 10 for example isn't exactly predicted what will happen next turn in the GUI so the accounting around nest removal doesn't bother me personally and not sure what is there to fix also, not only how to fix that

2024-07-01 06:41 UTC, agrrr3 commented
> does it mean in the end we don't prevent the monster spawn?

no, we prevent it by changing the spawning effect activation instead of preventing it by using stacking groups.  So if the building is there, do not activate the spawn effect.

> 
> Is it something I may pass onto you? 

i made a PR #4967 with what I meant based on your code (diff is this commit fb17a9cb06e84e379a7de78ffdea5bcf54cde485). 

> example isn't exactly predicted what will happen next turn in the GUI so the accounting around nest removal doesn't bother me personally

i am trying to get this a little more correct than it is currently. note also my ~fix only works if we change the backend effect application (which i intend to)

2024-07-24 06:59 UTC, Blue-Award commented
ok so this can be closed now, right? cause the other one got merged?

2024-08-02 12:42 UTC, closed without merging