Added Ancient Guardians species as an alternative to Sentries guardin…
freeorion/freeorion pull request #837
Opened 2016-08-05 09:15 UTC by Deepsloth

…g specials.

2016-08-05 09:16 UTC, Deepsloth commented
Discussion: http://www.freeorion.org/forum/viewtopic.php?f=15&t=10162

Post v0.4.6

2016-08-05 09:20 UTC, MatGB commented on default/stringtables/en.txt
> +Ancient Guardians seld destruct
self

2016-08-05 09:21 UTC, MatGB commented on default/stringtables/en.txt
> +'''Guardian Robots constructed by the Precursor civilizations aeons ago
Better to say "a Precursor", we've got several in game already, no need to say which one.

2016-08-05 09:27 UTC, MatGB commented on default/stringtables/en.txt
> +'''Constructed by precusor technology these ancient machines can adapt to and fight in any kind of environment. With unwavering loyalty and duteousness they have protected the planet from any invader
I dislike "duteousness", I had to look up whether it was an actual word and it's very rarely used (so much so Google won't even give me an ngram of it, insisting to give me results for duteous instead). "Commitment" might be better, not sure tho.

2016-08-05 09:29 UTC, MatGB commented
These do look very fun. Not sure about troops as a multiplier of target population, that prevents partial destruction from bombardment which ought to be a valid tactic, multiplier of current pop?

(it is of course another special giving Egassem a potential early advantage...)

2016-08-05 09:56 UTC, Deepsloth commented
Troops are not dependent on target population. "Target.Population" is the current population of the target. The other would be "Target.TargetPopulation". I love FOCS.

2016-08-05 10:25 UTC, MatGB commented
Good point, yeah, see, still not grokking FOCS properly.

2016-10-01 02:02 UTC, MatGB requested changes
I like the idea of this and want to expand on it, but better to get this in then use it for more down the line, fairly sure it needs AI updates as well.

2016-10-01 02:02 UTC, MatGB commented on default/scripting/species/SP_ANCIENT_GUARDIANS.focs.txt
> +        [[HAS_MINING_FOCUS]]
Mining is gone, I was wandering why I hadn't found any until I checked my logs.

2016-10-01 02:02 UTC, MatGB commented on default/scripting/species/SP_ANCIENT_GUARDIANS.focs.txt
> +            description = "ANCIENT_PLANETARY_SHIELD"
as of ec2f1cc this needs a _DESC suffix, @adrianbroher is on a bug hunt

2016-10-01 02:02 UTC, MatGB commented on default/scripting/species/SP_ANCIENT_GUARDIANS.focs.txt
> +            description = "ANCIENT_DEFENSE_TROOPS"
same for this

2016-10-01 02:02 UTC, MatGB commented on default/stringtables/en.txt
> +
this and the below shield are where the merge conflicts were for me, I made a hash of sorting it out so better to be redone, both need the _desc suffix as above.

2016-10-01 02:09 UTC, MatGB commented on default/scripting/species/SP_ANCIENT_GUARDIANS.focs.txt
> +                    message = "EFFECT_ANCIENT_GUARDIANS_CAPTURED"
Again, needs the label here.

2016-10-01 02:13 UTC, MatGB commented
Think they need an effect that sets their planetary population to max at start of game, if they're meant to be ancient they should have max pop not be growing on game start, especially given the troop effects.

Beyond that, finally got them working with current backend and I really like. Moving forward, the AI team need to review and possibly update the AI.

After that's been done, I'd like to expand the concept: for balance reasons I'd like the chance of guard on most of the big specials to always apply, so if a sentinel isn't generated these guys always should be, and possibly with a bonus of some sort for the bigger monsters, I've been uncomfortable for ages that ancient ruins can sometimes give you a really powerful unlock early with no defence whatsoever, etc.  But that's an ongoing balance thing, these are cool and I like them as is instead of sentries.

2016-10-01 06:52 UTC, MatGB commented
Also, Sitrep Priority needs to be added to the self destruct so it's just above the "dies out completely" message.

2016-10-01 07:51 UTC, Morlic-fo requested changes
This will need some AI adaptations but I wouldn't consider those to be critical enough to delay the merge.

@MatGB As before, please open another AI issue when you merge this.

2016-10-01 07:51 UTC, Morlic-fo commented on default/scripting/species/SP_ANCIENT_GUARDIANS.focs.txt
> +    tags = [ "ROBOTIC" "AI_TAG_NO_INDUSTRY" "AI_TAG_NO_RESEARCH" "AI_TAG_AVERAGE_SUPPLY"]
The AI_TAG_ prefix was removed in e39340464446e7bd3b268088ac4f0d03393a20e1. Just use "NO_INDUSTRY" etc.

2016-10-01 07:51 UTC, Morlic-fo commented on default/scripting/species/SP_ANCIENT_GUARDIANS.focs.txt
> +        [[HAS_MINING_FOCUS]]
Does it make sense for a non-playable, non-conquerable species to have any foci?

2016-10-01 07:51 UTC, Morlic-fo commented on default/scripting/species/SP_ANCIENT_GUARDIANS.focs.txt
> +    tags = [ "ROBOTIC" "AI_TAG_NO_INDUSTRY" "AI_TAG_NO_RESEARCH" "AI_TAG_AVERAGE_SUPPLY"]
Also I'd like to have a new tag "DESTROYED_ON_CONQUEST" for AI purposes.

2016-10-01 07:51 UTC, Morlic-fo commented on default/scripting/specials/specials.macros
> +                    ]
Any reason to use brackets and 3 lines for a singe-line-statement?

2016-10-01 07:51 UTC, Morlic-fo commented on default/stringtables/en.txt
> +'''Constructed by precusor technology these ancient machines can adapt to and fight in any kind of environment. With unwavering loyalty and commitment they have protected the planet from any invaders
Not a native speaker - shouldn't there be a comma after ```Constructed by precusor technology```, ```With unwavering loyalty and commitment```, and ```Upon being captured```?

2016-10-01 07:58 UTC, Morlic-fo commented
> Moving forward, the AI team need to review and possibly update the AI.
> 
> After that's been done, I'd like to expand the concept: for balance reasons I'd like the chance of guard on most of the big specials to always apply

While this PR may be merged without the AI adaptations, the concept should not be expanded until the relevant AI changes have been made. A rare special that the AI acts weird on is fine. Having half the galaxy being populated by Ancient Guardians is a different matter...

2016-10-01 08:29 UTC, MatGB commented on default/stringtables/en.txt
> +'''Constructed by precusor technology these ancient machines can adapt to and fight in any kind of environment. With unwavering loyalty and commitment they have protected the planet from any invaders
I am, but am terrible with punctuation, I checked with the editor-I-live-with and she says yes in all three, the latter two being optional for reading-as-text but required if to be read aloud. The first definitely as it's two clauses.

I wouldn't have put any of them in either, so good catch.

2016-10-01 08:31 UTC, MatGB commented
>A rare special that the AI acts weird on is fine. Having half the galaxy being populated by Ancient Guardians is a different matter...

Fair enough: what I'm hoping for is that the existing chance-of-guard becomes chance of guard monster or chance of getting these, so that everything that gives a decent bonus gets something. But it's a longer term thing and is only a balance quibble not a major concern, it would also allow us to maintain having ancient ruins in No Monsters galaxies without me having conniptions over the balance issues there (ie the chance of a monster is determined by monster setting else you get these)

2016-10-01 12:28 UTC, Deepsloth commented
I made a new branch with a fixed and tweaked version of the ancient guardians, but there is one requested change i haven't figured out:

"Also, Sitrep Priority needs to be added to the self destruct so it's just above the "dies out completely" message."

How do i implement that?

2016-10-01 14:10 UTC, dbenage-cx commented
For now: https://github.com/freeorion/freeorion/blob/master/default/customizations/common_user_customizations.txt contains an ordered list of sitreps under `FUNCTIONAL_SITREP_PRIORITY_ORDER`.  These sitreps are displayed before those with no entry.

2016-10-01 20:27 UTC, closed without merging