Added the new special: Kraken in the Ice.
freeorion/freeorion pull request #850
Opened 2016-08-09 08:36 UTC by Deepsloth

Discussion: http://www.freeorion.org/forum/viewtopic.php?f=15&t=10173

Post v0.4.6.

2016-09-27 14:41 UTC, dbenage-cx requested changes
Description inconsistent

2016-09-27 14:41 UTC, dbenage-cx commented on default/stringtables/en.txt
> +'''With the knowledge of the technologies [[tech SHP_DOMESTIC_MONSTER]] and [[tech LRN_XENOARCH]], the [[predefinedshipdesign SM_WHITE_KRAKEN]] can be resurrected and controlled by building a [[build
Not seeing any requirement or other mention of SHP_DOMESTIC_MONSTER.

2016-09-27 14:48 UTC, dbenage-cx commented
Curious if the extreme rarity is intended.  Very few games will have this actually placed on the map.

2016-09-27 21:13 UTC, Deepsloth commented
I will add the check for SHP_DOMESTIC_MONSTER.

Have to test the rarity. Is it so extreme?

2016-09-27 23:57 UTC, Cjkjvfnby requested changes

2016-09-27 23:57 UTC, Cjkjvfnby commented on default/stringtables/en.txt
> +'''The White Kraken is a white-colored prehistoric ancestor of the Kraken Space Monster.'''
No need quotes here

2016-09-28 13:06 UTC, dbenage-cx requested changes

2016-09-28 13:06 UTC, dbenage-cx commented on default/scripting/buildings/XENORESURRECTION_LAB.focs.txt
> +                    message = "EFFECT_WHITE_KRAKEN_RESURRECTED"
`label` is now required, as of d55b16cf

2016-09-28 13:24 UTC, dbenage-cx commented
> Have to test the rarity. Is it so extreme?
My attempts with 10 different seeds resulted in 0 placements(200 systems, high specials).  I assume this is mostly from the rarity of a suitable tundra planet.
Increasing the limit results in some placement, but not 100% of the limit.  If I read it correctly, a spawnrate of 9.0 should give a 90% chance with low specials.

2016-09-29 18:21 UTC, adrianbroher commented
Please don't merge master.

2016-09-29 18:27 UTC, Deepsloth commented
How can i fix that? How can i avoid that in the future?

2016-09-29 18:57 UTC, adrianbroher commented
> How can i fix that?

Use `git rebase` or `git pull --rebase` when you're on your topic branch.

> How can i avoid that in the future?

Don't use `git merge master` or `git pull` when you're on your topic branch.

=)

Seriously though: the problem with merging master into a topic branch caused us several times to re-introduce bugs, see also [the corresponding discussion](http://www.freeorion.org/forum/viewtopic.php?f=9&t=9595) about that topic and the introduction of the policy.

If you have trouble with the concept and the steps to approach this I suggest you to read the [Merging vs. Rebasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) tutorial from Atlassian.

2016-09-29 19:48 UTC, MatGB commented
For this specific the easiest thing is for me to cherry pick it and push direct to master, I'll do it later.

2016-09-29 21:04 UTC, MatGB commented
K, I've pushed the commits in directly and written up how I did it on the howto thread [Post](http://www.freeorion.org/forum/viewtopic.php?p=85827#p85827), as some of it is stuff I only learnt how to do very recently anyway. Cherry Picking is a very useful tool, especially when PR reviewing, I can put whatever I want into my Working branch and test it alongside my existing work easily.

2016-09-29 21:04 UTC, closed without merging

2016-09-30 21:39 UTC, Vezzra commented
Added the "status:merged" label to indicate that the contents of the PR actually have been merged (by cherry-picking).