Move ship design redundancy settings from UserString
freeorion/freeorion pull request #985
Opened 2016-09-25 15:50 UTC by dbenage-cx

Moves the bargain, cost, and time ratios to OptionsDB.

Removes skip list in favor of definition tags.

2016-09-25 18:58 UTC, geoffthemedio commented on UI/DesignWnd.cpp
> +    m_ratio_bargain_min = GetOptionsDB().Get<float>( "UI.ship-design.part-filters.ratio-bargain-min");
get rid of the extra space between ( and "

2016-09-25 18:59 UTC, geoffthemedio commented on default/stringtables/en.txt
> +(i) more powerful
what about otherwise equal but less expensive, or otherwise equal but faster to build parts?

2016-09-25 19:00 UTC, geoffthemedio commented on UI/DesignWnd.cpp
> +                UserStringNop("OPTIONS_DB_UI_DESIGN_PART_FILTER_MIN_BARGAIN"),
indent parameters to match left-side of first parameter

2016-09-25 19:00 UTC, geoffthemedio requested changes

2016-09-27 11:27 UTC, dbenage-cx commented on default/stringtables/en.txt
> +(i) more powerful
I aimed to relocate the documentation here, along with minor formatting adjustments.
According to this, both cases fail the first check, so the first part would not be deemed redundant.

2017-01-23 14:03 UTC, closed without merging

2017-01-29 12:03 UTC, Vezzra commented
@dbenage-cx, a short comment why you closed this as invalid would be good...